<?php
/**
 * @package    Joomla.Site
 * @copyright  (C) 2018 Open Source Matters, Inc. <https://www.joomla.org>
 * @license    GNU General Public License version 2 or later; see LICENSE.txt
 *
 * This file has been automatically generated by the Namespace Updater Plugin.
 * DO NOT EDIT THIS FILE as your changes will be overwritten.
 */

defined('_JEXEC') or die;

$loader = require JPATH_LIBRARIES . '/vendor/autoload.php';

// Configure the autoloader for the extensions
return $loader;
