CREATE TABLE IF NOT EXISTS ec_abandoned_carts (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id INT UNSIGNED NULL DEFAULT NULL,
    session_id VARCHAR(128) NOT NULL DEFAULT '',
    guest_email VARCHAR(191) NOT NULL DEFAULT '',
    guest_name VARCHAR(191) NOT NULL DEFAULT '',
    recovery_token CHAR(64) NOT NULL,
    status ENUM('active', 'recovered', 'closed') NOT NULL DEFAULT 'active',
    cart_snapshot LONGTEXT NOT NULL,
    item_count INT UNSIGNED NOT NULL DEFAULT 0,
    subtotal DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    total DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    recovery_email_1_sent_at DATETIME NULL DEFAULT NULL,
    recovery_email_2_sent_at DATETIME NULL DEFAULT NULL,
    recovery_email_3_sent_at DATETIME NULL DEFAULT NULL,
    recovered_order_id INT UNSIGNED NULL DEFAULT NULL,
    recovered_at DATETIME NULL DEFAULT NULL,
    last_activity_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_ec_abandoned_carts_recovery_token (recovery_token),
    KEY idx_ec_abandoned_carts_status_activity (status, last_activity_at),
    KEY idx_ec_abandoned_carts_email (guest_email),
    KEY idx_ec_abandoned_carts_user (user_id),
    KEY idx_ec_abandoned_carts_session (session_id),
    KEY idx_ec_abandoned_carts_recovered_order (recovered_order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;