CREATE TABLE IF NOT EXISTS `ec_subscriptions` (
    `id` bigint unsigned NOT NULL AUTO_INCREMENT,
    `order_id` bigint unsigned NOT NULL,
    `order_item_id` bigint unsigned DEFAULT NULL,
    `customer_id` bigint unsigned DEFAULT NULL,
    `customer_email` varchar(190) DEFAULT NULL,
    `product_id` bigint unsigned NOT NULL,
    `product_title` varchar(255) NOT NULL,
    `quantity` int NOT NULL DEFAULT 1,
    `status` varchar(32) NOT NULL DEFAULT 'active',
    `interval_unit` varchar(16) NOT NULL DEFAULT 'month',
    `interval_count` int NOT NULL DEFAULT 1,
    `trial_days` int NOT NULL DEFAULT 0,
    `max_cycles` int NOT NULL DEFAULT 0,
    `grace_period_days` int NOT NULL DEFAULT 7,
    `recurring_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
    `currency` varchar(10) NOT NULL DEFAULT 'PHP',
    `start_at` datetime DEFAULT NULL,
    `current_period_start_at` datetime DEFAULT NULL,
    `current_period_end_at` datetime DEFAULT NULL,
    `next_renewal_at` datetime DEFAULT NULL,
    `renewal_count` int NOT NULL DEFAULT 0,
    `cancelled_at` datetime DEFAULT NULL,
    `cancellation_reason` varchar(255) DEFAULT NULL,
    `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_ec_subscriptions_order_item_id` (`order_item_id`),
    KEY `idx_ec_subscriptions_order_id` (`order_id`),
    KEY `idx_ec_subscriptions_customer_id` (`customer_id`),
    KEY `idx_ec_subscriptions_status_next_renewal` (`status`, `next_renewal_at`),
    KEY `idx_ec_subscriptions_product_id` (`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;