<?php
/**
 * DiSyL v4.0 Template Cache
 * 
 * Manages compiled template caching for optimal performance.
 * 
 * @package Ikabud\Kernel\DiSyL\Compiler
 * @version 4.0.0
 */

namespace Ikabud\Kernel\DiSyL\Compiler;

use Ikabud\Kernel\DiSyL\v4\Parser;
use Ikabud\Kernel\DiSyL\v4\AST\DocumentNode;

/**
 * Template compilation and caching manager
 */
class TemplateCache
{
    private string $cacheDir;
    private Parser $parser;
    private TemplateCompiler $compiler;
    private bool $debug = false;
    
    /** @var array<string, CompiledTemplate> In-memory cache */
    private array $loaded = [];
    
    public function __construct(string $cacheDir, bool $debug = false)
    {
        $this->cacheDir = rtrim($cacheDir, '/');
        $this->debug = $debug;
        $this->parser = new Parser();
        $this->compiler = new TemplateCompiler();
        
        if (!is_dir($this->cacheDir)) {
            mkdir($this->cacheDir, 0755, true);
        }
    }
    
    /**
     * Get compiled template (from cache or compile fresh)
     */
    public function get(string $templatePath): CompiledTemplate
    {
        $className = $this->getClassName($templatePath);
        $cachePath = $this->getCachePath($className);
        
        // Check in-memory cache first
        if (isset($this->loaded[$className])) {
            return $this->loaded[$className];
        }
        
        // Check if recompilation needed
        if ($this->needsRecompile($templatePath, $cachePath)) {
            $this->compile($templatePath, $className, $cachePath);
        }
        
        // Validate cache file integrity before executing
        if (!$this->validateCacheFile($cachePath)) {
            // Recompile to regenerate a valid cache file
            $this->compile($templatePath, $className, $cachePath);
            if (!$this->validateCacheFile($cachePath)) {
                throw new \RuntimeException("Template cache validation failed for: {$cachePath}");
            }
        }
        
        // Load and instantiate
        require_once $cachePath;
        $fullClassName = "Ikabud\Kernel\DiSyL\Compiled\\{$className}";
        
        $template = new $fullClassName();
        $this->loaded[$className] = $template;
        
        return $template;
    }
    
    /**
     * Compile a template from source
     */
    public function compileSource(string $source, string $name = 'Anonymous'): CompiledTemplate
    {
        $className = 'Template_' . md5($source);
        $cachePath = $this->getCachePath($className);
        
        if (isset($this->loaded[$className])) {
            return $this->loaded[$className];
        }
        
        if (!file_exists($cachePath)) {
            $ast = $this->parser->parse($source, $name);
            $code = $this->compiler->compile($ast, $className);
            
            $this->writeCache($cachePath, $code);
        }
        
        // Validate cache file integrity before executing
        if (!$this->validateCacheFile($cachePath)) {
            // Regenerate from source
            $ast = $this->parser->parse($source, $name);
            $code = $this->compiler->compile($ast, $className);
            $this->writeCache($cachePath, $code);
            if (!$this->validateCacheFile($cachePath)) {
                throw new \RuntimeException("Template cache validation failed for compiled source: {$name}");
            }
        }
        
        require_once $cachePath;
        $fullClassName = "Ikabud\Kernel\DiSyL\Compiled\\{$className}";
        
        $template = new $fullClassName();
        $this->loaded[$className] = $template;
        
        return $template;
    }
    
    /**
     * Check if template needs recompilation
     */
    private function needsRecompile(string $templatePath, string $cachePath): bool
    {
        // Always recompile in debug mode
        if ($this->debug) {
            return true;
        }
        
        // Compile if cache doesn't exist
        if (!file_exists($cachePath)) {
            return true;
        }
        
        // Recompile if template is newer than cache
        return filemtime($templatePath) > filemtime($cachePath);
    }
    
    /**
     * Compile template and write to cache
     */
    private function compile(string $templatePath, string $className, string $cachePath): void
    {
        $source = file_get_contents($templatePath);
        $ast = $this->parser->parse($source, $templatePath);
        $code = $this->compiler->compile($ast, $className);
        
        $this->writeCache($cachePath, $code);
    }
    
    /**
     * Write compiled code to cache file (atomic).
     * Prepends a sentinel comment so we can validate the file was generated by
     * this compiler before executing it (defense against cache-dir tampering).
     */
    private function writeCache(string $cachePath, string $code): void
    {
        $normalizedCode = $this->normalizeCompiledCode($code);
        $sentinel = $this->buildSentinel($normalizedCode);
        $codeBody = $this->stripOpenTag($normalizedCode);
        $codeWithSentinel = "<?php // DISYL_CACHE_SENTINEL:{$sentinel}\n" . $codeBody;
        $tempPath = $cachePath . '.tmp.' . getmypid();
        
        if (file_put_contents($tempPath, $codeWithSentinel, LOCK_EX) === false) {
            throw new \RuntimeException("Failed to write template cache: {$cachePath}");
        }
        
        if (!rename($tempPath, $cachePath)) {
            @unlink($tempPath);
            throw new \RuntimeException("Failed to rename template cache: {$cachePath}");
        }
        
        // Invalidate opcache if available
        if (function_exists('opcache_invalidate')) {
            opcache_invalidate($cachePath, true);
        }
    }

    /**
     * Build an HMAC-like sentinel for the compiled code.
     * Uses a per-process secret derived from the cache directory path so that
     * even without a shared secret, files cannot trivially be copied from
     * another installation or tampered with without invalidating the check.
     */
    private function buildSentinel(string $code): string
    {
        // Use a real application secret when available so that knowing the
        // cache directory path is not sufficient to forge a sentinel.
        $appSecret = $_ENV['APP_KEY'] ?? getenv('APP_KEY') ?: '';
        if ($appSecret === '') {
            // Fallback: derive from cache dir (legacy behavior, weaker).
            $appSecret = 'DISYL_CACHE_' . sha1($this->cacheDir);
        }
        return hash_hmac('sha256', $code, $appSecret);
    }

    /**
     * Normalize compiled PHP so sentinel generation and validation operate on a
     * stable representation with a single PHP open tag prefix.
     */
    private function normalizeCompiledCode(string $code): string
    {
        return "<?php\n" . $this->stripOpenTag($code);
    }

    /**
     * Remove a leading PHP open tag from compiled code.
     */
    private function stripOpenTag(string $code): string
    {
        if (str_starts_with($code, "<?php\r\n")) {
            return substr($code, 7);
        }

        if (str_starts_with($code, "<?php\n")) {
            return substr($code, 6);
        }

        if (str_starts_with($code, '<?php')) {
            return ltrim(substr($code, 5), "\r\n");
        }

        return $code;
    }

    /**
     * Validate a cache file's sentinel before executing it.
     * Returns true if the file looks safe to require.
     */
    private function validateCacheFile(string $cachePath): bool
    {
        $firstLine = '';
        $handle = @fopen($cachePath, 'r');
        if ($handle === false) {
            return false;
        }
        $firstLine = fgets($handle) ?: '';
        $rest = stream_get_contents($handle);
        fclose($handle);

        if (!preg_match('/^<\?php \/\/ DISYL_CACHE_SENTINEL:([a-f0-9]{64})/', $firstLine, $m)) {
            return false;
        }

        $storedSentinel = $m[1];
        $originalCode = $this->normalizeCompiledCode("<?php\n" . $rest);
        $expected = $this->buildSentinel($originalCode);

        return hash_equals($expected, $storedSentinel);
    }
    
    /**
     * Get cache file path for a class
     */
    private function getCachePath(string $className): string
    {
        return $this->cacheDir . '/' . $className . '.php';
    }
    
    /**
     * Generate class name from template path.
     * Includes compiler version so stale compiled files are bypassed on upgrade.
     */
    private function getClassName(string $templatePath): string
    {
        $version = TemplateCompiler::COMPILER_VERSION;
        $hash = md5($templatePath . ':v' . $version);
        $name = preg_replace('/[^a-zA-Z0-9]/', '_', basename($templatePath, '.disyl'));
        return 'Template_' . $name . '_v' . $version . '_' . substr($hash, 0, 8);
    }
    
    /**
     * Clear all cached templates
     */
    public function clear(): int
    {
        $count = 0;
        $files = glob($this->cacheDir . '/Template_*.php');
        
        foreach ($files as $file) {
            if (unlink($file)) {
                $count++;
            }
        }
        
        $this->loaded = [];
        
        return $count;
    }
    
    /**
     * Clear cache for specific template
     */
    public function clearTemplate(string $templatePath): bool
    {
        $className = $this->getClassName($templatePath);
        $cachePath = $this->getCachePath($className);
        
        unset($this->loaded[$className]);
        
        if (file_exists($cachePath)) {
            return unlink($cachePath);
        }
        
        return true;
    }
    
    /**
     * Remove stale compiled files that don't match the current compiler version
     * or are older than the given TTL (seconds). Returns count of removed files.
     */
    public function cleanup(int $ttlSeconds = 0): int
    {
        $files = glob($this->cacheDir . '/Template_*.php');
        if (!$files) {
            return 0;
        }

        $currentVersionTag = '_v' . TemplateCompiler::COMPILER_VERSION . '_';
        $removed = 0;
        $now = time();

        foreach ($files as $file) {
            $basename = basename($file);
            $stale = false;

            // Remove files from a different compiler version
            if (strpos($basename, $currentVersionTag) === false) {
                $stale = true;
            }

            // Remove files older than TTL (if TTL > 0)
            if (!$stale && $ttlSeconds > 0) {
                $age = $now - filemtime($file);
                if ($age > $ttlSeconds) {
                    $stale = true;
                }
            }

            if ($stale && @unlink($file)) {
                $removed++;
                if (function_exists('opcache_invalidate')) {
                    opcache_invalidate($file, true);
                }
            }
        }

        return $removed;
    }

    /**
     * Get cache statistics
     */
    public function getStats(): array
    {
        $files = glob($this->cacheDir . '/Template_*.php');
        $totalSize = 0;
        
        foreach ($files as $file) {
            $totalSize += filesize($file);
        }
        
        return [
            'cache_dir' => $this->cacheDir,
            'cached_templates' => count($files),
            'total_size' => $totalSize,
            'loaded_in_memory' => count($this->loaded),
            'debug_mode' => $this->debug,
            'compiler_version' => TemplateCompiler::COMPILER_VERSION,
        ];
    }
}
