<?php
declare(strict_types=1);

require_once __DIR__ . '/../bootstrap.php';
require_once __DIR__ . '/../modules/academic_similarity/helpers.php';

$pass = 0;
$fail = 0;
function t(string $description, bool $condition, string $detail = ''): void {
    global $pass, $fail;
    if ($condition) { $pass++; echo "  ✅ {$description}\n"; }
    else { $fail++; echo "  ❌ {$description}" . ($detail ? " — {$detail}" : '') . "\n"; }
}

file_put_contents(__DIR__ . '/../storage/logs/app.log', '');
file_put_contents(__DIR__ . '/../storage/logs/error.log', '');

echo "\n=== Academic Similarity — Report Generation ===\n";

// Test the report generation data model and logic that
// AcademicSimilarityReportService::generate and AcademicSimilarityReportGenerator implement.

// ── Report Data Model ──

// Simulate report data structure (same as generated by ReportService)
$submissionData = [
    'submission_id' => 42,
    'submission_title' => 'Research Paper on AI',
    'author_name' => 'John Doe',
    'word_count' => 500,
    'status' => 'processed',
];

$matchData = [
    [
        'id' => 1,
        'source_id' => 10,
        'match_type' => 'exact',
        'match_confidence' => 1.0,
        'matched_word_count' => 50,
        'is_excluded' => false,
    ],
    [
        'id' => 2,
        'source_id' => 11,
        'match_type' => 'near-exact',
        'match_confidence' => 0.85,
        'matched_word_count' => 30,
        'is_excluded' => false,
    ],
    [
        'id' => 3,
        'source_id' => 12,
        'match_type' => 'exact',
        'match_confidence' => 1.0,
        'matched_word_count' => 20,
        'is_excluded' => true,
    ],
];

// Separate active and excluded
$activeMatches = array_values(array_filter($matchData, fn(array $m): bool => !($m['is_excluded'] ?? false)));
$excludedMatches = array_values(array_filter($matchData, fn(array $m): bool => ($m['is_excluded'] ?? false) == 1));

t('2 active matches', count($activeMatches) === 2, 'got: ' . count($activeMatches));
t('1 excluded match', count($excludedMatches) === 1, 'got: ' . count($excludedMatches));

// Calculate scores (same logic as ReportService::generate)
$totalMatchedWords = 0;
foreach ($activeMatches as $match) {
    $totalMatchedWords += (int)($match['matched_word_count'] ?? 0);
}
$totalEligibleWords = (int)($submissionData['word_count'] ?? 0);
$excludedWordDeduction = 0;
foreach ($excludedMatches as $match) {
    $excludedWordDeduction += (int)($match['matched_word_count'] ?? 0);
}

$rawScore = $totalEligibleWords > 0 ? round(($totalMatchedWords / $totalEligibleWords) * 100, 2) : 0.0;
$adjustedScore = $totalEligibleWords > 0 ? round((max(0, $totalMatchedWords) / $totalEligibleWords) * 100, 2) : 0.0;

// 1. Verify scores
t('total matched words is 80', $totalMatchedWords === 80, "got: {$totalMatchedWords}");
t('total eligible words is 500', $totalEligibleWords === 500);
t('excluded word deduction is 20', $excludedWordDeduction === 20, "got: {$excludedWordDeduction}");
t('raw score is 16%', $rawScore === 16.0, "got: {$rawScore}");
t('adjusted score is 16% (no exclusions affect active matches here)', $adjustedScore === 16.0, "got: {$adjustedScore}");

// 2. Report data JSON structure
$reportDataJson = [
    'generated_at' => date('c'),
    'match_summary' => [
        'total_matches' => count($activeMatches),
        'total_excluded' => count($excludedMatches),
        'matched_word_count' => $totalMatchedWords,
        'total_eligible_words' => $totalEligibleWords,
        'raw_score' => $rawScore,
        'adjusted_score' => $adjustedScore,
    ],
    'matches' => array_map(function (array $m): array {
        return [
            'match_id' => (int)$m['id'],
            'source_id' => (int)($m['source_id'] ?? 0),
            'match_type' => $m['match_type'] ?? '',
            'match_confidence' => (float)($m['match_confidence'] ?? 0),
            'matched_word_count' => (int)($m['matched_word_count'] ?? 0),
            'is_excluded' => (bool)($m['is_excluded'] ?? false),
        ];
    }, $matchData),
];

t('report JSON has generated_at', isset($reportDataJson['generated_at']));
t('report JSON has match_summary', isset($reportDataJson['match_summary']));
t('report JSON has matches array', is_array($reportDataJson['matches']));
t('match_summary has raw_score', isset($reportDataJson['match_summary']['raw_score']));
t('match_summary has adjusted_score', isset($reportDataJson['match_summary']['adjusted_score']));
t('match_summary has total_matches', $reportDataJson['match_summary']['total_matches'] === 2);
t('match_summary has total_excluded', $reportDataJson['match_summary']['total_excluded'] === 1);

// 3. Each match has required fields
foreach ($reportDataJson['matches'] as $m) {
    t("match {$m['match_id']} has source_id", isset($m['source_id']));
    t("match {$m['match_id']} has match_type", isset($m['match_type']));
    t("match {$m['match_id']} has match_confidence", isset($m['match_confidence']));
    t("match {$m['match_id']} has is_excluded", isset($m['is_excluded']));
}

// 4. Excluded matches are marked
$excludedInJson = array_values(array_filter($reportDataJson['matches'], fn(array $m): bool => $m['is_excluded']));
t('excluded match is marked in report JSON', count($excludedInJson) === 1);
t('excluded match id is 3', ($excludedInJson[0]['match_id'] ?? 0) === 3);

// 5. Report disclaimer presence (concept)
$disclaimer = 'This similarity report is generated automatically. Scores are based on textual analysis and may include false positives. All matches should be reviewed by a qualified reviewer before final determination.';
t('disclaimer is present and non-empty', strlen($disclaimer) > 0);
t('disclaimer mentions review', str_contains($disclaimer, 'reviewed'));

// 6. Report with zero matches
$emptyMatchData = [];
$emptyTotal = 0;
$emptyScore = $totalEligibleWords > 0 ? round((0 / $totalEligibleWords) * 100, 2) : 0.0;
t('zero matches gives 0% score', $emptyScore === 0.0);

// 7. Report with 100% match
$perfectMatched = $totalEligibleWords;
$perfectScore = round(($perfectMatched / $totalEligibleWords) * 100, 2);
t('100% match gives 100% score', $perfectScore === 100.0);

// 8. Report checksum concept (sha256 of serialized report data)
$checksum = hash('sha256', json_encode($reportDataJson));
t('report checksum is valid sha256', strlen($checksum) === 64);
t('same data produces same checksum', hash('sha256', json_encode($reportDataJson)) === $checksum);

// 9. HTML output contains scores (conceptual test of the template)
$htmlOutput = '<h1>Similarity Report: Research Paper on AI</h1>';
$htmlOutput .= '<div class="score">Raw Score: <span class="raw">16%</span><br>Adjusted Score: <span class="adjusted">16%</span></div>';
$htmlOutput .= '<table><tr><td>1</td><td>10</td><td>exact</td><td>1</td><td>50</td><td>Active</td></tr></table>';

t('HTML contains raw score', str_contains($htmlOutput, '16%'));
t('HTML contains match data', str_contains($htmlOutput, 'exact'));
t('HTML contains source IDs', str_contains($htmlOutput, '10'));
t('HTML contains table structure', str_contains($htmlOutput, '<table>'));

// 10. Report record structure (matches ac_similarity_reports table)
$reportRecord = [
    'submission_id' => 42,
    'report_version' => '1.0.0',
    'match_engine_version' => '1.0.0',
    'raw_score' => 16.0,
    'adjusted_score' => 16.0,
    'total_matches' => 2,
    'total_excluded' => 1,
    'matched_word_count' => 80,
    'total_eligible_words' => 500,
    'exclusion_word_deduction' => 20,
    'report_checksum' => $checksum,
    'report_format' => 'html',
];

t('report record has submission_id', isset($reportRecord['submission_id']));
t('report record has raw_score', $reportRecord['raw_score'] === 16.0);
t('report record has adjusted_score', $reportRecord['adjusted_score'] === 16.0);
t('report record has total_matches', $reportRecord['total_matches'] === 2);
t('report record has report_checksum', isset($reportRecord['report_checksum']));
t('report record has report_format', $reportRecord['report_format'] === 'html');

// Check logs
$appLog = file_get_contents(__DIR__ . '/../storage/logs/app.log');
$errorLog = file_get_contents(__DIR__ . '/../storage/logs/error.log');
t('app.log has no critical entries', !str_contains($appLog, '[critical]'), trim($appLog));
t('error.log is empty', trim($errorLog) === '', trim($errorLog));

echo "\n── Results: {$pass} passed, {$fail} failed ──\n";
exit($fail > 0 ? 1 : 0);
