<?php
/**
 * Builder component CSS ownership guard.
 *
 * The emitted class inventory is derived from the PHP renderer sources. Button
 * variants are expanded from the builder UI's typed source of truth rather than
 * copied into this test.
 *
 * Run: php tests/builder_component_css_test.php
 */
declare(strict_types=1);

$root = dirname(__DIR__);
$rendererPath = $root . '/modules/cms/builder-renderers.php';
$helperPath = $root . '/modules/cms/helpers/50-builder.php';
$typePath = $root . '/modules/cms/builder-ui/src/builder/core/types.ts';
$cssPath = $root . '/public/assets/cms/cms-public.css';
$arkCssPath = $root . '/storage/cms-themes/ark/style.css';
$arkTokensPath = $root . '/storage/cms-themes/ark/tokens.json';

$renderer = (string) file_get_contents($rendererPath);
$helper = (string) file_get_contents($helperPath);
$types = (string) file_get_contents($typePath);
$css = (string) file_get_contents($cssPath);
$arkCss = (string) file_get_contents($arkCssPath);
$arkTokens = json_decode((string)file_get_contents($arkTokensPath), true, 512, JSON_THROW_ON_ERROR);

$pass = 0;
$fail = 0;
function t(string $label, bool $ok, string $detail = ''): void
{
    global $pass, $fail;
    $ok ? $pass++ : $fail++;
    echo '  ' . ($ok ? "\u{2713}" : "\u{2717}") . " {$label}" . (!$ok && $detail !== '' ? " -- {$detail}" : '') . "\n";
}

/** @return list<string> */
function cssClassNames(string $source): array
{
    preg_match_all('/\\.(cms-builder-[A-Za-z0-9_-]+)/', $source, $matches);
    $classes = array_values(array_unique($matches[1] ?? []));
    sort($classes);
    return $classes;
}

/** @return list<string> */
function literalEmittedClasses(string $source): array
{
    preg_match_all('/(?<![A-Za-z0-9_-])(cms-builder-[A-Za-z0-9_-]+)(?![A-Za-z0-9_-])/', $source, $matches);
    $classes = array_values(array_unique(array_filter(
        $matches[1] ?? [],
        // A trailing hyphen is a dynamic prefix, not a complete emitted class.
        static fn(string $class): bool => !str_ends_with($class, '-')
            && !str_starts_with($class, 'cms-builder-scope-')
    )));
    sort($classes);
    return $classes;
}

/** @return list<string> */
function sourceUnionValues(string $source, string $property): array
{
    $pattern = '/' . preg_quote($property, '/') . '\\?\\s*:\\s*((?:\'[^\']+\'\\s*\\|\\s*)+\'[^\']+\')\\s*;/';
    if (preg_match($pattern, $source, $match) !== 1) {
        return [];
    }
    preg_match_all('/\'([^\']+)\'/', $match[1], $values);
    return array_values(array_unique($values[1] ?? []));
}

/** @return array{0: int, 1: int, 2: int} */
function selectorSpecificity(string $selector): array
{
    $ids = preg_match_all('/#[A-Za-z0-9_-]+/', $selector);
    $classes = preg_match_all('/\\.[A-Za-z0-9_-]+|\\[[^]]+]|(?<!:):(?!:)[A-Za-z0-9_-]+/', $selector);
    $withoutNonTypes = preg_replace('/#[A-Za-z0-9_-]+|\\.[A-Za-z0-9_-]+|\\[[^]]+]|::?[A-Za-z0-9_-]+(?:\\([^)]*\\))?/', ' ', $selector);
    $types = preg_match_all('/(?:^|[>+~\\s])([A-Za-z][A-Za-z0-9_-]*|\\*)/', (string)$withoutNonTypes, $matches);
    $types -= count(array_filter($matches[1] ?? [], static fn(string $type): bool => $type === '*'));
    return [$ids, $classes, $types];
}

function beatsThemeContentLink(string $selector): bool
{
    [$ids, $classes, $types] = selectorSpecificity($selector);
    return $ids > 0 || $classes > 1 || ($classes === 1 && $types > 1);
}

/** @return array{0: float, 1: float, 2: float} */
function buttonContrastRgb(string $hex): array
{
    $hex = ltrim($hex, '#');
    if (strlen($hex) !== 6 || !ctype_xdigit($hex)) {
        throw new InvalidArgumentException("Invalid RGB hex color: {$hex}");
    }
    return [
        hexdec(substr($hex, 0, 2)) / 255,
        hexdec(substr($hex, 2, 2)) / 255,
        hexdec(substr($hex, 4, 2)) / 255,
    ];
}

function buttonContrastLuminance(string $hex): float
{
    $channels = array_map(
        static fn(float $channel): float => $channel <= 0.04045
            ? $channel / 12.92
            : (($channel + 0.055) / 1.055) ** 2.4,
        buttonContrastRgb($hex)
    );
    return 0.2126 * $channels[0] + 0.7152 * $channels[1] + 0.0722 * $channels[2];
}

function buttonContrastRatio(string $foreground, string $background): float
{
    $foregroundLuminance = buttonContrastLuminance($foreground);
    $backgroundLuminance = buttonContrastLuminance($background);
    return (max($foregroundLuminance, $backgroundLuminance) + 0.05)
        / (min($foregroundLuminance, $backgroundLuminance) + 0.05);
}

$styled = array_flip(cssClassNames($css));
$literal = literalEmittedClasses($renderer . "\n" . $helper);

// Derive every node class generated by cmsBuilderRenderNode() from the renderer
// registry. Nodes have renderer-owned inline/default styles; any class that is
// also a shared component hook must remain represented in the base stylesheet.
preg_match('/function cmsBuilderWidgetRenderers\\(\\): array.*?\\$map\\s*=\\s*\\[(.*?)\\];/s', $renderer, $registryMatch);
preg_match_all("/^\\s*'([a-z0-9_]+)'\\s*=>\\s*'([A-Za-z0-9_]+)'/m", $registryMatch[1] ?? '', $registryEntries, PREG_SET_ORDER);
$nodeClasses = [];
$nodeRenderFunctions = [];
foreach ($registryEntries as $entry) {
    [$all, $type, $function] = $entry;
    $hasAttrs = preg_match(
        '/function\\s+' . preg_quote($function, '/') . '\\b.*?(?=\\nfunction\\s+|\\z)/s',
        $renderer,
        $functionMatch
    ) === 1 && str_contains($functionMatch[0], 'cmsBuilderAttrString($attrs)');
    if ($hasAttrs) {
        $nodeClasses[] = 'cms-builder-node--' . $type;
        $nodeRenderFunctions[$type] = $function;
    }
}
$nodeClasses = array_values(array_unique($nodeClasses));
sort($nodeClasses);

// The finite button variant vocabulary is owned by ButtonProps in types.ts.
// The PHP renderer emits cms-builder-button--{$variant}, so expand that source
// declaration here. Removing one corresponding CSS rule must name that class.
$buttonVariants = sourceUnionValues($types, 'variant');
$buttonVariantClasses = array_map(static fn(string $variant): string => 'cms-builder-button--' . $variant, $buttonVariants);

$missingVariants = array_values(array_filter(
    $buttonVariantClasses,
    static fn(string $class): bool => preg_match('/\\.' . preg_quote($class, '/') . '\\s*\\{/', $css) !== 1
));

// Literal component hooks that are not represented in the shared stylesheet
// must be self-styled by the renderer. This prevents false positives for such
// intentionally inline widgets as slideshow controls while still inventorying
// their emitted class names from source.
$selfStyled = [];
foreach ($literal as $class) {
    if (isset($styled[$class])) {
        continue;
    }
    $quoted = preg_quote($class, '/');
    $hasInlineElementStyle = preg_match('/class=["\'][^"\']*' . $quoted . '[^"\']*["\'][^>]*style=["\']/s', $renderer) === 1;
    $hasInlineCssRule = preg_match('/\\.' . $quoted . '(?:[.:{[])/', $renderer) === 1;
    if ($hasInlineElementStyle || $hasInlineCssRule) {
        $selfStyled[] = $class;
    }
}
// Dynamic node classes are valid when the node type has a non-empty renderer
// default style. Classes with no default must have a base CSS selector or a
// renderer that applies its computed style array to the emitted element.
preg_match('/function cmsBuilderDefaultStyle\\(string \\$type\\): array.*?static \\$defaults\\s*=\\s*\\[(.*?)\\n\\s*\\];/s', $helper, $defaultsMatch);
preg_match_all("/^\\s*'([a-z0-9_]+)'\\s*=>\\s*\\[(.*?)\\],?$/m", $defaultsMatch[1] ?? '', $defaultMatches, PREG_SET_ORDER);
$inlineDefaultTypes = [];
foreach ($defaultMatches as $match) {
    if (trim($match[2]) !== '') {
        $inlineDefaultTypes[$match[1]] = true;
    }
}
$missingNodes = [];
foreach ($nodeClasses as $class) {
    $type = substr($class, strlen('cms-builder-node--'));
    $function = $nodeRenderFunctions[$type] ?? 'cmsRenderWidget_' . $type;
    $hasComputedStyle = preg_match(
        '/function\\s+' . preg_quote($function, '/') . '\\b.*?(?=\\nfunction\\s+|\\z)/s',
        $renderer,
        $functionMatch
    ) === 1 && (str_contains($functionMatch[0], 'cmsBuilderStyleAttr(')
        || preg_match('/\\bstyle=["\']/', $functionMatch[0]) === 1);
    if (!isset($styled[$class]) && !isset($inlineDefaultTypes[$type]) && !$hasComputedStyle) {
        $missingNodes[] = $class;
    }
}
$missingLiteral = array_values(array_diff($literal, array_keys($styled), $selfStyled, $nodeClasses));

echo "\nBuilder component CSS ownership guard\n\n";
t('renderer class inventory was derived', $literal !== [] && $nodeClasses !== [], count($literal) . ' literal, ' . count($nodeClasses) . ' node classes');
t('button variants were derived from ButtonProps', $buttonVariants !== [], 'none found');
t('every externally-styled button variant exists in cms-public.css', $missingVariants === [], implode(', ', $missingVariants));
t('literal emitted classes are base-styled or explicitly self-styled', $missingLiteral === [], implode(', ', $missingLiteral));
t('dynamic node classes are base-styled or have renderer defaults', $missingNodes === [], implode(', ', $missingNodes));

// Pin the seven relocated button selectors, including the three historical size
// spellings. This is deliberately derived from the relocated selector family;
// it supplements (rather than replaces) the renderer-derived inventory above.
preg_match_all('/\\.cms-builder-button--([a-z]+)\\s*\\{/', $css, $buttonRuleMatches);
$buttonRules = array_values(array_unique($buttonRuleMatches[1] ?? []));
sort($buttonRules);
t('all 7 relocated button modifier rules remain present', count($buttonRules) === 7, implode(', ', $buttonRules));

// Base CSS loads before theme CSS. Every variant declaration that paints a
// background must therefore set its own foreground in a selector stronger than
// a theme's `.theme-content a` rule (specificity 0,1,1).
$cssWithoutComments = (string)preg_replace('~/\\*.*?\\*/~s', '', $css);
preg_match_all('/([^{}]+)\\{([^{}]*)\\}/', $cssWithoutComments, $ruleMatches, PREG_SET_ORDER);
$paintedVariantRules = [];
$unsafePaintedVariantRules = [];
foreach ($ruleMatches as $rule) {
    $selectorList = trim($rule[1]);
    $declarations = $rule[2];
    if (!str_contains($selectorList, '.cms-builder-button--')
        || preg_match('/(?:^|;)\\s*background(?:-color)?\\s*:/', $declarations) !== 1) {
        continue;
    }
    foreach (array_map('trim', explode(',', $selectorList)) as $selector) {
        if (!str_contains($selector, '.cms-builder-button--')) {
            continue;
        }
        $paintedVariantRules[] = $selector;
        $hasColor = preg_match('/(?:^|;)\\s*color\\s*:/', $declarations) === 1;
        if (!$hasColor || !beatsThemeContentLink($selector)) {
            $unsafePaintedVariantRules[] = $selector . ($hasColor ? ' (specificity)' : ' (missing color)');
        }
    }
}
t(
    'painted button variants declare a winning foreground color',
    $paintedVariantRules !== [] && $unsafePaintedVariantRules === [],
    implode(', ', $unsafePaintedVariantRules)
);

t(
    'base primary button has a dedicated AA-safe token default',
    preg_match('/--cms-button-bg,\\s*(#[0-9a-fA-F]{6})/', $css, $baseTokenMatch) === 1,
    'token fallback not found'
);
t(
    'ARK scopes its button fill to the existing primary-dark token',
    preg_match('/--cms-button-bg:\\s*var\\(--color-primary-dark,\\s*(#[0-9a-fA-F]{6})\\)/', $arkCss, $arkTokenMatch) === 1,
    'ARK button token not found'
);

$baseButton = strtolower($baseTokenMatch[1] ?? '#000000');
$arkButton = strtolower((string)($arkTokens['--color-primary-dark'] ?? ($arkTokenMatch[1] ?? '#000000')));
$secondary = '#64748b';
$lightBackground = '#f8fafc';
$contrastScenarios = [
    'base primary' => ['#ffffff', $baseButton],
    'base secondary' => ['#ffffff', $secondary],
    'base outline' => [$baseButton, '#ffffff'],
    'base outline:hover' => ['#ffffff', $baseButton],
    'base ghost' => [$baseButton, '#ffffff'],
    'base ghost:hover' => [$baseButton, $lightBackground],
    'ARK primary' => ['#ffffff', $arkButton],
    'ARK outline' => [$arkButton, '#ffffff'],
    'ARK outline:hover' => ['#ffffff', $arkButton],
    'ARK ghost' => [$arkButton, '#ffffff'],
    'ARK ghost:hover' => [$arkButton, $lightBackground],
];
echo "\nButton variant contrast ratios\n";
foreach ($contrastScenarios as $variant => [$foreground, $background]) {
    $ratio = buttonContrastRatio($foreground, $background);
    $ratioLabel = number_format($ratio, 2) . ':1';
    echo "  {$variant}: {$foreground} on {$background} = {$ratioLabel}\n";
    t("{$variant} clears the WCAG AA 4.5:1 floor", $ratio >= 4.5, $ratioLabel);
}

echo "\n  {$pass} passed, {$fail} failed\n\n";
exit($fail === 0 ? 0 : 1);
