<?php
/**
 * Academic Similarity — route map.
 * All admin routes are under /admin/academic-similarity.
 */

return [
    'GET' => [
        '/admin/academic-similarity'                              => 'academic-similarity:pageDashboard',
        '/api/v1/academic-similarity/public/results'              => 'academic-similarity:apiPublicResults',
        '/api/v1/academic-similarity/public/reports/{submission_id}'          => 'academic-similarity:apiPublicReportSummary',
        '/api/v1/academic-similarity/public/reports/{submission_id}/viewer' => 'academic-similarity:apiPublicReportViewer',
        '/api/v1/academic-similarity/public/reports/{submission_id}/download' => 'academic-similarity:apiPublicReportDownload',
        '/admin/academic-similarity/submissions'                  => 'academic-similarity:pageSubmissions',
        '/admin/academic-similarity/submissions/{id}'             => 'academic-similarity:pageSubmissionDetail',
        '/admin/academic-similarity/sources'                      => 'academic-similarity:pageSources',
        '/admin/academic-similarity/sources/new'                  => 'academic-similarity:pageSourceForm',
        '/admin/academic-similarity/sources/edit'                 => 'academic-similarity:pageSourceForm',
        '/admin/academic-similarity/sources/{id}'                 => 'academic-similarity:pageSourceForm',
        '/admin/academic-similarity/sources/{id}/edit'            => 'academic-similarity:pageSourceForm',
        '/admin/academic-similarity/collections'                  => 'academic-similarity:pageCollections',
        '/admin/academic-similarity/collections/new'              => 'academic-similarity:pageCollectionForm',
        '/admin/academic-similarity/collections/edit'             => 'academic-similarity:pageCollectionForm',
        '/admin/academic-similarity/collections/{id}'             => 'academic-similarity:pageCollectionForm',
        '/admin/academic-similarity/collections/{id}/edit'        => 'academic-similarity:pageCollectionForm',
        '/admin/academic-similarity/reports'                      => 'academic-similarity:pageReports',
        '/admin/academic-similarity/reports/{id}'                 => 'academic-similarity:pageReportDetail',
        '/admin/academic-similarity/reports/{id}/download'        => 'academic-similarity:downloadReport',
        '/admin/academic-similarity/settings'                     => 'academic-similarity:pageSettings',
        '/admin/academic-similarity/settings/processing'          => 'academic-similarity:pageSettings',
        '/admin/academic-similarity/settings/reports'             => 'academic-similarity:pageSettings',
        '/admin/academic-similarity/settings/sources'             => 'academic-similarity:pageSettings',
        '/admin/academic-similarity/settings/semantic'            => 'academic-similarity:pageSettings',
        '/admin/academic-similarity/settings/internet'            => 'academic-similarity:pageSettings',
        '/admin/academic-similarity/settings/cms'                 => 'academic-similarity:pageSettings',
        '/admin/academic-similarity/submissions/new'              => 'academic-similarity:pageSubmissionUpload',
        '/admin/academic-similarity/submissions/{id}/upload'      => 'academic-similarity:pageSubmissionUpload',
        '/api/v1/academic-similarity/semantic/health'            => 'academic-similarity:apiSemanticHealth',
        '/api/v1/academic-similarity/submissions/{id}/internet-check-status' => 'academic-similarity:apiInternetCheckStatus',
        '/api/v1/academic-similarity/submissions/{id}/scholarship-profile' => 'academic-similarity:apiScholarshipProfile',
        '/api/v1/academic-similarity/submissions/{id}/lineage-graph' => 'academic-similarity:apiLineageGraph',
        '/api/v1/academic-similarity/submissions/{id}/lineage-mermaid' => 'academic-similarity:apiLineageMermaid',
    ],
    'POST' => [
        '/admin/academic-similarity/settings'                     => 'academic-similarity:apiSaveSettings',
        '/admin/academic-similarity/settings/processing'          => 'academic-similarity:apiSaveSettings',
        '/admin/academic-similarity/settings/reports'             => 'academic-similarity:apiSaveSettings',
        '/admin/academic-similarity/settings/sources'             => 'academic-similarity:apiSaveSettings',
        '/admin/academic-similarity/settings/semantic'            => 'academic-similarity:apiSaveSettings',
        '/admin/academic-similarity/settings/internet'            => 'academic-similarity:apiSaveSettings',
        '/admin/academic-similarity/settings/cms'                 => 'academic-similarity:apiSaveSettings',
        '/api/v1/academic-similarity/submissions'                 => 'academic-similarity:apiCreateSubmission',
        '/api/v1/academic-similarity/submissions/process'         => 'academic-similarity:apiProcessAllPending',
        '/api/v1/academic-similarity/submissions/{id}/process'    => 'academic-similarity:apiProcessSubmission',
        '/api/v1/academic-similarity/submissions/{id}/internet-check' => 'academic-similarity:apiRunInternetCheck',
        '/api/v1/academic-similarity/submissions/{id}/delete'     => 'academic-similarity:apiDeleteSubmission',
        '/api/v1/academic-similarity/sources'                     => 'academic-similarity:apiCreateSource',
        '/api/v1/academic-similarity/sources/{id}/reindex'        => 'academic-similarity:apiReindexSource',
        '/api/v1/academic-similarity/sources/{id}/delete'         => 'academic-similarity:apiDeleteSource',
        '/api/v1/academic-similarity/collections'                 => 'academic-similarity:apiCreateCollection',
        '/api/v1/academic-similarity/collections/{id}/delete'     => 'academic-similarity:apiDeleteCollection',
        '/api/v1/academic-similarity/reviews/{match_id}/exclude'  => 'academic-similarity:apiExcludeMatch',
        '/api/v1/academic-similarity/reviews/{match_id}/action'   => 'academic-similarity:apiReviewWorkflowAction',
        '/api/v1/academic-similarity/context/analyze'             => 'academic-similarity:apiContextAnalyze',
        '/api/v1/academic-similarity/citation/analyze'            => 'academic-similarity:apiCitationAnalyze',
        '/api/v1/academic-similarity/settings'                    => 'academic-similarity:apiSaveSettings',
        '/api/v1/academic-similarity/public/submit'               => 'academic-similarity:apiPublicSubmit',
        '/admin/academic-similarity/submissions/process-all-pending' => 'academic-similarity:apiProcessAllPending',
    ],
];
