<?php

declare(strict_types=1);

return [
    'GET' => [
        '/bakeshop/login' => 'bakeshop:bakeshopPageLogin',
        '/bakeshop/forgot-password' => 'bakeshop:bakeshopForgotPasswordPage',
        '/bakeshop/reset-password' => 'bakeshop:bakeshopResetPasswordPage',
        '/admin/bakeshop' => 'bakeshop:bakeshopPageSupervisor',
        '/admin/bakeshop/branches' => 'bakeshop:bakeshopPageBranches',
        '/admin/bakeshop/catalog' => 'bakeshop:bakeshopPageCatalog',
        '/admin/bakeshop/ingredients' => 'bakeshop:bakeshopPageIngredients',
        '/admin/bakeshop/deliveries' => 'bakeshop:bakeshopPageDeliveries',
        '/admin/bakeshop/production' => 'bakeshop:bakeshopPageProduction',
        '/admin/bakeshop/usage' => 'bakeshop:bakeshopPageUsage',
        '/admin/bakeshop/history' => 'bakeshop:bakeshopPageHistory',
        '/admin/bakeshop/users' => 'bakeshop:bakeshopPageUsers',
        '/admin/bakeshop/account' => 'bakeshop:bakeshopPageAccount',
        '/admin/bakeshop/settings' => 'bakeshop:bakeshopPageSettings',
        '/bakeshop' => 'bakeshop:bakeshopPageSupervisor',
        '/api/v1/bakeshop/health' => 'bakeshop:bakeshopApiHealth',
        '/api/v1/bakeshop/users' => 'bakeshop:bakeshopApiUsersList',
        '/api/v1/bakeshop/branches' => 'bakeshop:bakeshopApiBranchesIndex',
        '/api/v1/bakeshop/units' => 'bakeshop:bakeshopApiUnitsIndex',
        '/api/v1/bakeshop/products' => 'bakeshop:bakeshopApiProductsIndex',
        '/api/v1/bakeshop/ingredients' => 'bakeshop:bakeshopApiIngredientsIndex',
        '/api/v1/bakeshop/recipes' => 'bakeshop:bakeshopApiRecipesIndex',
        '/api/v1/bakeshop/deliveries' => 'bakeshop:bakeshopApiDeliveriesIndex',
        '/api/v1/bakeshop/production' => 'bakeshop:bakeshopApiProductionIndex',
        '/api/v1/bakeshop/usage' => 'bakeshop:bakeshopApiUsageIndex',
        '/admin/bakeshop/print' => 'bakeshop:bakeshopPagePrintSummary',
        '/bakeshop/print' => 'bakeshop:bakeshopPagePrintSummary',
    ],
    'POST' => [
        '/bakeshop/auth/login' => 'bakeshop:bakeshopAuthLogin',
        '/api/v1/bakeshop/auth/login' => 'bakeshop:bakeshopAuthLogin',
        '/api/v1/bakeshop/auth/forgot-password' => 'bakeshop:bakeshopApiForgotPassword',
        '/api/v1/bakeshop/auth/reset-password' => 'bakeshop:bakeshopApiResetPassword',
        '/bakeshop/logout' => 'bakeshop:bakeshopLogout',
        '/api/v1/bakeshop/account/password' => 'bakeshop:bakeshopApiAccountPasswordUpdate',
        '/api/v1/bakeshop/users' => 'bakeshop:bakeshopApiUserCreate',
        '/api/v1/bakeshop/users/{id}' => 'bakeshop:bakeshopApiUserUpdate',
        '/api/v1/bakeshop/users/{id}/delete' => 'bakeshop:bakeshopApiUserDelete',
        '/api/v1/bakeshop/settings/permissions' => 'bakeshop:bakeshopApiSettingsSavePermissions',
        '/api/v1/bakeshop/settings/display' => 'bakeshop:bakeshopApiSettingsSaveDisplay',
        '/api/v1/bakeshop/settings/logo' => 'bakeshop:bakeshopApiSettingsUploadLogo',
        '/api/v1/bakeshop/units' => 'bakeshop:bakeshopApiUnitsStore',
        '/api/v1/bakeshop/branches' => 'bakeshop:bakeshopApiBranchesStore',
        '/api/v1/bakeshop/branches/{id}/status' => 'bakeshop:bakeshopApiBranchesStatusUpdate',
        '/api/v1/bakeshop/products' => 'bakeshop:bakeshopApiProductsStore',
        '/api/v1/bakeshop/products/{id}/status' => 'bakeshop:bakeshopApiProductsStatusUpdate',
        '/api/v1/bakeshop/products/delete' => 'bakeshop:bakeshopApiProductsDelete',
        '/api/v1/bakeshop/ingredients' => 'bakeshop:bakeshopApiIngredientsStore',
        '/api/v1/bakeshop/ingredients/{id}/status' => 'bakeshop:bakeshopApiIngredientsStatusUpdate',
        '/api/v1/bakeshop/ingredients/delete' => 'bakeshop:bakeshopApiIngredientsDelete',
        '/api/v1/bakeshop/recipes' => 'bakeshop:bakeshopApiRecipesStore',
        '/api/v1/bakeshop/recipes/delete' => 'bakeshop:bakeshopApiRecipesDelete',
        '/api/v1/bakeshop/deliveries' => 'bakeshop:bakeshopApiDeliveriesStore',
        '/api/v1/bakeshop/deliveries/delete' => 'bakeshop:bakeshopApiDeliveriesDelete',
        '/api/v1/bakeshop/production' => 'bakeshop:bakeshopApiProductionStore',
        '/api/v1/bakeshop/production/void' => 'bakeshop:bakeshopApiProductionVoid',
        '/api/v1/bakeshop/production/delete' => 'bakeshop:bakeshopApiProductionDelete',
    ],
];