<?php

declare(strict_types=1);

return [
    'GET' => [
        '/wms/login'             => 'wms:wmsPageLogin',
        '/wms/forgot-password'   => 'wms:wmsForgotPasswordPage',
        '/wms/reset-password'    => 'wms:wmsResetPasswordPage',
        '/wms/logout'            => 'wms:wmsLogout',
        '/wms'                   => 'wms:wmsPageDashboard',
        '/wms/dashboard'         => 'wms:wmsPageDashboard',
        '/wms/inventory'         => 'wms:wmsPageInventory',
        '/wms/suppliers'         => 'wms:wmsPageSuppliers',
        '/wms/stock'             => 'wms:wmsPageStock',
        '/wms/movements'         => 'wms:wmsPageMovements',
        '/wms/deliveries'        => 'wms:wmsPageDeliveries',
        '/wms/orders'            => 'wms:wmsPageOrders',
        '/wms/cycle-counts'      => 'wms:wmsPageCycleCounts',
        '/wms/returns'           => 'wms:wmsPageReturns',
        '/wms/tasks'             => 'wms:wmsPageTasks',
        '/wms/recipes'           => 'wms:wmsPageRecipes',
        '/wms/production'        => 'wms:wmsPageProduction',
        '/wms/receiving'         => 'wms:wmsPageReceiving',
        '/wms/picking'           => 'wms:wmsPagePicking',
        '/wms/users'             => 'wms:wmsPageUsers',
        '/wms/settings'          => 'wms:wmsPageSettings',
        '/wms/scanner'           => 'wms:wmsPageScanner',

        '/api/v1/wms/products'           => 'wms:wmsApiProductsList',
        '/api/v1/wms/products/{id}'       => 'wms:wmsApiProductGet',
        '/api/v1/wms/warehouses'          => 'wms:wmsApiWarehousesList',
        '/api/v1/wms/warehouses/{id}'     => 'wms:wmsApiWarehouseGet',
        '/api/v1/wms/locations'           => 'wms:wmsApiLocationsList',
        '/api/v1/wms/locations/{id}'      => 'wms:wmsApiLocationGet',
        '/api/v1/wms/locations/{id}/children' => 'wms:wmsApiLocationChildren',
        '/api/v1/wms/suppliers'           => 'wms:wmsApiSuppliersList',
        '/api/v1/wms/suppliers/{id}'      => 'wms:wmsApiSupplierGet',
        '/api/v1/wms/batches'             => 'wms:wmsApiBatchesList',
        '/api/v1/wms/batches/{id}'        => 'wms:wmsApiBatchGet',

        '/api/v1/wms/stock'               => 'wms:wmsApiStockQuery',
        '/api/v1/wms/stock/{id}'          => 'wms:wmsApiStockGet',
        '/api/v1/wms/stock/movements'     => 'wms:wmsApiMovementsList',
        '/api/v1/wms/stock/adjustments'   => 'wms:wmsApiAdjustmentsList',

        '/api/v1/wms/deliveries'          => 'wms:wmsApiDeliveriesList',
        '/api/v1/wms/deliveries/{id}'     => 'wms:wmsApiDeliveryGet',
        '/api/v1/wms/orders'              => 'wms:wmsApiOrdersList',
        '/api/v1/wms/orders/{id}'         => 'wms:wmsApiOrderGet',
        '/api/v1/wms/picklists'           => 'wms:wmsApiPicklistsList',
        '/api/v1/wms/picklists/{id}'      => 'wms:wmsApiPicklistGet',
        '/api/v1/wms/putaway-rules'       => 'wms:wmsApiPutawayRulesList',

        '/api/v1/wms/cycle-counts'        => 'wms:wmsApiCycleCountsList',
        '/api/v1/wms/cycle-counts/{id}'   => 'wms:wmsApiCycleCountGet',
        '/api/v1/wms/returns'             => 'wms:wmsApiReturnsList',
        '/api/v1/wms/returns/{id}'        => 'wms:wmsApiReturnGet',
        '/api/v1/wms/tasks'               => 'wms:wmsApiTasksList',
        '/api/v1/wms/tasks/{id}'          => 'wms:wmsApiTaskGet',
        '/api/v1/wms/recipes'             => 'wms:wmsApiRecipesList',
        '/api/v1/wms/recipes/{id}'        => 'wms:wmsApiRecipeGet',
        '/api/v1/wms/production-orders'   => 'wms:wmsApiProductionOrdersList',
        '/api/v1/wms/production-orders/{id}' => 'wms:wmsApiProductionOrderGet',
        '/api/v1/wms/webhooks'            => 'wms:wmsApiWebhooksList',
    ],
    'POST' => [
        '/wms/auth/login'              => 'wms:wmsAuthLogin',
        '/api/v1/wms/auth/login'       => 'wms:wmsAuthLogin',
        '/api/v1/wms/auth/forgot-password' => 'wms:wmsApiForgotPassword',
        '/api/v1/wms/auth/reset-password'  => 'wms:wmsApiResetPassword',

        '/api/v1/wms/products'              => 'wms:wmsApiProductCreate',
        '/api/v1/wms/products/{id}'          => 'wms:wmsApiProductUpdate',
        '/api/v1/wms/products/{id}/delete'   => 'wms:wmsApiProductDelete',
        '/api/v1/wms/warehouses'             => 'wms:wmsApiWarehouseCreate',
        '/api/v1/wms/warehouses/{id}'        => 'wms:wmsApiWarehouseUpdate',
        '/api/v1/wms/locations'              => 'wms:wmsApiLocationCreate',
        '/api/v1/wms/locations/{id}'         => 'wms:wmsApiLocationUpdate',
        '/api/v1/wms/suppliers'              => 'wms:wmsApiSupplierCreate',
        '/api/v1/wms/suppliers/{id}'         => 'wms:wmsApiSupplierUpdate',
        '/api/v1/wms/suppliers/{id}/delete'  => 'wms:wmsApiSupplierDelete',
        '/api/v1/wms/batches'                => 'wms:wmsApiBatchCreate',
        '/api/v1/wms/batches/{id}'          => 'wms:wmsApiBatchUpdate',

        '/api/v1/wms/stock/receive'         => 'wms:wmsApiStockReceive',
        '/api/v1/wms/stock/transfer'        => 'wms:wmsApiStockTransfer',
        '/api/v1/wms/stock/adjust'          => 'wms:wmsApiStockAdjust',
        '/api/v1/wms/stock/scrap'           => 'wms:wmsApiStockScrap',
        '/api/v1/wms/stock/adjustments/{id}' => 'wms:wmsApiAdjustmentReview',

        '/api/v1/wms/deliveries'              => 'wms:wmsApiDeliveryCreate',
        '/api/v1/wms/deliveries/{id}/receive'  => 'wms:wmsApiDeliveryReceive',
        '/api/v1/wms/deliveries/{id}/cancel'   => 'wms:wmsApiDeliveryCancel',
        '/api/v1/wms/orders'                   => 'wms:wmsApiOrderCreate',
        '/api/v1/wms/orders/{id}/cancel'       => 'wms:wmsApiOrderCancel',
        '/api/v1/wms/picklists'                => 'wms:wmsApiPicklistCreate',
        '/api/v1/wms/picklists/{id}/assign'    => 'wms:wmsApiPicklistAssign',
        '/api/v1/wms/picklists/{id}/items/{item_id}/pick' => 'wms:wmsApiPicklistPickItem',
        '/api/v1/wms/shipments'                => 'wms:wmsApiShipmentCreate',
        '/api/v1/wms/putaway-rules'            => 'wms:wmsApiPutawayRuleCreate',
        '/api/v1/wms/putaway-rules/{id}/delete' => 'wms:wmsApiPutawayRuleDelete',

        '/api/v1/wms/cycle-counts'               => 'wms:wmsApiCycleCountCreate',
        '/api/v1/wms/cycle-counts/{id}/items/{item_id}/record' => 'wms:wmsApiCycleCountRecord',
        '/api/v1/wms/cycle-counts/{id}/complete'  => 'wms:wmsApiCycleCountComplete',
        '/api/v1/wms/returns'                     => 'wms:wmsApiReturnCreate',
        '/api/v1/wms/returns/{id}/process'        => 'wms:wmsApiReturnProcess',
        '/api/v1/wms/tasks'                       => 'wms:wmsApiTaskCreate',
        '/api/v1/wms/tasks/{id}'                  => 'wms:wmsApiTaskUpdate',
        '/api/v1/wms/tasks/{id}/complete'         => 'wms:wmsApiTaskComplete',
        '/api/v1/wms/recipes'                     => 'wms:wmsApiRecipeCreate',
        '/api/v1/wms/production-orders'           => 'wms:wmsApiProductionOrderCreate',
        '/api/v1/wms/production-orders/{id}/complete' => 'wms:wmsApiProductionOrderComplete',
        '/api/v1/wms/webhooks'                    => 'wms:wmsApiWebhookCreate',
        '/api/v1/wms/webhooks/{id}/toggle'        => 'wms:wmsApiWebhookToggle',
        '/api/v1/wms/webhooks/{id}/delete'        => 'wms:wmsApiWebhookDelete',

        '/api/v1/wms/users/{id}/toggle'           => 'wms:wmsApiUserToggle',
        '/api/v1/wms/auth/admin-reset-password'   => 'wms:wmsApiAdminResetPassword',
    ],
];
