<?php

declare(strict_types=1);

function palPagePurchaseList(): void { $u = palCurrentUser(); $s = new palPurchaseService(palDb(), (int)($u['tenant_id']??0), (int)$u['id']); $r = $s->list($_GET); $t = __DIR__.'/../templates/project-audit-ledger/shell.disyl'; palRender($t, ['current_user'=>$u, 'page_title'=>'Purchases', 'page_content'=>'purchases-list', 'purchases'=>$r, 'show_items'=>true]); }
function palPagePurchaseForm(array $rp = []): void { $u = palCurrentUser(); $id=(int)($rp['id']??$_GET['id']??0); $p=null; if($id>0){$s=new palPurchaseService(palDb(), (int)($u['tenant_id']??0), (int)$u['id']); $p=$s->get($id);} $db=palDb(); $sup=$db->prepare("SELECT id,name FROM pal_suppliers WHERE tenant_id=:tid AND is_active=1 ORDER BY name"); $sup->execute([':tid'=>$u['tenant_id']??0]); $mat=$db->prepare("SELECT id,name FROM pal_materials WHERE tenant_id=:tid AND is_active=1 ORDER BY name"); $mat->execute([':tid'=>$u['tenant_id']??0]); $t=__DIR__.'/../templates/project-audit-ledger/shell.disyl'; palRender($t, ['current_user'=>$u, 'page_title'=>$p?'Edit Purchase':'Create Purchase', 'page_content'=>'purchase-form', 'purchase'=>$p, 'is_edit'=>$p!==null, 'suppliers'=>$sup->fetchAll(PDO::FETCH_ASSOC), 'materials'=>$mat->fetchAll(PDO::FETCH_ASSOC)]); }
function palPagePurchaseDetail(array $rp=[]): void { $u=palCurrentUser(); $id=(int)($rp['id']??$_GET['id']??0); $s=new palPurchaseService(palDb(), (int)($u['tenant_id']??0), (int)$u['id']); $p=$s->get($id); if(!$p){palJsonError('Purchase not found.',404);return;} $t=__DIR__.'/../templates/project-audit-ledger/shell.disyl'; palRender($t, ['current_user'=>$u, 'page_title'=>'Purchase #'.$p['purchase_number'], 'page_content'=>'purchase-detail', 'purchase'=>$p]); }
function palApiPurchaseStore(): void { palResponseGuard(function(){ $u=palCurrentUser(); palEnforceCsrf(); $s=new palPurchaseService(palDb(), (int)($u['tenant_id']??0), (int)$u['id']); $id=$s->create($_POST); palAudit('pal.purchase.created', (int)$u['id'], 'pal_purchases', (string)$id, null, []); header('Content-Type: application/json'); echo json_encode(['ok'=>true, 'id'=>$id]); }); }
function palApiPurchaseUpdate(array $rp=[]): void { palResponseGuard(function() use ($rp): void { $u=palCurrentUser(); palEnforceCsrf(); $id=(int)($rp['id']??$_GET['id']??$_POST['id']??0); if($id<=0){palJsonError('Invalid ID.');return;} $s=new palPurchaseService(palDb(), (int)($u['tenant_id']??0), (int)$u['id']); $s->update($id, $_POST); palAudit('pal.purchase.updated', (int)$u['id'], 'pal_purchases', (string)$id, null, []); header('Content-Type: application/json'); echo json_encode(['ok'=>true]); }); }
function palApiPurchaseSubmit(array $rp = []): void { palResponseGuard(function() use ($rp): void { $u=palCurrentUser(); palEnforceCsrf(); $id=(int)($rp['id']??$_GET['id']??$_POST['id']??0); $s=new palPurchaseService(palDb(), (int)($u['tenant_id']??0), (int)$u['id']); $aid=$s->submit($id); header('Content-Type: application/json'); echo json_encode(['ok'=>true, 'approval_id'=>$aid]); }); }
