<?php

declare(strict_types=1);

function palPageInventoryList(): void { $u=palCurrentUser(); $s=new palInventoryService(palDb(), (int)($u['tenant_id']??0)); $r=$s->listMaterials($_GET); $db=palDb(); $tid=(int)($u['tenant_id']??0); $cats=$db->prepare("SELECT id,name FROM pal_material_categories WHERE tenant_id=:tid AND is_active=1 ORDER BY name"); $cats->execute([':tid'=>$tid]); $units=$db->prepare("SELECT id,name,abbreviation FROM pal_units ORDER BY name"); $units->execute(); $t=__DIR__.'/../templates/project-audit-ledger/shell.disyl'; palRender($t, ['current_user'=>$u, 'page_title'=>'Inventory', 'page_content'=>'inventory-list', 'materials'=>$r, 'categories'=>$cats->fetchAll(PDO::FETCH_ASSOC), 'units'=>$units->fetchAll(PDO::FETCH_ASSOC)]); }
function palPageInventoryDetail(array $rp = []): void { $u=palCurrentUser(); $id=(int)($rp['id']??$_GET['id']??0); $s=new palInventoryService(palDb(), (int)($u['tenant_id']??0)); $m=$s->getMaterial($id); if(!$m){palJsonError('Material not found.',404);return;} $db=palDb(); $tid=(int)($u['tenant_id']??0); $cats=$db->prepare("SELECT id,name FROM pal_material_categories WHERE tenant_id=:tid AND is_active=1 ORDER BY name"); $cats->execute([':tid'=>$tid]); $units=$db->prepare("SELECT id,name,abbreviation FROM pal_units ORDER BY name"); $units->execute(); $sups=$db->prepare("SELECT id,name FROM pal_suppliers WHERE tenant_id=:tid AND is_active=1 ORDER BY name"); $sups->execute([':tid'=>$tid]); $t=__DIR__.'/../templates/project-audit-ledger/shell.disyl'; palRender($t, ['current_user'=>$u, 'page_title'=>$m['name'], 'page_content'=>'inventory-detail', 'material'=>$m, 'categories'=>$cats->fetchAll(PDO::FETCH_ASSOC), 'units'=>$units->fetchAll(PDO::FETCH_ASSOC), 'suppliers'=>$sups->fetchAll(PDO::FETCH_ASSOC)]); }
function palPageMovementList(): void { $u=palCurrentUser(); $db=palDb(); $mv=$db->prepare("SELECT im.*, m.name AS material_name FROM pal_inventory_movements im LEFT JOIN pal_materials m ON im.material_id=m.id WHERE im.tenant_id=:tid ORDER BY im.created_at DESC LIMIT 100"); $mv->execute([':tid'=>$u['tenant_id']??0]); $t=__DIR__.'/../templates/project-audit-ledger/shell.disyl'; palRender($t, ['current_user'=>$u, 'page_title'=>'Stock Movements', 'page_content'=>'movements-list', 'movements'=>$mv->fetchAll(PDO::FETCH_ASSOC)]); }
function palApiMaterialStore(): void { palResponseGuard(function(){ $u=palCurrentUser(); palEnforceCsrf(); $s=new palInventoryService(palDb(), (int)($u['tenant_id']??0)); $_POST['created_by']=$u['id']; $id=$s->createMaterial($_POST); palAudit('pal.material.created', (int)$u['id'], 'pal_materials', (string)$id, null, []); header('Content-Type: application/json'); echo json_encode(['ok'=>true, 'id'=>$id]); }); }
function palApiInventoryAdjust(): void { palResponseGuard(function(){ $u=palCurrentUser(['admin','supervisor']); palEnforceCsrf(); $db=palDb(); $mid=(int)($_POST['material_id']??0); $qty=(float)($_POST['quantity']??0); $reason=$_POST['reason']??''; if($qty===0.0||$reason===''){palJsonError('Quantity and reason are required.');return;} $type=$qty>0?'adjustment_up':'adjustment_down'; $mv=$db->prepare("INSERT INTO pal_inventory_movements (tenant_id, material_id, movement_type, quantity, unit_cost, total_cost, description, created_by) VALUES (:t,:m,:mt,:q,0,0,:desc,:cb)"); $mv->execute([':t'=>$u['tenant_id']??0,':m'=>$mid,':mt'=>$type,':q'=>$qty,':desc'=>$reason,':cb'=>(int)$u['id']]); $bal=$db->prepare("INSERT INTO pal_inventory_balances (tenant_id, material_id, quantity) VALUES (:t,:m,:q) ON DUPLICATE KEY UPDATE quantity=quantity+:q2"); $bal->execute([':t'=>$u['tenant_id']??0,':m'=>$mid,':q'=>$qty,':q2'=>$qty]); palAudit('pal.inventory.adjusted', (int)$u['id'], 'pal_materials', (string)$mid, null, ['qty'=>$qty,'reason'=>$reason]); header('Content-Type: application/json'); echo json_encode(['ok'=>true]); }); }
