<?php

declare(strict_types=1);

require_once __DIR__ . '/../services/MaterialIssuanceService.php';
require_once __DIR__ . '/../services/MaterialReturnService.php';

function palPageIssuanceList(): void { $u=palCurrentUser(); $t=__DIR__.'/../templates/project-audit-ledger/shell.disyl'; palRender($t, ['current_user'=>$u, 'page_title'=>'Material Issuance', 'page_content'=>'issuance-list']); }
function palPageIssuanceForm(array $rp = []): void { $u=palCurrentUser(); $id=(int)($rp['id']??$_GET['id']??0); $issuance=null; if($id>0){$s=new palMaterialIssuanceService(palDb(), (int)($u['tenant_id']??0), (int)$u['id']); $issuance=$s->get($id);} $db=palDb(); $proj=$db->prepare("SELECT id,title FROM pal_projects WHERE tenant_id=:tid AND status IN('approved','started','ongoing') ORDER BY title"); $proj->execute([':tid'=>$u['tenant_id']??0]); $mat=$db->prepare("SELECT m.id,m.name,COALESCE(b.quantity,0) AS stock FROM pal_materials m LEFT JOIN pal_inventory_balances b ON m.id=b.material_id WHERE m.tenant_id=:tid AND m.is_active=1 ORDER BY m.name"); $mat->execute([':tid'=>$u['tenant_id']??0]); $t=__DIR__.'/../templates/project-audit-ledger/shell.disyl'; palRender($t, ['current_user'=>$u, 'page_title'=>$issuance?'Edit Issuance':'Create Issuance', 'page_content'=>'issuance-form', 'issuance'=>$issuance, 'is_edit'=>$issuance!==null, 'projects'=>$proj->fetchAll(PDO::FETCH_ASSOC), 'materials'=>$mat->fetchAll(PDO::FETCH_ASSOC)]); }
function palPageIssuanceDetail(array $rp=[]): void { $u=palCurrentUser(); $id=(int)($rp['id']??$_GET['id']??0); $s=new palMaterialIssuanceService(palDb(), (int)($u['tenant_id']??0), (int)$u['id']); $iss=$s->get($id); if(!$iss){palJsonError('Issuance not found.',404);return;} $t=__DIR__.'/../templates/project-audit-ledger/shell.disyl'; palRender($t, ['current_user'=>$u, 'page_title'=>'Issuance #'.$iss['issuance_number'], 'page_content'=>'issuance-detail', 'issuance'=>$iss]); }
function palPageMaterialReturnForm(): void { $u=palCurrentUser(); $db=palDb(); $tid=(int)($u['tenant_id']??0); $proj=$db->prepare("SELECT id,title FROM pal_projects WHERE tenant_id=:tid AND status IN('approved','started','ongoing','completed') ORDER BY title"); $proj->execute([':tid'=>$tid]); $mat=$db->prepare("SELECT id,name FROM pal_materials WHERE tenant_id=:tid AND is_active=1 ORDER BY name"); $mat->execute([':tid'=>$tid]); $iss=$db->prepare("SELECT id,issuance_number FROM pal_material_issuances WHERE tenant_id=:tid AND status IN('approved','fully_issued') ORDER BY created_at DESC LIMIT 50"); $iss->execute([':tid'=>$tid]); $t=__DIR__.'/../templates/project-audit-ledger/shell.disyl'; palRender($t, ['current_user'=>$u, 'page_title'=>'Material Return', 'page_content'=>'material-return-form', 'projects'=>$proj->fetchAll(PDO::FETCH_ASSOC), 'materials'=>$mat->fetchAll(PDO::FETCH_ASSOC), 'issuances'=>$iss->fetchAll(PDO::FETCH_ASSOC)]); }
function palPageMaterialReturnList(): void { $u=palCurrentUser(); $t=__DIR__.'/../templates/project-audit-ledger/shell.disyl'; palRender($t, ['current_user'=>$u, 'page_title'=>'Material Returns', 'page_content'=>'material-return-list']); }
function palApiIssuanceStore(): void { palResponseGuard(function(){ $u=palCurrentUser(); palEnforceCsrf(); $items=[]; if(isset($_POST['material_id'])&&is_array($_POST['material_id'])){foreach($_POST['material_id'] as $i=>$mid){$items[]=['material_id'=>(int)$mid,'quantity'=>(float)($_POST['quantity'][$i]??0)];}} $_POST['items']=$items; $s=new palMaterialIssuanceService(palDb(), (int)($u['tenant_id']??0), (int)$u['id']); $id=$s->create($_POST); palAudit('pal.issuance.created', (int)$u['id'], 'pal_material_issuances', (string)$id, null, []); header('Content-Type: application/json'); echo json_encode(['ok'=>true, 'id'=>$id]); }); }
function palApiIssuanceSubmit(array $rp = []): void { palResponseGuard(function() use ($rp): void { $u=palCurrentUser(); palEnforceCsrf(); $id=(int)($rp['id']??$_GET['id']??$_POST['id']??0); $s=new palMaterialIssuanceService(palDb(), (int)($u['tenant_id']??0), (int)$u['id']); $aid=$s->submit($id); header('Content-Type: application/json'); echo json_encode(['ok'=>true, 'approval_id'=>$aid]); }); }
function palApiIssuanceUpdate(array $rp = []): void { palResponseGuard(function() use ($rp): void { $u=palCurrentUser(); palEnforceCsrf(); $id=(int)($rp['id']??$_GET['id']??$_POST['id']??0); if($id<=0){palJsonError('Invalid ID.');return;} $s=new palMaterialIssuanceService(palDb(), (int)($u['tenant_id']??0), (int)$u['id']); $s->update($id, $_POST); palAudit('pal.issuance.updated', (int)$u['id'], 'pal_material_issuances', (string)$id, null, []); header('Content-Type: application/json'); echo json_encode(['ok'=>true]); }); }
function palApiMaterialReturn(): void { palResponseGuard(function(){ $u=palCurrentUser(); palEnforceCsrf(); $s=new palMaterialReturnService(palDb(), (int)($u['tenant_id']??0), (int)$u['id']); $id=$s->create($_POST); palAudit('pal.inventory.material_returned', (int)$u['id'], 'pal_material_returns', (string)$id, null, []); header('Content-Type: application/json'); echo json_encode(['ok'=>true, 'id'=>$id]); }); }
