<?php

declare(strict_types=1);

function palPageSalesList(): void { $u=palCurrentUser(); $s=new palSalesService(palDb(), (int)($u['tenant_id']??0), (int)$u['id']); $r=$s->list($_GET); $t=__DIR__.'/../templates/project-audit-ledger/shell.disyl'; palRender($t, ['current_user'=>$u, 'page_title'=>'Sales', 'page_content'=>'sales-list', 'sales'=>$r]); }
function palPageSalesDetail(array $rp=[]): void { $u=palCurrentUser(); $id=(int)($rp['id']??$_GET['id']??0); $s=new palSalesService(palDb(), (int)($u['tenant_id']??0), (int)$u['id']); $sale=$s->get($id); if(!$sale){palJsonError('Sale not found.',404);return;} $t=__DIR__.'/../templates/project-audit-ledger/shell.disyl'; palRender($t, ['current_user'=>$u, 'page_title'=>'Invoice #'.$sale['sales_number'], 'page_content'=>'sales-detail', 'sale'=>$sale]); }
function palPageSalesForm(array $rp = []): void { $u=palCurrentUser(); $id=(int)($rp['id']??$_GET['id']??0); $sale=null; if($id>0){$s=new palSalesService(palDb(), (int)($u['tenant_id']??0), (int)$u['id']); $sale=$s->get($id);} $db=palDb(); $proj=$db->prepare("SELECT id,title FROM pal_projects WHERE tenant_id=:tid AND status IN('approved','in_progress','completed') ORDER BY title"); $proj->execute([':tid'=>$u['tenant_id']??0]); $clients=$db->prepare("SELECT id,name FROM pal_clients WHERE tenant_id=:tid AND is_active=1 ORDER BY name"); $clients->execute([':tid'=>$u['tenant_id']??0]); $t=__DIR__.'/../templates/project-audit-ledger/shell.disyl'; palRender($t, ['current_user'=>$u, 'page_title'=>$sale?'Edit Sale':'Create Sale', 'page_content'=>'sales-form', 'sale'=>$sale, 'is_edit'=>$sale!==null, 'projects'=>$proj->fetchAll(PDO::FETCH_ASSOC), 'clients'=>$clients->fetchAll(PDO::FETCH_ASSOC)]); }
function palPageCollectionList(): void { $u=palCurrentUser(); $db=palDb(); $tid=(int)($u['tenant_id']??0); $col=$db->prepare("SELECT c.*, s.sales_number, s.net_amount AS sale_net, p.title AS project_title, cl.name AS client_name FROM pal_collections c LEFT JOIN pal_sales s ON c.sales_id=s.id LEFT JOIN pal_projects p ON c.project_id=p.id LEFT JOIN pal_clients cl ON c.client_id=cl.id WHERE c.tenant_id=:tid ORDER BY c.created_at DESC LIMIT 50"); $col->execute([':tid'=>$tid]); $t=__DIR__.'/../templates/project-audit-ledger/shell.disyl'; palRender($t, ['current_user'=>$u, 'page_title'=>'Collections', 'page_content'=>'collections-list', 'collections'=>$col->fetchAll(PDO::FETCH_ASSOC)]); }
function palPageCollectionDetail(array $rp=[]): void { $u=palCurrentUser(); $id=(int)($rp['id']??$_GET['id']??0); $db=palDb(); $tid=(int)($u['tenant_id']??0); $stmt=$db->prepare("SELECT c.*, s.sales_number, s.net_amount AS sale_net, s.status AS sale_status, p.title AS project_title, cl.name AS client_name FROM pal_collections c LEFT JOIN pal_sales s ON c.sales_id=s.id LEFT JOIN pal_projects p ON c.project_id=p.id LEFT JOIN pal_clients cl ON c.client_id=cl.id WHERE c.id=:id AND c.tenant_id=:tid"); $stmt->execute([':id'=>$id,':tid'=>$tid]); $col=$stmt->fetch(PDO::FETCH_ASSOC); if(!$col){palJsonError('Collection not found.',404);return;} $t=__DIR__.'/../templates/project-audit-ledger/shell.disyl'; palRender($t, ['current_user'=>$u, 'page_title'=>'Collection #'.$id, 'page_content'=>'collections-detail', 'collection'=>$col]); }
function palPageCollectionForm(): void { $u=palCurrentUser(); $db=palDb(); $tid=(int)($u['tenant_id']??0); $proj=$db->prepare("SELECT id,title FROM pal_projects WHERE tenant_id=:tid AND status IN('approved','in_progress','completed') ORDER BY title"); $proj->execute([':tid'=>$tid]); $sales=$db->prepare("SELECT s.id, s.sales_number, s.net_amount, s.gross_amount, s.project_id, p.title AS project_title, cl.name AS client_name, COALESCE((SELECT SUM(amount) FROM pal_collections WHERE sales_id=s.id AND status='approved'),0) AS collected_amt FROM pal_sales s LEFT JOIN pal_projects p ON s.project_id=p.id LEFT JOIN pal_clients cl ON s.client_id=cl.id WHERE s.tenant_id=:tid AND s.status IN('issued','partially_paid') ORDER BY p.title, s.created_at DESC"); $sales->execute([':tid'=>$tid]); $t=__DIR__.'/../templates/project-audit-ledger/shell.disyl'; palRender($t, ['current_user'=>$u, 'page_title'=>'Record Collection', 'page_content'=>'collection-form', 'projects'=>$proj->fetchAll(PDO::FETCH_ASSOC), 'sales'=>$sales->fetchAll(PDO::FETCH_ASSOC)]); }
function palApiSalesStore(): void { palResponseGuard(function(){ $u=palCurrentUser(); palEnforceCsrf(); $s=new palSalesService(palDb(), (int)($u['tenant_id']??0), (int)$u['id']); $id=$s->create($_POST); palAudit('pal.sale.created', (int)$u['id'], 'pal_sales', (string)$id, null, []); header('Content-Type: application/json'); echo json_encode(['ok'=>true, 'id'=>$id]); }); }
function palApiSalesUpdate(array $rp = []): void { palResponseGuard(function() use ($rp): void { $u=palCurrentUser(); palEnforceCsrf(); $id=(int)($rp['id']??$_GET['id']??$_POST['id']??0); if($id<=0){palJsonError('Invalid ID.');return;} $s=new palSalesService(palDb(), (int)($u['tenant_id']??0), (int)$u['id']); $s->update($id, $_POST); palAudit('pal.sale.updated', (int)$u['id'], 'pal_sales', (string)$id, null, []); header('Content-Type: application/json'); echo json_encode(['ok'=>true]); }); }
function palApiCollectionStore(): void { palResponseGuard(function(){ $u=palCurrentUser(); palEnforceCsrf(); $s=new palSalesService(palDb(), (int)($u['tenant_id']??0), (int)$u['id']); $id=$s->recordCollection($_POST); palAudit('pal.collection.recorded', (int)$u['id'], 'pal_collections', (string)$id, null, []); header('Content-Type: application/json'); echo json_encode(['ok'=>true, 'id'=>$id]); }); }
