CREATE TABLE IF NOT EXISTS ehr_prescriptions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    prescription_uuid VARCHAR(64) NOT NULL,
    patient_id BIGINT UNSIGNED NOT NULL,
    encounter_id BIGINT UNSIGNED NOT NULL,
    medication_code VARCHAR(64) DEFAULT NULL,
    code_system VARCHAR(64) DEFAULT NULL,
    medication_text VARCHAR(255) NOT NULL,
    prescriber_user_id BIGINT UNSIGNED DEFAULT NULL,
    dose_text VARCHAR(255) DEFAULT NULL,
    route VARCHAR(64) DEFAULT NULL,
    frequency VARCHAR(128) DEFAULT NULL,
    duration_text VARCHAR(128) DEFAULT NULL,
    quantity VARCHAR(64) DEFAULT NULL,
    refills INT UNSIGNED DEFAULT NULL,
    indication VARCHAR(255) DEFAULT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'issued',
    issued_at DATETIME NOT NULL,
    canceled_at DATETIME DEFAULT NULL,
    cancellation_reason VARCHAR(255) DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_ehr_prescriptions_uuid (prescription_uuid),
    KEY idx_ehr_prescriptions_patient (patient_id),
    KEY idx_ehr_prescriptions_encounter (encounter_id),
    KEY idx_ehr_prescriptions_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;