/**
 * Browser tests for Guidance Monitoring Navigation
 *
 * Auto-generated by generate-module-test.php
 *
 * Run: npx playwright test tests/browser/modules/guidance/
 */

// @ts-check
const { test, expect } = require('../../../GuidanceAdapter');

const NAV_URLS = ['/admin/guidance'];

test.describe('guidance:navigation', () => {

    test('all nav items render in sidebar', async ({ page, shell }) => {
        for (const url of NAV_URLS) {
            const link = page.locator('a[href="' + url + '"]');
            await expect(link.first()).toBeVisible();
        }
    });

    test('each nav item navigates to correct page', async ({ page, shell }) => {
        for (const url of NAV_URLS) {
            await page.goto(url);
            await page.waitForSelector('[data-wb-component="app-shell"]', { timeout: 10000 });
            await expect(page).toHaveURL(new RegExp(url.replace(/\//g, '\\/')));
        }
    });

    test('known coverage gaps', async ({ integrity }) => {
        integrity.gap('Form validation on create/edit pages');
        integrity.gap('List views show entity data');
        integrity.gap('Detail views for each entity type');
        integrity.gap('Cross-page navigation preserves state');
        integrity.gap('Mobile bottom-nav for key pages');
    });
});