<?php

declare(strict_types=1);

return [
    'GET' => [
        '/attendance-wage/login'           => 'attendance-wage:attendancePageLogin',
        '/attendance-wage/forgot-password' => 'attendance-wage:attendancePageForgotPassword',
        '/attendance-wage/reset-password'  => 'attendance-wage:attendancePageResetPassword',
        '/admin/attendance'              => 'attendance-wage:attendancePageClock',
        '/admin/attendance/history'      => 'attendance-wage:attendancePageHistory',
        '/admin/attendance/report'       => 'attendance-wage:attendancePageReport',
        '/admin/wage'                    => 'attendance-wage:wagePageDashboard',
        '/admin/wage/employees'          => 'attendance-wage:wagePageEmployees',
        '/admin/wage/employees/create'   => 'attendance-wage:wagePageEmployeeForm',
        '/admin/wage/employees/{id}'     => 'attendance-wage:wagePageEmployeeForm',
        '/admin/wage/periods'            => 'attendance-wage:wagePagePeriods',
        '/admin/wage/periods/create'     => 'attendance-wage:wagePagePeriodForm',
        '/admin/wage/computations'       => 'attendance-wage:wagePageComputations',
        '/admin/wage/adjustments'        => 'attendance-wage:wagePageAdjustments',
        '/admin/wage/adjustments/create' => 'attendance-wage:wagePageAdjustmentForm',
        '/admin/wage/deductions'         => 'attendance-wage:wagePageDeductions',
        '/admin/wage/deductions/create'  => 'attendance-wage:wagePageDeductionForm',
        '/admin/wage/cash-advances'      => 'attendance-wage:wagePageCashAdvances',
        '/admin/wage/holidays'           => 'attendance-wage:wagePageHolidays',
        '/admin/wage/schedules'          => 'attendance-wage:wagePageSchedules',
        '/admin/wage/reports'            => 'attendance-wage:wagePageReports',
        '/admin/wage/reports/{periodId}' => 'attendance-wage:wagePageReportDetail',
        '/admin/wage/benefits-calculator'=> 'attendance-wage:wagePageBenefitsCalc',
        '/admin/wage/migration'          => 'attendance-wage:wagePageMigrationWizard',
        '/api/v1/attendance/photo/{file}' => 'attendance-wage:attendanceApiPhoto',
        '/api/v1/attendance/records'      => 'attendance-wage:attendanceApiRecords',
        '/api/v1/wage/employees'          => 'attendance-wage:wageApiEmployeesList',
        '/api/v1/wage/employees/{id}'     => 'attendance-wage:wageApiEmployeeGet',
        '/api/v1/wage/periods'            => 'attendance-wage:wageApiPeriodsList',
        '/api/v1/wage/periods/{id}'       => 'attendance-wage:wageApiPeriodGet',
        '/api/v1/wage/computations'       => 'attendance-wage:wageApiComputationsList',
        '/api/v1/wage/computations/{id}'  => 'attendance-wage:wageApiComputationGet',
        '/api/v1/wage/adjustments'        => 'attendance-wage:wageApiAdjustmentsList',
        '/api/v1/wage/deductions'         => 'attendance-wage:wageApiDeductionsList',
        '/api/v1/wage/cash-advances'      => 'attendance-wage:wageApiCashAdvancesList',
        '/api/v1/wage/holidays'           => 'attendance-wage:wageApiHolidaysList',
        '/api/v1/wage/payslip/{computationId}' => 'attendance-wage:wageApiPayslip',
    ],
    'POST' => [
        '/attendance-wage/auth/login'                    => 'attendance-wage:attendanceAuthLogin',
        '/api/v1/attendance-wage/auth/forgot-password'   => 'attendance-wage:attendanceApiForgotPassword',
        '/api/v1/attendance-wage/auth/reset-password'    => 'attendance-wage:attendanceApiResetPassword',
        '/api/v1/attendance/clock-in'        => 'attendance-wage:attendanceApiClockIn',
        '/api/v1/attendance/clock-out'       => 'attendance-wage:attendanceApiClockOut',
        '/api/v1/wage/employees'             => 'attendance-wage:wageApiEmployeeCreate',
        '/api/v1/wage/employees/{id}'        => 'attendance-wage:wageApiEmployeeUpdate',
        '/api/v1/wage/periods'               => 'attendance-wage:wageApiPeriodCreate',
        '/api/v1/wage/periods/{id}'          => 'attendance-wage:wageApiPeriodUpdate',
        '/api/v1/wage/compute'               => 'attendance-wage:wageApiComputeEmployee',
        '/api/v1/wage/compute/bulk'          => 'attendance-wage:wageApiBulkCompute',
        '/api/v1/wage/computations/{id}/approve' => 'attendance-wage:wageApiApproveComputation',
        '/api/v1/wage/computations/{id}/pay'      => 'attendance-wage:wageApiPayComputation',
        '/api/v1/wage/adjustments'            => 'attendance-wage:wageApiAdjustmentCreate',
        '/api/v1/wage/adjustments/{id}/approve' => 'attendance-wage:wageApiAdjustmentApprove',
        '/api/v1/wage/deductions'             => 'attendance-wage:wageApiDeductionCreate',
        '/api/v1/wage/deductions/{id}/status' => 'attendance-wage:wageApiDeductionStatus',
        '/api/v1/wage/cash-advances'          => 'attendance-wage:wageApiCashAdvanceCreate',
        '/api/v1/wage/cash-advances/{id}/approve' => 'attendance-wage:wageApiCashAdvanceApprove',
        '/api/v1/wage/holidays'               => 'attendance-wage:wageApiHolidayCreate',
        '/api/v1/wage/benefits/calculate'     => 'attendance-wage:wageApiBenefitsCalculate',
        '/api/v1/wage/migration/bulk'         => 'attendance-wage:wageApiMigrationBulk',
    ],
];
