CREATE TABLE IF NOT EXISTS ehr_appointments (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    appointment_uuid VARCHAR(64) NOT NULL UNIQUE,
    patient_id BIGINT UNSIGNED NOT NULL,
    encounter_id BIGINT UNSIGNED DEFAULT NULL,
    appointment_type VARCHAR(80) NOT NULL,
    scheduled_start DATETIME NOT NULL,
    scheduled_end DATETIME DEFAULT NULL,
    facility_id BIGINT UNSIGNED DEFAULT NULL,
    department_id BIGINT UNSIGNED DEFAULT NULL,
    location_id BIGINT UNSIGNED DEFAULT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'scheduled',
    reason_for_visit VARCHAR(255) DEFAULT NULL,
    notes TEXT DEFAULT NULL,
    created_by_user_id BIGINT UNSIGNED DEFAULT NULL,
    checked_in_at DATETIME DEFAULT NULL,
    roomed_at DATETIME DEFAULT NULL,
    completed_at DATETIME DEFAULT NULL,
    no_show_at DATETIME DEFAULT NULL,
    canceled_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_ehr_appointments_patient (patient_id),
    KEY idx_ehr_appointments_status_start (status, scheduled_start),
    KEY idx_ehr_appointments_department (department_id, scheduled_start),
    CONSTRAINT fk_ehr_appointments_patient FOREIGN KEY (patient_id) REFERENCES ehr_patients(id) ON DELETE CASCADE,
    CONSTRAINT fk_ehr_appointments_encounter FOREIGN KEY (encounter_id) REFERENCES ehr_encounters(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;