/**
 * PAL Job Order Operational Setup — Browser-driven E2E journey.
 *
 * Creates a client and Job Order through the real browser UI,
 * then drives the workflow from draft through ongoing.
 *
 * Best practices:
 *   - data-wb-* attributes as test IDs (generated by ?wb_inspect=1)
 *   - getByRole() for buttons/links
 *   - expect.soft() for non-blocking issue collection
 *   - Required elements use expect().toBeVisible() — no silent skip
 *   - Unique run prefix (timestamp + workerIndex) for cleanup safety
 *
 * Run: ADMIN_USER=pAladmin ADMIN_PASS=pal123456 npx playwright test tests/browser/modules/pal/workflows/pal-lifecycle-interactive.spec.js
 */

// @ts-check
var { test, expect } = require('../../../WorkbenchFixture');
var execSync = require('child_process').execSync;
var path = require('path');

var RUN_ID = Date.now();
var PREFIX = 'E2E-' + RUN_ID;
var CLIENT_NAME = PREFIX + '-Client';
var PROJECT_TITLE = PREFIX + '-Project';
var SEED_CLEANUP = path.resolve(__dirname, '../../../../pal/pal_seed_interactive.php');
var PAL_TEST_TENANT = process.env.PAL_TEST_TENANT || '502';

/**
 * Navigate to a path and wait for the app shell to be ready.
 */
async function goTo(/** @type {import('@playwright/test').Page} */ page, /** @type {string} */ path) {
    await page.goto(path);
    await page.waitForSelector('[data-wb-component="app-shell"]', { timeout: 15000 });
    await page.waitForTimeout(400);
}

// Cleanup: delete records created with our prefix
test.afterAll(async function () {
    try {
        execSync('php ' + SEED_CLEANUP + ' --cleanup --tenant=' + PAL_TEST_TENANT, { encoding: 'utf-8', timeout: 10000 });
        console.log('  🧹 Cleanup done');
    } catch (/** @type {any} */ e) {
        console.error('  ⚠ Cleanup note: ' + e.message);
    }
});

test.describe('pal:jo-operational-setup', function () {

    test('JO operational setup: draft → ongoing', async function (/** @type {{page: import('@playwright/test').Page, integrity: any}} */ { page, integrity }) {
        var base = '/admin/project-audit-ledger';
        var projectId = null;
        var startTime = Date.now();

        // ── Step 1: Create client ──
        await test.step('create client', async function () {
            await goTo(page, base + '/clients/create');
            var nameInput = page.locator('input[name="name"]').first();
            await expect(nameInput, 'Client name field required').toBeVisible({ timeout: 5000 });
            await nameInput.fill(CLIENT_NAME);
            await page.getByRole('button', { name: /save|submit/i }).first().click();
            await page.waitForTimeout(1500);
            console.log('  ✅ Client: ' + CLIENT_NAME);
        });

        // ── Step 2: Create Job Order ──
        await test.step('create job order', async function () {
            await goTo(page, base + '/projects/create');

            // Title (required)
            var titleInput = page.locator('input[name="title"], input[name="project_id"], [data-wb-field="title"]').first();
            await expect(titleInput, 'JO title field required').toBeVisible({ timeout: 5000 });
            await titleInput.fill(PROJECT_TITLE);

            // Contract amount
            var amountInput = page.locator('input[name="contract_amount"], [data-wb-field="contract_amount"]').first();
            if (await amountInput.isVisible({ timeout: 2000 }).catch(() => false)) {
                await amountInput.fill('150000');
            }

            // Client dropdown — pick the second option (first is placeholder)
            var clientSelect = page.locator('select[name="client_id"], [data-wb-field="client_id"]').first();
            if (await clientSelect.isVisible({ timeout: 2000 }).catch(() => false)) {
                var opts = await clientSelect.locator('option').count();
                if (opts > 1) await clientSelect.selectOption({ index: 1 });
            }

            // Add a line item
            var addItemBtn = page.locator('[data-wb-action="add-item"], button:has-text("Add")').first();
            if (await addItemBtn.isVisible({ timeout: 2000 }).catch(() => false)) {
                await addItemBtn.click();
                await page.waitForTimeout(400);
                var itemInput = page.locator('input[name*="particulars"], input[name*="description"], [data-wb-field*="particulars"]').last();
                if (await itemInput.isVisible({ timeout: 2000 }).catch(() => false)) {
                    await itemInput.fill(PREFIX + ' line item');
                }
            }

            // Save (required)
            var saveBtn = page.locator('[data-wb-action="save-as-draft"], button:has-text("Save")').first();
            await expect(saveBtn, 'Save button required').toBeVisible({ timeout: 5000 });
            await saveBtn.click();
            await page.waitForTimeout(2000);

            // Extract project ID from URL or project list
            var url = page.url();
            var match = url.match(/\/projects\/(\d+)/);
            if (match) {
                projectId = parseInt(match[1]);
            } else {
                await goTo(page, base + '/projects');
                var row = page.locator('[data-ikb-list="pal_project"]').locator('tr, [data-ikb-row]').filter({ hasText: PROJECT_TITLE }).first();
                if (await row.isVisible({ timeout: 5000 }).catch(() => false)) {
                    var text = await row.textContent();
                    var idMatch = text.match(/PJ-[^]+\s+#?(\d+)/) || text.match(/#(\d+)/);
                    if (idMatch) projectId = parseInt(idMatch[1]);
                }
            }
            // Required entity — fail if not found
            expect(projectId, 'Project ID must be extracted after save').not.toBeNull();
            console.log('  ✅ JO #' + projectId + ': ' + PROJECT_TITLE);
            integrity.perf('JO create', Date.now() - startTime);
        });

        // ── Step 3: Submit for Approval ──
        await test.step('draft → pending', async function () {
            await goTo(page, base + '/projects/' + projectId + '/edit');

            var submitBtn = page.locator('[data-wb-action="submit-for-approval"], button:has-text("Submit for Approval"), button:has-text("Submit")').first();
            await expect(submitBtn, 'Submit button required on edit page').toBeVisible({ timeout: 5000 });
            await submitBtn.click();
            await page.waitForTimeout(1500);

            await goTo(page, base + '/projects/' + projectId);
            await expect(page.locator('#wb-main'), 'Status should be Pending after submit')
                .toContainText('Pending', { timeout: 5000 });
            console.log('  ✅ Pending');
        });

        // ── Step 4: Approve exact entity ──
        await test.step('pending → approved', async function () {
            await goTo(page, base + '/approvals');

            // Find approval row for THIS project by entity type + title
            var row = page.locator('[data-wb-entity-type="project"]').filter({ hasText: PROJECT_TITLE }).first();
            await expect(row, 'Approval row for ' + PROJECT_TITLE + ' must exist').toBeVisible({ timeout: 8000 });

            await row.getByRole('button', { name: /approve/i }).click();

            // Confirm modal if present
            var confirmBtn = page.getByRole('button', { name: /yes|confirm|ok/i }).first();
            if (await confirmBtn.isVisible({ timeout: 3000 }).catch(() => false)) {
                await confirmBtn.click();
            }
            await page.waitForTimeout(1000);

            await goTo(page, base + '/projects/' + projectId);
            await expect(page.locator('#wb-main'), 'Status should be Approved')
                .toContainText('Approved', { timeout: 5000 });
            console.log('  ✅ Approved');
        });

        // ── Step 5: Start Work ──
        await test.step('approved → started', async function () {
            await goTo(page, base + '/projects/' + projectId + '/edit');

            var startBtn = page.locator('[data-wb-action="start-work"], button:has-text("Start Work"), button:has-text("Start")').first();
            await expect(startBtn, 'Start Work button required').toBeVisible({ timeout: 5000 });
            await startBtn.click();
            await page.waitForTimeout(1000);
            console.log('  ✅ Started');
        });

        // ── Step 6: Mark Ongoing ──
        await test.step('started → ongoing', async function () {
            await goTo(page, base + '/projects/' + projectId + '/edit');

            var ongoingBtn = page.locator('[data-wb-action="mark-ongoing"], button:has-text("Mark Ongoing"), button:has-text("Ongoing")').first();
            await expect(ongoingBtn, 'Mark Ongoing button required').toBeVisible({ timeout: 5000 });
            await ongoingBtn.click();
            await page.waitForTimeout(1000);
            console.log('  ✅ Ongoing');
        });

        // ── Step 7: Verify dashboard reflects the JO ──
        await test.step('verify dashboard', async function () {
            await goTo(page, base);
            await expect(page.getByRole('heading', { name: /dashboard/i }), 'Dashboard heading').toBeVisible();

            // The project must appear somewhere on the dashboard
            var body = await page.locator('#wb-main').textContent();
            expect(body, 'Dashboard must reference the created JO').toContain(PROJECT_TITLE);

            console.log('  ✅ Dashboard shows ' + PROJECT_TITLE);
            integrity.perf('full setup journey', Date.now() - startTime);
        });
    });
});
