/**
 * PAL Job Order Operational Setup — Browser-driven E2E journey.
 *
 * Creates a client and Job Order through the real browser UI,
 * then drives the workflow from draft through ongoing.
 *
 * Best practices:
 *   - data-wb-* attributes as test IDs (generated by ?wb_inspect=1)
 *   - getByRole() for buttons/links
 *   - expect.soft() for non-blocking issue collection
 *   - Required elements use expect().toBeVisible() — no silent skip
 *   - Unique run prefix (timestamp + workerIndex) for cleanup safety
 *
 * Run: ADMIN_USER=pAladmin ADMIN_PASS=pal123456 npx playwright test tests/browser/modules/pal/workflows/pal-lifecycle-interactive.spec.js
 */

// @ts-nocheck
var { test, expect } = require('../../../WorkbenchFixture');
var execSync = require('child_process').execSync;
var path = require('path');

var RUN_ID = Date.now();
var PREFIX = 'E2E-' + RUN_ID;
var CLIENT_NAME = PREFIX + '-Client';
var PROJECT_TITLE = PREFIX + '-Project';
var SEED_CLEANUP = path.resolve(__dirname, '../../../../pal/pal_seed_interactive.php');
var PAL_TEST_TENANT = process.env.PAL_TEST_TENANT || '502';

/**
 * Navigate to a path and wait for the app shell to be ready.
 */
async function goTo(/** @type {import('@playwright/test').Page} */ page, /** @type {string} */ path) {
    await page.goto(path);
    await page.waitForSelector('[data-wb-component="app-shell"]', { timeout: 15000 });
    await page.waitForTimeout(400);
}

// Cleanup: delete records created with our prefix
test.afterAll(async function () {
    try {
        execSync('php ' + SEED_CLEANUP + ' --cleanup --tenant=' + PAL_TEST_TENANT, { encoding: 'utf-8', timeout: 10000 });
        console.log('  🧹 Cleanup done');
    } catch (/** @type {any} */ e) {
        console.error('  ⚠ Cleanup note: ' + e.message);
    }
});

test.describe('pal:jo-operational-setup', function () {

    test('JO operational setup: draft → ongoing', async function (/** @type {{page: import('@playwright/test').Page, integrity: any}} */ { page, integrity }) {
        test.setTimeout(120000); // 2 min — 7 browser steps
        var base = '/admin/project-audit-ledger';
        var projectId = null;
        var startTime = Date.now();

        // ── Step 1: Create client ──
        await test.step('create client', async function () {
            await goTo(page, base + '/clients/create');
            var nameInput = page.locator('input[name="name"]').first();
            await expect(nameInput, 'Client name field required').toBeVisible({ timeout: 5000 });
            await nameInput.fill(CLIENT_NAME);
            // Submit: try semantic selectors, fall back to any submit button
            var saveBtn = page.locator('[data-wb-action], button[type="submit"], button:has-text("Save"), button:has-text("Create"), button:has-text("Add")').first();
            await expect(saveBtn, 'Save/submit button required on client form').toBeVisible({ timeout: 5000 });
            await saveBtn.click();
            await page.waitForTimeout(1500);
            console.log('  ✅ Client: ' + CLIENT_NAME);
        });

        // ── Step 2: Create Job Order ──
        await test.step('create job order', async function () {
            await goTo(page, base + '/projects/create');

            // Title (required)
            var titleInput = page.locator('input[name="title"], input[name="project_id"], [data-wb-field="title"]').first();
            await expect(titleInput, 'JO title field required').toBeVisible({ timeout: 5000 });
            await titleInput.fill(PROJECT_TITLE);

            // Contract amount
            var amountInput = page.locator('input[name="contract_amount"], [data-wb-field="contract_amount"]').first();
            if (await amountInput.isVisible({ timeout: 2000 }).catch(() => false)) {
                await amountInput.fill('150000');
            }

            // Client dropdown — pick the second option (first is placeholder)
            var clientSelect = page.locator('select[name="client_id"], [data-wb-field="client_id"]').first();
            if (await clientSelect.isVisible({ timeout: 2000 }).catch(() => false)) {
                var opts = await clientSelect.locator('option').count();
                if (opts > 1) await clientSelect.selectOption({ index: 1 });
            }

            // Add a line item
            var addItemBtn = page.locator('[data-wb-action="add-item"], button:has-text("Add")').first();
            if (await addItemBtn.isVisible({ timeout: 2000 }).catch(() => false)) {
                await addItemBtn.click();
                await page.waitForTimeout(400);
                var itemInput = page.locator('input[name*="particulars"], input[name*="description"], [data-wb-field*="particulars"]').last();
                if (await itemInput.isVisible({ timeout: 2000 }).catch(() => false)) {
                    await itemInput.fill(PREFIX + ' line item');
                }
            }

            // Save (required) — try semantic selectors
            var saveBtn = page.locator('[data-wb-action="save-as-draft"], button[type="submit"], button:has-text("Save"), button:has-text("Create"), button:has-text("Submit")').first();
            await expect(saveBtn, 'Save button required').toBeVisible({ timeout: 5000 });
            await saveBtn.click();
            // ajaxSubmit redirects to project detail on success.
            // Use regex to avoid matching /projects/create (current page).
            await page.waitForURL(/\/admin\/project-audit-ledger\/projects\/\d+/, { timeout: 15000 });
            await page.waitForTimeout(500);
            // Extract ID from URL
            var urlMatch = page.url().match(/\/projects\/(\d+)/);
            projectId = urlMatch ? parseInt(urlMatch[1]) : null;
            expect(projectId, 'Project ID must be extractable from redirect URL').not.toBeNull();
            console.log('  ✅ JO #' + projectId + ': ' + PROJECT_TITLE);
            integrity.perf('JO create', Date.now() - startTime);
        });

        // ── Step 3: Submit for Approval (via in-browser API call) ──
        await test.step('draft → pending', async function () {
            // Use page.evaluate to make the API call with the browser's cookies/session
            var result = await page.evaluate(async function (opts) {
                var csrfInput = document.querySelector('input[name="_token"]');
                var token = csrfInput ? csrfInput.value : '';
                var fd = new URLSearchParams();
                fd.append('status', 'pending');
                if (token) fd.append('_token', token);
                try {
                    var r = await fetch('/api/v1/project-audit-ledger/projects/' + opts.projectId + '/status', {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
                        body: fd.toString(),
                    });
                    return await r.json();
                } catch (e) {
                    return { ok: false, error: e.message };
                }
            }, { projectId: projectId });

            if (result.ok) {
                console.log('  ✅ Pending (via API)');
            } else {
                integrity.issue({
                    kind: 'bug', severity: 'critical',
                    where: 'JO submit', detail: 'API status change failed: ' + (result.error || 'unknown'),
                    recommendation: 'Check palApiProjectStatus handler'
                });
                console.log('  ⚠ API status change failed: ' + (result.error || 'unknown'));
            }

            // Navigate to detail and verify status (case-insensitive)
            await goTo(page, base + '/projects/' + projectId);
            var hasPending = await page.locator('#wb-main').textContent().then(function (t) { return t.toLowerCase().includes('pending'); }).catch(function () { return false; });
            if (hasPending) {
                console.log('  ✅ Status Pending');
            } else {
                console.log('  ⚠ Status not Pending on detail page');
            }
        });

        // ── Step 4: Approve via API ──
        await test.step('pending → approved', async function () {
            // Get approval ID from the visible row and approve via API
            await goTo(page, base + '/approvals');

            var row = page.locator('[data-wb-entity-type="project"]').filter({ hasText: 'Project #' + projectId }).first();
            await expect(row, 'Approval row for Project #' + projectId + ' must exist').toBeVisible({ timeout: 8000 });

            // Extract approval ID from the approve button's onclick attribute
            var approveBtn = row.getByRole('button', { name: /approve/i }).first();
            var onclick = await approveBtn.getAttribute('onclick') || '';
            var approvalId = onclick.match(/approve\((\d+)/);

            if (!approvalId) {
                integrity.issue({ kind: 'bug', severity: 'critical', where: 'approve', detail: 'Could not extract approval ID from button onclick' });
            }

            // Approve via direct API call
            var result = { ok: false, error: 'approvalId missing' };
            if (approvalId) {
                result = await page.evaluate(async function (opts) {
                    var csrfInput = document.querySelector('input[name="_token"]');
                    var token = csrfInput ? csrfInput.value : '';
                    var fd = new URLSearchParams();
                    fd.append('decision', 'approved');
                    fd.append('remarks', '');
                    if (token) fd.append('_token', token);
                    try {
                        var r = await fetch('/api/v1/project-audit-ledger/approvals/' + opts.id + '/decide', {
                            method: 'POST',
                            headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
                            body: fd.toString(),
                        });
                        return await r.json();
                    } catch (e) {
                        return { ok: false, error: e.message };
                    }
                }, { id: parseInt(approvalId[1]) });
            }

            if (result.ok) {
                console.log('  ✅ Approved (via API)');
            } else {
                console.log('  ⚠ Approve failed: ' + (result.error || 'unknown'));
            }

            await page.waitForTimeout(500);
            await goTo(page, base + '/projects/' + projectId);
            await expect(page.locator('#wb-main'), 'Status should be approved')
                .toContainText(/approved/i, { timeout: 5000 });
            console.log('  ✅ Approved');
        });

        // ── Step 5: Start Work ──
        await test.step('approved → started', async function () {
            await goTo(page, base + '/projects/' + projectId + '/edit');

            var startBtn = page.locator('[data-wb-action="start-work"], button:has-text("Start Work"), button:has-text("Start")').first();
            await expect(startBtn, 'Start Work button required').toBeVisible({ timeout: 5000 });
            await startBtn.click();
            // ajaxSubmit submits the form then calls location.reload() after 800ms
            await page.waitForTimeout(2000);
            console.log('  ✅ Started');
        });

        // ── Step 6: Mark Ongoing ──
        await test.step('started → ongoing', async function () {
            await goTo(page, base + '/projects/' + projectId + '/edit');

            var ongoingBtn = page.locator('[data-wb-action="mark-ongoing"], button:has-text("Mark Ongoing"), button:has-text("Ongoing")').first();
            await expect(ongoingBtn, 'Mark Ongoing button required').toBeVisible({ timeout: 5000 });
            await ongoingBtn.click();
            // ajaxSubmit submits the form then calls location.reload() after 800ms
            await page.waitForTimeout(2000);
            console.log('  ✅ Ongoing');
        });

        // ── Step 7: Verify dashboard reflects the JO ──
        await test.step('verify dashboard', async function () {
            await goTo(page, base);
            await expect(page.getByRole('heading', { name: /dashboard/i }), 'Dashboard heading').toBeVisible();

            // The project must appear somewhere on the dashboard
            var body = await page.locator('#wb-main').textContent();
            expect(body, 'Dashboard must reference the created JO').toContain(PROJECT_TITLE);

            console.log('  ✅ Dashboard shows ' + PROJECT_TITLE);
            integrity.perf('full setup journey', Date.now() - startTime);
        });
    });
});
