/**
 * PAL Instruction-Based Lifecycle — Browser-driven E2E test.
 *
 * Creates data through the REAL browser UI (no PHP seed).
 * Uses Playwright best practices:
 *   - data-wb-* attributes as test IDs (generated by ?wb_inspect=1)
 *   - getByRole() for buttons/links where possible
 *   - expect.soft() collects multiple issues without aborting
 *   - Web-first assertions (toBeVisible, toContainText) with auto-wait
 *
 * Run: ADMIN_USER=pAladmin ADMIN_PASS=pal123456 npx playwright test tests/browser/modules/pal/workflows/pal-lifecycle-interactive.spec.js
 */

// @ts-check
var { test, expect } = require('../../../WorkbenchFixture');

var PREFIX = 'E2E-' + new Date().toISOString().slice(0, 10).replace(/-/g, '');
var CLIENT_NAME = PREFIX + '-Client';
var PROJECT_TITLE = PREFIX + '-Project';

/**
 * Navigate to a path and wait for the app shell to be ready.
 */
async function goTo(/** @type {import('@playwright/test').Page} */ page, /** @type {string} */ path) {
    await page.goto(path);
    await page.waitForSelector('[data-wb-component="app-shell"]', { timeout: 15000 });
    // Let Alpine.js / htmx settle
    await page.waitForTimeout(400);
}

test.describe('pal:instruction-based-lifecycle', function () {

    test('Full JO lifecycle through browser UI', async function (/** @type {{page: import('@playwright/test').Page, integrity: any}} */ { page, integrity }) {
        var base = '/admin/project-audit-ledger';
        var projectId = null;
        var startTime = Date.now();

        // ── Step 1: Create client ──
        await test.step('create client', async function () {
            await goTo(page, base + '/clients/create');

            var nameInput = page.locator('input[name="name"]').first();
            if (await nameInput.isVisible({ timeout: 3000 }).catch(() => false)) {
                await nameInput.fill(CLIENT_NAME);
                await page.getByRole('button', { name: /save|submit/i }).first().click();
                await page.waitForTimeout(1500);
                console.log('  ✅ Client: ' + CLIENT_NAME);
            } else {
                integrity.friction('Client create form: input[name="name"] not found');
                console.log('  ⚠ Client form field not detected — continuing');
            }
        });

        // ── Step 2: Create Job Order ──
        await test.step('create job order', async function () {
            await goTo(page, base + '/projects/create');

            // Title
            var titleInput = page.locator('input[name="title"], input[name="project_id"], [data-wb-field="title"]').first();
            if (await titleInput.isVisible({ timeout: 3000 }).catch(() => false)) {
                await titleInput.fill(PROJECT_TITLE);
            }

            // Contract amount
            var amountInput = page.locator('input[name="contract_amount"], [data-wb-field="contract_amount"]').first();
            if (await amountInput.isVisible({ timeout: 2000 }).catch(() => false)) {
                await amountInput.fill('150000');
            }

            // Client dropdown
            var clientSelect = page.locator('select[name="client_id"], [data-wb-field="client_id"]').first();
            if (await clientSelect.isVisible({ timeout: 2000 }).catch(() => false)) {
                // Select second option (first is usually placeholder)
                var opts = await clientSelect.locator('option').count();
                if (opts > 1) await clientSelect.selectOption({ index: 1 });
            }

            // Add a line item
            var addItemBtn = page.locator('[data-wb-action="add-item"], button:has-text("Add")').first();
            if (await addItemBtn.isVisible({ timeout: 2000 }).catch(() => false)) {
                await addItemBtn.click();
                await page.waitForTimeout(400);
                var itemInput = page.locator('input[name*="particulars"], input[name*="description"], [data-wb-field*="particulars"]').last();
                if (await itemInput.isVisible({ timeout: 2000 }).catch(() => false)) {
                    await itemInput.fill('E2E line item — ' + PREFIX);
                }
            }

            // Save as draft
            var saveBtn = page.locator('[data-wb-action="save-as-draft"], button:has-text("Save")').first();
            await expect(saveBtn, 'Save button should be visible').toBeVisible({ timeout: 5000 });
            await saveBtn.click();
            await page.waitForTimeout(2000);

            // Try to extract ID from redirect
            var url = page.url();
            var match = url.match(/\/projects\/(\d+)/);
            if (match) {
                projectId = parseInt(match[1]);
                console.log('  ✅ JO #' + projectId + ': ' + PROJECT_TITLE);
            } else {
                // Fallback: navigate to project list and find our project
                await goTo(page, base + '/projects');
                var row = page.locator('[data-ikb-list="pal_project"]').locator('tr, [data-ikb-row]').filter({ hasText: PROJECT_TITLE }).first();
                if (await row.isVisible({ timeout: 3000 }).catch(() => false)) {
                    var text = await row.textContent();
                    var idMatch = text.match(/#(\d+)/);
                    if (idMatch) projectId = parseInt(idMatch[1]);
                }
                console.log('  ✅ JO: ' + PROJECT_TITLE + ' (id: ' + (projectId || 'unknown') + ')');
            }

            integrity.perf('JO create', Date.now() - startTime);
        });

        if (!projectId) {
            integrity.issue({ kind: 'bug', severity: 'critical', where: 'JO create', detail: 'Could not create or find project', recommendation: 'Check JO form field selectors and save redirect' });
            test.skip(true, 'No project created — cannot continue workflow');
            return;
        }

        // ── Step 3: Submit for Approval ──
        await test.step('draft → pending: submit for approval', async function () {
            await goTo(page, base + '/projects/' + projectId + '/edit');

            // Use data-wb-action from inspect mode, fall back to button text
            var submitBtn = page.locator('[data-wb-action="submit-for-approval"], button:has-text("Submit")').first();
            await expect(submitBtn, 'Submit button should be on edit page').toBeVisible({ timeout: 5000 });
            await submitBtn.click();
            await page.waitForTimeout(1500);

            await goTo(page, base + '/projects/' + projectId);
            await expect.soft(page.locator('#wb-main'), 'Status should be Pending after submit')
                .toContainText('Pending', { timeout: 5000 });
            console.log('  ✅ Submitted for approval');
        });

        // ── Step 4: Approve ──
        await test.step('pending → approved', async function () {
            await goTo(page, base + '/approvals');

            // Find approval row for our project (by entity type + title match)
            var row = page.locator('[data-wb-entity-type="project"]').filter({ hasText: PROJECT_TITLE }).first();
            var rowVisible = await row.isVisible({ timeout: 3000 }).catch(() => false);

            if (rowVisible) {
                await row.getByRole('button', { name: /approve/i }).click();
                console.log('  ✅ Approved via entity-specific row');
            } else {
                // Fallback: any approve button (only one pending item should exist)
                var anyBtn = page.getByRole('button', { name: /approve/i }).first();
                await expect(anyBtn, 'Approve button should exist').toBeVisible({ timeout: 3000 });
                await anyBtn.click();
                console.log('  ⚠ Approved via fallback (entity row not found)');
                integrity.friction('Approval queue: no data-wb-entity-type on row for JO #' + projectId);
            }

            // Confirm modal
            var confirmBtn = page.getByRole('button', { name: /yes|confirm/i }).first();
            if (await confirmBtn.isVisible({ timeout: 3000 }).catch(() => false)) {
                await confirmBtn.click();
            }
            await page.waitForTimeout(1000);

            await goTo(page, base + '/projects/' + projectId);
            await expect.soft(page.locator('#wb-main'), 'Status should be Approved')
                .toContainText('Approved', { timeout: 5000 });
        });

        // ── Step 5: Start Work ──
        await test.step('approved → started', async function () {
            await goTo(page, base + '/projects/' + projectId + '/edit');

            var startBtn = page.locator('[data-wb-action="start-work"], button:has-text("Start")').first();
            if (await startBtn.isVisible({ timeout: 3000 }).catch(() => false)) {
                await startBtn.click();
                await page.waitForTimeout(1000);
                console.log('  ✅ Started');
            } else {
                integrity.friction('No "Start Work" button on edit page for JO #' + projectId);
            }
        });

        // ── Step 6: Mark Ongoing ──
        await test.step('started → ongoing', async function () {
            await goTo(page, base + '/projects/' + projectId + '/edit');

            var ongoingBtn = page.locator('[data-wb-action="mark-ongoing"], button:has-text("Ongoing")').first();
            if (await ongoingBtn.isVisible({ timeout: 3000 }).catch(() => false)) {
                await ongoingBtn.click();
                await page.waitForTimeout(1000);
                console.log('  ✅ Ongoing');
            }
        });

        // ── Step 7: Verify dashboard reflects activity ──
        await test.step('verify dashboard', async function () {
            await goTo(page, base);
            await expect(page.getByRole('heading', { name: /dashboard/i }), 'Dashboard heading').toBeVisible();

            // Active projects should be ≥ 1 (our JO is ongoing)
            var body = await page.locator('#wb-main').textContent();
            if (!body.includes(PROJECT_TITLE)) {
                integrity.friction('Dashboard does not show active JO by title');
            }

            console.log('  ✅ Dashboard verified');
            integrity.perf('full lifecycle', Date.now() - startTime);
        });
    });
});
