<?php

declare(strict_types=1);

namespace Ikabud\Kernel\Workbench\Graph;

/**
 * SpecGenerator — generates Playwright test specs from graph gaps.
 *
 * Reads gap data from GapAnalyzer and emits .spec.js files that exercise
 * the uncovered paths. Each generated spec follows the proven pattern:
 *   seed → navigate → act → verify → cleanup
 */
final class SpecGenerator
{
    /** @var array<int, string> */
    private array $generatedFiles = [];

    public function __construct(
        private readonly string $moduleId,
        private readonly string $projectRoot,
        private readonly string $outputDir,
    ) {}

    /**
     * Generate test specs for the given gaps.
     *
     * @param array<int, array{path: array, reason: string, type: string, label: string}> $gaps
     * @return array<int, string> Generated file paths
     */
    public function generate(array $gaps): array
    {
        $this->generatedFiles = [];
        $outputDir = $this->outputDir;

        if (!is_dir($outputDir)) {
            if (!mkdir($outputDir, 0755, true)) {
                throw new \RuntimeException("Cannot create output directory: {$outputDir}");
            }
        }

        // Group gaps by type for efficient spec generation
        $grouped = [];
        foreach ($gaps as $gap) {
            $grouped[$gap['type']][] = $gap;
        }

        foreach ($grouped as $type => $typeGaps) {
            $spec = $this->generateSpecForType($type, $typeGaps);
            if ($spec === null) continue;

            $filename = $this->moduleId . '-generated-' . $type . '.spec.js';
            $filepath = $outputDir . '/' . $filename;
            file_put_contents($filepath, $spec);
            $this->generatedFiles[] = $filepath;
        }

        return $this->generatedFiles;
    }

    private function generateSpecForType(string $type, array $gaps): ?string
    {
        $moduleIdDash = str_replace('_', '-', $this->moduleId);
        $modulePath = str_replace('-', '/', $moduleIdDash);
        $testTitle = ucwords(str_replace('_', ' ', $type));

        $lines = [];
        $lines[] = "/**";
        $lines[] = " * Auto-generated by ARK Workbench Gap Analyzer";
        $lines[] = " * Module: {$this->moduleId}";
        $lines[] = " * Type: {$type}";
        $lines[] = " * Gaps covered: " . count($gaps);
        $lines[] = " */";
        $lines[] = "var { test, expect } = require('../../../WorkbenchFixture');";
        $lines[] = "var execSync = require('child_process').execSync;";
        $lines[] = "var path = require('path');";
        $lines[] = "var SEED = path.resolve(__dirname, '../../../../pal/pal_seed_interactive.php');";
        $lines[] = "var PAL_TEST_TENANT = process.env.PAL_TEST_TENANT || '502';";
        $lines[] = "";

        $lines[] = "async function goTo(page, url) {";
        $lines[] = "    await page.goto(url);";
        $lines[] = "    await page.waitForSelector('[data-wb-component=\"app-shell\"]', { timeout: 15000 });";
        $lines[] = "    await page.waitForTimeout(400);";
        $lines[] = "}";
        $lines[] = "";

        $lines[] = "test.describe('pal:generated-{$type}', function () {";

        foreach ($gaps as $i => $gap) {
            $path = $gap['path'];
            $label = $path['label'] ?? "Path {$i}";
            $testName = $this->sanitizeTestName($label);
            $lines[] = "    test('{$testName}', async function ({ page, integrity }) {";
            $lines[] = "        test.setTimeout(60000);";
            $lines[] = "        var base = '/admin/" . $modulePath . "';";

            switch ($type) {
                case 'entity_list':
                    $lines = array_merge($lines, $this->generateEntityListTest($path));
                    break;
                case 'entity_create':
                case 'entity_edit':
                    $lines = array_merge($lines, $this->generateEntityFormTest($path, $type));
                    break;
                case 'entity_detail':
                    $lines = array_merge($lines, $this->generateEntityDetailTest($path));
                    break;
                case 'action_execute':
                    $lines = array_merge($lines, $this->generateActionTest($path));
                    break;
                case 'workflow_transition':
                    $lines = array_merge($lines, $this->generateTransitionTest($path));
                    break;
                case 'route_exists':
                    $lines = array_merge($lines, $this->generateRouteTest($path));
                    break;
                default:
                    $lines[] = "        integrity.gap('Untested path: {$label}');";
                    break;
            }

            $lines[] = "    });";
            $lines[] = "";
        }

        $lines[] = "});";

        return implode("\n", $lines);
    }

    private function generateEntityListTest(array $path): array
    {
        $lines = [];
        $lines[] = "        var out = execSync('php ' + SEED + ' --tenant=' + PAL_TEST_TENANT, { encoding: 'utf-8', timeout: 15000 });";
        $lines[] = "        var seed = JSON.parse(out);";
        $lines[] = "        if (!seed.ok) { integrity.gap('Seed failed, cannot test entity list'); return; }";
        $lines[] = "";
        $lines[] = "        await goTo(page, base);";
        $lines[] = "        // Verify entity list renders";
        $lines[] = "        await page.waitForSelector('[data-ikb-list], [data-wb-list]', { timeout: 10000 }).catch(function () {";
        $lines[] = "            integrity.gap('Entity list container not found');";
        $lines[] = "        });";
        $lines[] = "        var rows = await page.locator('[data-wb-list] tbody tr, [data-ikb-list] tbody tr').count();";
        $lines[] = "        if (rows === 0) { integrity.gap('Entity list has no rows after seed'); }";
        $lines[] = "        else { console.log('  Entity list rows: ' + rows); }";
        $lines[] = "";
        $lines[] = "        execSync('php ' + SEED + ' --cleanup --tenant=' + PAL_TEST_TENANT, { encoding: 'utf-8', timeout: 10000 });";
        return $lines;
    }

    private function generateEntityFormTest(array $path, string $type): array
    {
        $lines = [];
        $lines[] = "        var out = execSync('php ' + SEED + ' --tenant=' + PAL_TEST_TENANT, { encoding: 'utf-8', timeout: 15000 });";
        $lines[] = "        var seed = JSON.parse(out);";
        $lines[] = "        if (!seed.ok) { integrity.gap('Seed failed'); return; }";
        $lines[] = "";
        $lines[] = "        var url = base + '/projects/' + seed.project_id + '/edit?disyl_nocache=1';";
        $lines[] = "        await goTo(page, url);";
        $lines[] = "";
        $lines[] = "        // Verify form has action buttons";
        $lines[] = "        var actions = await page.locator('[data-wb-action]').count();";
        $lines[] = "        if (actions === 0) { integrity.gap('No data-wb-action buttons on edit form'); }";
        $lines[] = "        else { console.log('  Form actions: ' + actions); }";
        $lines[] = "";
        $lines[] = "        // Verify required fields present";
        $lines[] = "        var titleField = page.locator('input[name=\"title\"]');";
        $lines[] = "        if (await titleField.isVisible({ timeout: 3000 }).catch(function () { return false; })) {";
        $lines[] = "            console.log('  Title field visible');";
        $lines[] = "        } else { integrity.gap('Title field not visible on form'); }";
        $lines[] = "";
        $lines[] = "        execSync('php ' + SEED + ' --cleanup --tenant=' + PAL_TEST_TENANT, { encoding: 'utf-8', timeout: 10000 });";
        return $lines;
    }

    private function generateEntityDetailTest(array $path): array
    {
        $lines = [];
        $lines[] = "        var out = execSync('php ' + SEED + ' --tenant=' + PAL_TEST_TENANT, { encoding: 'utf-8', timeout: 15000 });";
        $lines[] = "        var seed = JSON.parse(out);";
        $lines[] = "        if (!seed.ok) return;";
        $lines[] = "";
        $lines[] = "        await goTo(page, base + '/projects/' + seed.project_id + '?disyl_nocache=1&wb_inspect=1');";
        $lines[] = "        await page.waitForSelector('[data-wb-component=\"detail-header\"]', { timeout: 10000 });";
        $lines[] = "        var m = await page.evaluate(function () { return window.__wbManifest; });";
        $lines[] = "        if (m.status) { console.log('  Status: ' + m.status); }";
        $lines[] = "        else { integrity.gap('Status badge not detected on detail page'); }";
        $lines[] = "";
        $lines[] = "        execSync('php ' + SEED + ' --cleanup --tenant=' + PAL_TEST_TENANT, { encoding: 'utf-8', timeout: 10000 });";
        return $lines;
    }

    private function generateActionTest(array $path): array
    {
        $lines = [];
        $lines[] = "        integrity.gap('Action test not auto-generated yet. See action ID for manual review.');";
        $lines[] = "        console.log('Action needs test spec');";
        return $lines;
    }

    private function generateTransitionTest(array $path): array
    {
        $nodes = $path['nodes'] ?? [];
        if (count($nodes) < 2) {
            return ["        integrity.gap('Transition path has too few nodes');"];
        }

        $from = explode(':', $nodes[0]);
        $to = explode(':', $nodes[1]);
        $fromStatus = end($from);
        $toStatus = end($to);

        $lines = [];
        $lines[] = "        var out = execSync('php ' + SEED + ' --tenant=' + PAL_TEST_TENANT, { encoding: 'utf-8', timeout: 15000 });";
        $lines[] = "        var seed = JSON.parse(out);";
        $lines[] = "        if (!seed.ok) return;";
        $lines[] = "        var pid = seed.project_id;";
        $lines[] = "";
        $lines[] = "        // Transition {$fromStatus} → {$toStatus}";
        $lines[] = "        var result = await page.evaluate(async function (opts) {";
        $lines[] = "            var csrf = document.querySelector('input[name=\"_token\"]');";
        $lines[] = "            var token = csrf ? csrf.value : '';";
        $lines[] = "            var fd = new URLSearchParams();";
        $lines[] = "            fd.append('status', opts.toStatus);";
        $lines[] = "            if (token) fd.append('_token', token);";
        $lines[] = "            var r = await fetch('/api/v1/project-audit-ledger/projects/' + opts.pid + '/status',";
        $lines[] = "                { method: 'POST', body: fd, headers: { 'Content-Type': 'application/x-www-form-urlencoded' } });";
        $lines[] = "            return { ok: (await r.json()).ok };";
        $lines[] = "        }, { pid: pid, toStatus: '{$toStatus}' });";
        $lines[] = "        if (result.ok) { console.log('  {$fromStatus}→{$toStatus}: OK'); }";
        $lines[] = "        else { integrity.gap('Transition {$fromStatus}→{$toStatus} failed'); }";
        $lines[] = "";
        $lines[] = "        execSync('php ' + SEED + ' --cleanup --tenant=' + PAL_TEST_TENANT, { encoding: 'utf-8', timeout: 10000 });";
        return $lines;
    }

    private function generateRouteTest(array $path): array
    {
        $lines = [];
        $lines[] = "        // Verify route loads without error";
        $lines[] = "        await goTo(page, base);";
        $lines[] = "        var hasError = await page.locator('.wb-error, [data-wb-error]').count();";
        $lines[] = "        if (hasError > 0) { integrity.gap('Route may have an error element on page'); }";
        $lines[] = "        else { console.log('  Page loaded'); }";
        return $lines;
    }

    private function sanitizeTestName(string $name): string
    {
        $name = str_replace(['→', ':', '/', '\\'], [' to ', ' ', '-', '-'], $name);
        $name = preg_replace('/[^a-zA-Z0-9 _-]/', '', $name);
        $name = substr($name, 0, 80);
        return trim($name);
    }
}
