ALTER TABLE pal_users
  MODIFY role ENUM('admin','supervisor','encoder','printer') NOT NULL DEFAULT 'encoder';

CREATE TABLE IF NOT EXISTS pal_print_jobs (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    tenant_id INT UNSIGNED NOT NULL,
    job_number VARCHAR(50) NOT NULL,
    project_id INT UNSIGNED DEFAULT NULL,
    sale_id INT UNSIGNED DEFAULT NULL,
    sale_item_id INT UNSIGNED DEFAULT NULL,
    material_id INT UNSIGNED DEFAULT NULL,
    client_name VARCHAR(255) NOT NULL,
    material_label VARCHAR(255) NOT NULL,
    size_label VARCHAR(100) DEFAULT NULL,
    width DECIMAL(10,2) DEFAULT NULL,
    height DECIMAL(10,2) DEFAULT NULL,
    size_unit VARCHAR(20) DEFAULT NULL,
    quantity DECIMAL(10,2) NOT NULL DEFAULT 1.00,
    cost DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    status ENUM('pending','done') NOT NULL DEFAULT 'pending',
    comment_option_key VARCHAR(50) DEFAULT NULL,
    comment_text VARCHAR(500) DEFAULT NULL,
    completed_by INT UNSIGNED DEFAULT NULL,
    completed_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by INT UNSIGNED DEFAULT NULL,
    updated_at DATETIME DEFAULT NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_pal_print_jobs_job_number (tenant_id, job_number),
    KEY idx_pal_print_jobs_status (tenant_id, status, created_at),
    KEY idx_pal_print_jobs_project (project_id),
    KEY idx_pal_print_jobs_sale (sale_id),
    KEY idx_pal_print_jobs_sale_item (sale_item_id),
    KEY idx_pal_print_jobs_material (material_id),
    CONSTRAINT fk_pal_print_jobs_project FOREIGN KEY (project_id) REFERENCES pal_projects(id) ON DELETE SET NULL,
    CONSTRAINT fk_pal_print_jobs_sale FOREIGN KEY (sale_id) REFERENCES pal_sales(id) ON DELETE SET NULL,
    CONSTRAINT fk_pal_print_jobs_sale_item FOREIGN KEY (sale_item_id) REFERENCES pal_sale_items(id) ON DELETE SET NULL,
    CONSTRAINT fk_pal_print_jobs_material FOREIGN KEY (material_id) REFERENCES pal_materials(id) ON DELETE SET NULL,
    CONSTRAINT fk_pal_print_jobs_created_by FOREIGN KEY (created_by) REFERENCES pal_users(id) ON DELETE SET NULL,
    CONSTRAINT fk_pal_print_jobs_completed_by FOREIGN KEY (completed_by) REFERENCES pal_users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
