CREATE TABLE IF NOT EXISTS `wms_products` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `sku` VARCHAR(100) NOT NULL,
    `barcode` VARCHAR(100) NULL,
    `name` VARCHAR(255) NOT NULL,
    `description` TEXT NULL,
    `unit` VARCHAR(50) NOT NULL DEFAULT 'pcs',
    `product_type` VARCHAR(50) NOT NULL DEFAULT 'physical',
    `weight` DECIMAL(14,4) NULL,
    `dimensions` JSON NULL,
    `is_batch_tracked` TINYINT(1) NOT NULL DEFAULT 0,
    `meta` JSON NULL,
    `is_active` TINYINT(1) NOT NULL DEFAULT 1,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` DATETIME NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_wms_products_sku` (`sku`),
    UNIQUE KEY `uq_wms_products_barcode` (`barcode`),
    KEY `idx_wms_products_name` (`name`),
    KEY `idx_wms_products_type` (`product_type`, `is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
