CREATE TABLE IF NOT EXISTS `wms_stocks` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `product_id` INT UNSIGNED NOT NULL,
    `warehouse_id` INT UNSIGNED NOT NULL,
    `location_id` INT UNSIGNED NOT NULL,
    `batch_id` INT UNSIGNED NULL,
    `batch_key` INT UNSIGNED GENERATED ALWAYS AS (COALESCE(`batch_id`, 0)) STORED,
    `qty_on_hand` DECIMAL(14,4) NOT NULL DEFAULT 0,
    `qty_reserved` DECIMAL(14,4) NOT NULL DEFAULT 0,
    `qty_available` DECIMAL(14,4) GENERATED ALWAYS AS (`qty_on_hand` - `qty_reserved`) STORED,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_wms_stocks_position_batch` (`product_id`, `location_id`, `batch_key`),
    KEY `idx_wms_stocks_warehouse` (`warehouse_id`, `product_id`),
    KEY `idx_wms_stocks_location` (`location_id`),
    KEY `idx_wms_stocks_batch` (`batch_id`),
    KEY `idx_wms_stocks_available` (`qty_available`),
    CONSTRAINT `fk_wms_stocks_product` FOREIGN KEY (`product_id`) REFERENCES `wms_products` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_wms_stocks_warehouse` FOREIGN KEY (`warehouse_id`) REFERENCES `wms_warehouses` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_wms_stocks_location` FOREIGN KEY (`location_id`) REFERENCES `wms_locations` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_wms_stocks_batch` FOREIGN KEY (`batch_id`) REFERENCES `wms_batches` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
