CREATE TABLE IF NOT EXISTS `wms_movements` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `movement_type` VARCHAR(40) NOT NULL,
    `reference_type` VARCHAR(50) NULL,
    `reference_id` INT UNSIGNED NULL,
    `product_id` INT UNSIGNED NOT NULL,
    `warehouse_id` INT UNSIGNED NOT NULL,
    `location_id` INT UNSIGNED NOT NULL,
    `batch_id` INT UNSIGNED NULL,
    `qty` DECIMAL(14,4) NOT NULL,
    `qty_before` DECIMAL(14,4) NOT NULL DEFAULT 0,
    `qty_after` DECIMAL(14,4) NOT NULL DEFAULT 0,
    `unit_cost` DECIMAL(14,4) NULL,
    `notes` TEXT NULL,
    `actor_user_id` INT UNSIGNED NULL,
    `meta` JSON NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_wms_movements_product_created` (`product_id`, `created_at`),
    KEY `idx_wms_movements_reference` (`reference_type`, `reference_id`),
    KEY `idx_wms_movements_warehouse_created` (`warehouse_id`, `created_at`),
    KEY `idx_wms_movements_type_created` (`movement_type`, `created_at`),
    CONSTRAINT `fk_wms_movements_product` FOREIGN KEY (`product_id`) REFERENCES `wms_products` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_wms_movements_warehouse` FOREIGN KEY (`warehouse_id`) REFERENCES `wms_warehouses` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_wms_movements_location` FOREIGN KEY (`location_id`) REFERENCES `wms_locations` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_wms_movements_batch` FOREIGN KEY (`batch_id`) REFERENCES `wms_batches` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
