-- WMS Stock, Movements, Inventory Adjustments
-- Phase 3: Movement Ledger

CREATE TABLE IF NOT EXISTS wms_stock (
    id                INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    product_id        INT UNSIGNED NOT NULL,
    warehouse_id      INT UNSIGNED NOT NULL,
    location_id       INT UNSIGNED NULL DEFAULT NULL,
    batch_id          INT UNSIGNED NULL DEFAULT NULL,
    qty_on_hand       DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
    qty_reserved      DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
    qty_staged        DECIMAL(14,4) NOT NULL DEFAULT 0.0000 COMMENT 'In staging — unavailable until putaway',
    qty_in_transit    DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
    last_movement_at  DATETIME NULL DEFAULT NULL,
    created_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_wms_stock (product_id, warehouse_id, location_id, batch_id),
    INDEX idx_wms_stock_product (product_id),
    INDEX idx_wms_stock_warehouse (warehouse_id),
    INDEX idx_wms_stock_location (location_id),
    INDEX idx_wms_stock_batch (batch_id),
    INDEX idx_wms_stock_low (warehouse_id, qty_on_hand),
    CONSTRAINT fk_wms_stock_product FOREIGN KEY (product_id) REFERENCES wms_products (id) ON DELETE CASCADE,
    CONSTRAINT fk_wms_stock_warehouse FOREIGN KEY (warehouse_id) REFERENCES wms_warehouses (id) ON DELETE CASCADE,
    CONSTRAINT fk_wms_stock_location FOREIGN KEY (location_id) REFERENCES wms_locations (id) ON DELETE SET NULL,
    CONSTRAINT fk_wms_stock_batch FOREIGN KEY (batch_id) REFERENCES wms_batches (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS wms_stock_movements (
    id               INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    product_id       INT UNSIGNED NOT NULL,
    warehouse_id     INT UNSIGNED NOT NULL,
    from_location_id INT UNSIGNED NULL DEFAULT NULL,
    to_location_id   INT UNSIGNED NULL DEFAULT NULL,
    batch_id         INT UNSIGNED NULL DEFAULT NULL,
    movement_type    VARCHAR(50) NOT NULL COMMENT 'receipt, transfer, sale, adjustment_up, adjustment_down, return_in, return_out, scrap, production_consumption, production_output',
    quantity         DECIMAL(14,4) NOT NULL COMMENT 'Positive for additions, negative for removals',
    prev_qty_on_hand DECIMAL(14,4) NULL DEFAULT NULL,
    new_qty_on_hand  DECIMAL(14,4) NULL DEFAULT NULL,
    reference_type   VARCHAR(50) NULL DEFAULT NULL COMMENT 'delivery, order, adjustment, transfer',
    reference_id     INT UNSIGNED NULL DEFAULT NULL,
    reason           TEXT NULL DEFAULT NULL,
    notes            TEXT NULL DEFAULT NULL,
    created_by       INT UNSIGNED NULL DEFAULT NULL,
    created_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_wms_movement_product (product_id),
    INDEX idx_wms_movement_warehouse (warehouse_id),
    INDEX idx_wms_movement_type (movement_type),
    INDEX idx_wms_movement_reference (reference_type, reference_id),
    INDEX idx_wms_movement_created (created_at),
    INDEX idx_wms_movement_batch (batch_id),
    CONSTRAINT fk_wms_movement_product FOREIGN KEY (product_id) REFERENCES wms_products (id) ON DELETE CASCADE,
    CONSTRAINT fk_wms_movement_warehouse FOREIGN KEY (warehouse_id) REFERENCES wms_warehouses (id) ON DELETE CASCADE,
    CONSTRAINT fk_wms_movement_from_loc FOREIGN KEY (from_location_id) REFERENCES wms_locations (id) ON DELETE SET NULL,
    CONSTRAINT fk_wms_movement_to_loc FOREIGN KEY (to_location_id) REFERENCES wms_locations (id) ON DELETE SET NULL,
    CONSTRAINT fk_wms_movement_batch FOREIGN KEY (batch_id) REFERENCES wms_batches (id) ON DELETE SET NULL,
    CONSTRAINT fk_wms_movement_user FOREIGN KEY (created_by) REFERENCES wms_users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS wms_inventory_adjustments (
    id                INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    product_id        INT UNSIGNED NOT NULL,
    warehouse_id      INT UNSIGNED NOT NULL,
    location_id       INT UNSIGNED NULL DEFAULT NULL,
    batch_id          INT UNSIGNED NULL DEFAULT NULL,
    adjustment_type   VARCHAR(50) NOT NULL COMMENT 'cycle_count, damage, loss, correction, write_off',
    expected_qty      DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
    counted_qty       DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
    difference        DECIMAL(14,4) GENERATED ALWAYS AS (counted_qty - expected_qty) STORED,
    reason            TEXT NULL DEFAULT NULL,
    status            VARCHAR(20) NOT NULL DEFAULT 'pending' COMMENT 'pending, approved, rejected',
    created_by        INT UNSIGNED NOT NULL,
    approved_by       INT UNSIGNED NULL DEFAULT NULL,
    counted_at        DATETIME NULL DEFAULT NULL,
    approved_at       DATETIME NULL DEFAULT NULL,
    created_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_wms_adjustment_product (product_id),
    INDEX idx_wms_adjustment_warehouse (warehouse_id),
    INDEX idx_wms_adjustment_status (status),
    INDEX idx_wms_adjustment_type (adjustment_type),
    CONSTRAINT fk_wms_adjustment_product FOREIGN KEY (product_id) REFERENCES wms_products (id) ON DELETE CASCADE,
    CONSTRAINT fk_wms_adjustment_warehouse FOREIGN KEY (warehouse_id) REFERENCES wms_warehouses (id) ON DELETE CASCADE,
    CONSTRAINT fk_wms_adjustment_location FOREIGN KEY (location_id) REFERENCES wms_locations (id) ON DELETE SET NULL,
    CONSTRAINT fk_wms_adjustment_batch FOREIGN KEY (batch_id) REFERENCES wms_batches (id) ON DELETE SET NULL,
    CONSTRAINT fk_wms_adjustment_creator FOREIGN KEY (created_by) REFERENCES wms_users (id) ON DELETE CASCADE,
    CONSTRAINT fk_wms_adjustment_approver FOREIGN KEY (approved_by) REFERENCES wms_users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
