CREATE TABLE IF NOT EXISTS `wms_deliveries` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `reference_number` VARCHAR(100) NOT NULL,
    `supplier_name` VARCHAR(255) NULL,
    `supplier_reference` VARCHAR(100) NULL,
    `warehouse_id` INT UNSIGNED NOT NULL,
    `status` VARCHAR(20) NOT NULL DEFAULT 'pending',
    `expected_at` DATETIME NULL,
    `received_at` DATETIME NULL,
    `notes` TEXT NULL,
    `meta` JSON NULL,
    `created_by` INT UNSIGNED NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` DATETIME NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_wms_deliveries_reference` (`reference_number`),
    KEY `idx_wms_deliveries_status` (`status`, `warehouse_id`),
    CONSTRAINT `fk_wms_deliveries_warehouse` FOREIGN KEY (`warehouse_id`) REFERENCES `wms_warehouses` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `wms_delivery_items` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `delivery_id` INT UNSIGNED NOT NULL,
    `product_id` INT UNSIGNED NOT NULL,
    `location_id` INT UNSIGNED NOT NULL,
    `batch_id` INT UNSIGNED NULL,
    `qty_expected` DECIMAL(14,4) NOT NULL DEFAULT 0,
    `qty_received` DECIMAL(14,4) NOT NULL DEFAULT 0,
    `unit_cost` DECIMAL(14,4) NULL,
    `meta` JSON NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_wms_delivery_items_delivery` (`delivery_id`),
    KEY `idx_wms_delivery_items_product` (`product_id`),
    CONSTRAINT `fk_wms_delivery_items_delivery` FOREIGN KEY (`delivery_id`) REFERENCES `wms_deliveries` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_wms_delivery_items_product` FOREIGN KEY (`product_id`) REFERENCES `wms_products` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_wms_delivery_items_location` FOREIGN KEY (`location_id`) REFERENCES `wms_locations` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_wms_delivery_items_batch` FOREIGN KEY (`batch_id`) REFERENCES `wms_batches` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
