CREATE TABLE IF NOT EXISTS `wms_orders` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `order_number` VARCHAR(100) NOT NULL,
    `external_reference` VARCHAR(100) NULL,
    `customer_name` VARCHAR(255) NULL,
    `warehouse_id` INT UNSIGNED NOT NULL,
    `status` VARCHAR(20) NOT NULL DEFAULT 'pending',
    `priority` INT NOT NULL DEFAULT 100,
    `ordered_at` DATETIME NULL,
    `dispatched_at` DATETIME NULL,
    `notes` TEXT NULL,
    `meta` JSON NULL,
    `created_by` INT UNSIGNED NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` DATETIME NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_wms_orders_number` (`order_number`),
    KEY `idx_wms_orders_status` (`status`, `warehouse_id`),
    KEY `idx_wms_orders_priority` (`priority`, `created_at`),
    CONSTRAINT `fk_wms_orders_warehouse` FOREIGN KEY (`warehouse_id`) REFERENCES `wms_warehouses` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `wms_order_items` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `order_id` INT UNSIGNED NOT NULL,
    `product_id` INT UNSIGNED NOT NULL,
    `location_id` INT UNSIGNED NULL,
    `batch_id` INT UNSIGNED NULL,
    `qty_ordered` DECIMAL(14,4) NOT NULL DEFAULT 0,
    `qty_reserved` DECIMAL(14,4) NOT NULL DEFAULT 0,
    `qty_picked` DECIMAL(14,4) NOT NULL DEFAULT 0,
    `notes` VARCHAR(500) NULL,
    `meta` JSON NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_wms_order_items_order` (`order_id`),
    KEY `idx_wms_order_items_product` (`product_id`),
    CONSTRAINT `fk_wms_order_items_order` FOREIGN KEY (`order_id`) REFERENCES `wms_orders` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_wms_order_items_product` FOREIGN KEY (`product_id`) REFERENCES `wms_products` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_wms_order_items_location` FOREIGN KEY (`location_id`) REFERENCES `wms_locations` (`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_wms_order_items_batch` FOREIGN KEY (`batch_id`) REFERENCES `wms_batches` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
