-- WMS Cycle Counts, Returns, Tasks, Recipes/BOM, Production, Webhooks
-- Phase 5: Advanced Operations

CREATE TABLE IF NOT EXISTS wms_cycle_counts (
    id                INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    warehouse_id      INT UNSIGNED NOT NULL,
    count_number      VARCHAR(100) NOT NULL,
    count_type        VARCHAR(30) NOT NULL DEFAULT 'full' COMMENT 'full, partial, ad_hoc, abc_a, abc_b, abc_c',
    status            VARCHAR(30) NOT NULL DEFAULT 'open' COMMENT 'open, in_progress, completed, cancelled',
    assigned_to       INT UNSIGNED NULL DEFAULT NULL,
    scheduled_at      DATE NULL DEFAULT NULL,
    completed_at      DATETIME NULL DEFAULT NULL,
    notes             TEXT NULL DEFAULT NULL,
    created_by        INT UNSIGNED NOT NULL,
    created_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_wms_cycle_count_number (count_number),
    INDEX idx_wms_cycle_count_warehouse (warehouse_id),
    INDEX idx_wms_cycle_count_status (status),
    INDEX idx_wms_cycle_count_assignee (assigned_to),
    CONSTRAINT fk_wms_cycle_count_warehouse FOREIGN KEY (warehouse_id) REFERENCES wms_warehouses (id) ON DELETE CASCADE,
    CONSTRAINT fk_wms_cycle_count_assignee FOREIGN KEY (assigned_to) REFERENCES wms_users (id) ON DELETE SET NULL,
    CONSTRAINT fk_wms_cycle_count_creator FOREIGN KEY (created_by) REFERENCES wms_users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS wms_cycle_count_items (
    id                INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    cycle_count_id    INT UNSIGNED NOT NULL,
    product_id        INT UNSIGNED NOT NULL,
    location_id       INT UNSIGNED NULL DEFAULT NULL,
    batch_id          INT UNSIGNED NULL DEFAULT NULL,
    expected_qty      DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
    counted_qty       DECIMAL(14,4) NULL DEFAULT NULL,
    difference        DECIMAL(14,4) GENERATED ALWAYS AS (COALESCE(counted_qty, 0) - expected_qty) STORED,
    status            VARCHAR(30) NOT NULL DEFAULT 'pending' COMMENT 'pending, counted, resolved',
    notes             TEXT NULL DEFAULT NULL,
    counted_at        DATETIME NULL DEFAULT NULL,
    created_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_wms_cycle_count_item_count (cycle_count_id),
    INDEX idx_wms_cycle_count_item_product (product_id),
    INDEX idx_wms_cycle_count_item_location (location_id),
    INDEX idx_wms_cycle_count_item_status (status),
    CONSTRAINT fk_wms_cycle_count_item_count FOREIGN KEY (cycle_count_id) REFERENCES wms_cycle_counts (id) ON DELETE CASCADE,
    CONSTRAINT fk_wms_cycle_count_item_product FOREIGN KEY (product_id) REFERENCES wms_products (id) ON DELETE CASCADE,
    CONSTRAINT fk_wms_cycle_count_item_location FOREIGN KEY (location_id) REFERENCES wms_locations (id) ON DELETE SET NULL,
    CONSTRAINT fk_wms_cycle_count_item_batch FOREIGN KEY (batch_id) REFERENCES wms_batches (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS wms_returns (
    id                INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    return_number     VARCHAR(100) NOT NULL,
    order_id          INT UNSIGNED NULL DEFAULT NULL,
    warehouse_id      INT UNSIGNED NOT NULL,
    return_type       VARCHAR(30) NOT NULL DEFAULT 'customer' COMMENT 'customer, supplier, internal',
    status            VARCHAR(30) NOT NULL DEFAULT 'pending' COMMENT 'pending, inspected, approved, rejected, restocked, disposed',
    customer_name     VARCHAR(255) NULL DEFAULT NULL,
    customer_email    VARCHAR(255) NULL DEFAULT NULL,
    reason            TEXT NULL DEFAULT NULL,
    disposition       VARCHAR(50) NULL DEFAULT NULL COMMENT 'restock, scrap, return_to_supplier, donate',
    notes             TEXT NULL DEFAULT NULL,
    created_by        INT UNSIGNED NOT NULL,
    inspected_by      INT UNSIGNED NULL DEFAULT NULL,
    created_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    inspected_at      DATETIME NULL DEFAULT NULL,
    updated_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_wms_return_number (return_number),
    INDEX idx_wms_return_order (order_id),
    INDEX idx_wms_return_warehouse (warehouse_id),
    INDEX idx_wms_return_status (status),
    INDEX idx_wms_return_type (return_type),
    CONSTRAINT fk_wms_return_order FOREIGN KEY (order_id) REFERENCES wms_orders (id) ON DELETE SET NULL,
    CONSTRAINT fk_wms_return_warehouse FOREIGN KEY (warehouse_id) REFERENCES wms_warehouses (id) ON DELETE CASCADE,
    CONSTRAINT fk_wms_return_creator FOREIGN KEY (created_by) REFERENCES wms_users (id) ON DELETE CASCADE,
    CONSTRAINT fk_wms_return_inspector FOREIGN KEY (inspected_by) REFERENCES wms_users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS wms_return_items (
    id                INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    return_id         INT UNSIGNED NOT NULL,
    product_id        INT UNSIGNED NOT NULL,
    batch_id          INT UNSIGNED NULL DEFAULT NULL,
    quantity          DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
    condition         VARCHAR(30) NULL DEFAULT NULL COMMENT 'damaged, defective, good, expired',
    disposition       VARCHAR(50) NULL DEFAULT NULL COMMENT 'restock, scrap, return_to_supplier, donate',
    notes             TEXT NULL DEFAULT NULL,
    created_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_wms_return_item_return (return_id),
    INDEX idx_wms_return_item_product (product_id),
    INDEX idx_wms_return_item_batch (batch_id),
    CONSTRAINT fk_wms_return_item_return FOREIGN KEY (return_id) REFERENCES wms_returns (id) ON DELETE CASCADE,
    CONSTRAINT fk_wms_return_item_product FOREIGN KEY (product_id) REFERENCES wms_products (id) ON DELETE CASCADE,
    CONSTRAINT fk_wms_return_item_batch FOREIGN KEY (batch_id) REFERENCES wms_batches (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS wms_tasks (
    id                INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    warehouse_id      INT UNSIGNED NOT NULL,
    task_type         VARCHAR(50) NOT NULL COMMENT 'putaway, pick, cycle_count, receive, transfer, audit, clean, other',
    status            VARCHAR(30) NOT NULL DEFAULT 'open' COMMENT 'open, assigned, in_progress, completed, cancelled',
    priority          VARCHAR(10) NOT NULL DEFAULT 'medium' COMMENT 'low, medium, high, critical',
    title             VARCHAR(255) NOT NULL,
    description       TEXT NULL DEFAULT NULL,
    reference_type    VARCHAR(50) NULL DEFAULT NULL,
    reference_id      INT UNSIGNED NULL DEFAULT NULL,
    assigned_to       INT UNSIGNED NULL DEFAULT NULL,
    completed_by      INT UNSIGNED NULL DEFAULT NULL,
    due_at            DATETIME NULL DEFAULT NULL,
    completed_at      DATETIME NULL DEFAULT NULL,
    created_by        INT UNSIGNED NOT NULL,
    created_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_wms_task_warehouse (warehouse_id),
    INDEX idx_wms_task_type (task_type),
    INDEX idx_wms_task_status (status),
    INDEX idx_wms_task_priority (priority),
    INDEX idx_wms_task_assignee (assigned_to),
    INDEX idx_wms_task_reference (reference_type, reference_id),
    CONSTRAINT fk_wms_task_warehouse FOREIGN KEY (warehouse_id) REFERENCES wms_warehouses (id) ON DELETE CASCADE,
    CONSTRAINT fk_wms_task_assignee FOREIGN KEY (assigned_to) REFERENCES wms_users (id) ON DELETE SET NULL,
    CONSTRAINT fk_wms_task_completer FOREIGN KEY (completed_by) REFERENCES wms_users (id) ON DELETE SET NULL,
    CONSTRAINT fk_wms_task_creator FOREIGN KEY (created_by) REFERENCES wms_users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS wms_recipes (
    id                INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    product_id        INT UNSIGNED NOT NULL,
    recipe_code       VARCHAR(100) NOT NULL,
    name              VARCHAR(255) NOT NULL,
    description       TEXT NULL DEFAULT NULL,
    output_qty        DECIMAL(14,4) NOT NULL DEFAULT 1.0000 COMMENT 'Quantity produced per batch',
    output_unit       VARCHAR(50) NOT NULL DEFAULT 'pcs',
    version           INT UNSIGNED NOT NULL DEFAULT 1,
    is_active         TINYINT(1) NOT NULL DEFAULT 1,
    notes             TEXT NULL DEFAULT NULL,
    created_by        INT UNSIGNED NOT NULL,
    created_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_wms_recipe_code (recipe_code),
    INDEX idx_wms_recipe_product (product_id),
    INDEX idx_wms_recipe_active (is_active),
    CONSTRAINT fk_wms_recipe_product FOREIGN KEY (product_id) REFERENCES wms_products (id) ON DELETE CASCADE,
    CONSTRAINT fk_wms_recipe_creator FOREIGN KEY (created_by) REFERENCES wms_users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS wms_recipe_ingredients (
    id                INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    recipe_id         INT UNSIGNED NOT NULL,
    ingredient_product_id INT UNSIGNED NOT NULL,
    quantity          DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
    unit              VARCHAR(50) NOT NULL DEFAULT 'pcs',
    wastage_pct       DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Expected wastage percentage',
    sort_order        INT UNSIGNED NOT NULL DEFAULT 0,
    notes             TEXT NULL DEFAULT NULL,
    created_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_wms_recipe_ingredient_recipe (recipe_id),
    INDEX idx_wms_recipe_ingredient_product (ingredient_product_id),
    CONSTRAINT fk_wms_recipe_ingredient_recipe FOREIGN KEY (recipe_id) REFERENCES wms_recipes (id) ON DELETE CASCADE,
    CONSTRAINT fk_wms_recipe_ingredient_product FOREIGN KEY (ingredient_product_id) REFERENCES wms_products (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS wms_production_orders (
    id                INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    recipe_id         INT UNSIGNED NOT NULL,
    order_number      VARCHAR(100) NOT NULL,
    warehouse_id      INT UNSIGNED NOT NULL,
    status            VARCHAR(30) NOT NULL DEFAULT 'planned' COMMENT 'planned, in_progress, completed, cancelled',
    quantity          DECIMAL(14,4) NOT NULL DEFAULT 0.0000 COMMENT 'Target output quantity',
    quantity_produced DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
    location_id       INT UNSIGNED NULL DEFAULT NULL COMMENT 'Output location',
    started_at        DATETIME NULL DEFAULT NULL,
    completed_at      DATETIME NULL DEFAULT NULL,
    notes             TEXT NULL DEFAULT NULL,
    created_by        INT UNSIGNED NOT NULL,
    completed_by      INT UNSIGNED NULL DEFAULT NULL,
    created_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_wms_production_order_number (order_number),
    INDEX idx_wms_production_order_recipe (recipe_id),
    INDEX idx_wms_production_order_warehouse (warehouse_id),
    INDEX idx_wms_production_order_status (status),
    CONSTRAINT fk_wms_production_order_recipe FOREIGN KEY (recipe_id) REFERENCES wms_recipes (id) ON DELETE CASCADE,
    CONSTRAINT fk_wms_production_order_warehouse FOREIGN KEY (warehouse_id) REFERENCES wms_warehouses (id) ON DELETE CASCADE,
    CONSTRAINT fk_wms_production_order_location FOREIGN KEY (location_id) REFERENCES wms_locations (id) ON DELETE SET NULL,
    CONSTRAINT fk_wms_production_order_creator FOREIGN KEY (created_by) REFERENCES wms_users (id) ON DELETE CASCADE,
    CONSTRAINT fk_wms_production_order_completer FOREIGN KEY (completed_by) REFERENCES wms_users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS wms_production_order_items (
    id                INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    production_order_id INT UNSIGNED NOT NULL,
    ingredient_product_id INT UNSIGNED NOT NULL,
    quantity_required DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
    quantity_consumed DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
    batch_id          INT UNSIGNED NULL DEFAULT NULL,
    notes             TEXT NULL DEFAULT NULL,
    created_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_wms_production_order_item_order (production_order_id),
    INDEX idx_wms_production_order_item_product (ingredient_product_id),
    INDEX idx_wms_production_order_item_batch (batch_id),
    CONSTRAINT fk_wms_production_order_item_order FOREIGN KEY (production_order_id) REFERENCES wms_production_orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_wms_production_order_item_product FOREIGN KEY (ingredient_product_id) REFERENCES wms_products (id) ON DELETE CASCADE,
    CONSTRAINT fk_wms_production_order_item_batch FOREIGN KEY (batch_id) REFERENCES wms_batches (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS wms_event_webhooks (
    id                INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    event_name        VARCHAR(100) NOT NULL,
    url               VARCHAR(500) NOT NULL,
    secret            VARCHAR(255) NULL DEFAULT NULL COMMENT 'HMAC secret for payload verification',
    headers           JSON NULL DEFAULT NULL COMMENT 'Custom headers as JSON object',
    retry_count       TINYINT UNSIGNED NOT NULL DEFAULT 3,
    timeout_ms        INT UNSIGNED NOT NULL DEFAULT 5000,
    is_active         TINYINT(1) NOT NULL DEFAULT 1,
    last_triggered_at DATETIME NULL DEFAULT NULL,
    last_status       VARCHAR(30) NULL DEFAULT NULL COMMENT 'success, failed',
    created_by        INT UNSIGNED NOT NULL,
    created_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_wms_webhook_event (event_name),
    INDEX idx_wms_webhook_active (is_active),
    CONSTRAINT fk_wms_webhook_creator FOREIGN KEY (created_by) REFERENCES wms_users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
