CREATE TABLE IF NOT EXISTS `wms_returns` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `reference_number` VARCHAR(100) NOT NULL,
    `order_id` INT UNSIGNED DEFAULT NULL,
    `customer_name` VARCHAR(255) DEFAULT NULL,
    `warehouse_id` INT UNSIGNED NOT NULL,
    `status` ENUM('pending','inspecting','restocked','disposed','cancelled') NOT NULL DEFAULT 'pending',
    `reason` VARCHAR(500) DEFAULT NULL,
    `received_at` DATETIME DEFAULT NULL,
    `notes` TEXT DEFAULT NULL,
    `meta` JSON DEFAULT NULL,
    `created_by` INT UNSIGNED DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` DATETIME DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_wms_returns_reference_number` (`reference_number`),
    KEY `idx_wms_returns_warehouse` (`warehouse_id`),
    KEY `idx_wms_returns_order` (`order_id`),
    KEY `idx_wms_returns_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `wms_return_items` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `return_id` INT UNSIGNED NOT NULL,
    `product_id` INT UNSIGNED NOT NULL,
    `location_id` INT UNSIGNED NOT NULL,
    `batch_id` INT UNSIGNED DEFAULT NULL,
    `qty_returned` DECIMAL(14,4) NOT NULL DEFAULT '0.0000',
    `qty_restocked` DECIMAL(14,4) NOT NULL DEFAULT '0.0000',
    `condition` ENUM('good','damaged','expired','unknown') NOT NULL DEFAULT 'unknown',
    `notes` VARCHAR(500) DEFAULT NULL,
    `restock_movement_id` BIGINT UNSIGNED DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_wms_return_items_return` (`return_id`),
    KEY `idx_wms_return_items_product` (`product_id`),
    KEY `idx_wms_return_items_location` (`location_id`),
    KEY `idx_wms_return_items_batch` (`batch_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
