<?php

declare(strict_types=1);

require_once __DIR__ . '/poc6-shadow-build.php';

function poc6l_render_status_doc(array $artifact): string
{
    $f = $artifact['fingerprint'];
    $tenant = $artifact['disposable_tenant'] ?? [];
    return "# POC6 lifecycle proof status\n\n"
        . "Regenerated by `php tools/poc6-lifecycle-proof.php`.\n\n"
        . "- Proof artifact: `{$artifact['artifact_path']}`\n"
        . "- HEAD: `{$f['head_sha']}`\n"
        . "- Dirty worktree captured: `" . (!empty($f['dirty']) ? 'yes' : 'no') . "`\n"
        . "- Golden module: `{$artifact['module_id']}`\n"
        . "- Disposable tenant: `" . ($tenant['tenant_key'] ?? 'n/a') . "`\n"
        . "- Disposable DB: `" . ($tenant['db_name'] ?? 'n/a') . "`\n"
        . "- Verdict: `{$artifact['verdict']}`\n";
}

function poc6l_build_shadow(): array
{
    $repoRoot = poc6_repo_root();
    $artifactDir = $repoRoot . '/storage/poc6';
    $allowedRepoWrites = [$artifactDir, $repoRoot . '/docs'];

    $head = poc6_run(['git', 'rev-parse', 'HEAD'], $repoRoot);
    if ($head['exit_code'] !== 0) {
        throw new RuntimeException('Unable to resolve HEAD: ' . $head['output']);
    }
    $headSha = trim($head['stdout']);
    $shortHead = substr($headSha, 0, 12);

    $status = poc6_run(['git', 'status', '--porcelain'], $repoRoot);
    $dirty = trim($status['stdout']) !== '';

    $modifiedTracked = poc6_run(['git', 'diff', '--name-only', 'HEAD'], $repoRoot);
    if ($modifiedTracked['exit_code'] !== 0) {
        throw new RuntimeException('Unable to list modified tracked files: ' . $modifiedTracked['output']);
    }
    $modifiedTrackedPaths = array_values(array_filter(array_map('trim', preg_split('/\R/', trim($modifiedTracked['stdout'])) ?: []), 'strlen'));
    sort($modifiedTrackedPaths);

    $tempRoot = rtrim(sys_get_temp_dir(), DIRECTORY_SEPARATOR) . '/poc6-lifecycle-' . $shortHead . '-' . getmypid() . '-' . bin2hex(random_bytes(4));
    $captureRoot = $tempRoot . '/capture';
    $shadowRoot = $tempRoot . '/shadow';
    poc6_mkdir($captureRoot, $repoRoot, $allowedRepoWrites);
    poc6_mkdir($shadowRoot, $repoRoot, $allowedRepoWrites);

    $archive = poc6_run(['/bin/sh', '-lc', 'git archive HEAD | tar -x -C ' . escapeshellarg($captureRoot)], $repoRoot);
    if ($archive['exit_code'] !== 0) {
        throw new RuntimeException('git archive extraction failed: ' . $archive['output']);
    }

    foreach ($modifiedTrackedPaths as $relativePath) {
        $source = $repoRoot . '/' . $relativePath;
        if (is_file($source)) {
            poc6_copy_file($source, $captureRoot . '/' . $relativePath, $repoRoot, $allowedRepoWrites);
        }
    }

    $publicInputs = [
        'ikabud', 'kernel', 'src', 'config', 'public', 'vendor', 'database', 'locales', 'templates', 'modules', 'docs',
        'bootstrap.php', 'composer.json', 'composer.lock', 'README.md', 'LICENSE', 'LICENSE.md', 'LICENSE.txt',
        'CONTRIBUTING.md', 'SECURITY.md', 'CODE_OF_CONDUCT.md', 'scripts/guard-module-manifests.php',
    ];
    foreach ($publicInputs as $relativePath) {
        $source = $captureRoot . '/' . $relativePath;
        if (file_exists($source)) {
            poc6_copy_tree($source, $shadowRoot . '/' . $relativePath, $repoRoot, $allowedRepoWrites);
        }
    }
    poc6_mkdir($shadowRoot . '/tests', $repoRoot, $allowedRepoWrites);
    poc6_mkdir($shadowRoot . '/storage', $repoRoot, $allowedRepoWrites);

    $capturedFiles = poc6_list_files($captureRoot);
    $capturedHashes = [];
    foreach ($capturedFiles as $relativePath) {
        $capturedHashes[$relativePath] = hash_file('sha256', $captureRoot . '/' . $relativePath);
    }

    return [
        'repo_root' => $repoRoot,
        'head_sha' => $headSha,
        'short_head' => $shortHead,
        'dirty' => $dirty,
        'modified_tracked' => $modifiedTrackedPaths,
        'capture_root' => $captureRoot,
        'shadow_root' => $shadowRoot,
        'temp_root' => $tempRoot,
        'captured_files' => $capturedFiles,
        'captured_hashes' => $capturedHashes,
    ];
}

function poc6l_remove_tree(string $path): void
{
    if ($path === '' || !file_exists($path)) {
        return;
    }
    $realPath = realpath($path);
    $tmp = realpath(sys_get_temp_dir());
    if ($realPath === false || $tmp === false || ($realPath !== $tmp && !str_starts_with($realPath, $tmp . DIRECTORY_SEPARATOR))) {
        return;
    }
    if (is_file($realPath) || is_link($realPath)) {
        @unlink($realPath);
        return;
    }
    $it = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($realPath, FilesystemIterator::SKIP_DOTS), RecursiveIteratorIterator::CHILD_FIRST);
    foreach ($it as $entry) {
        if ($entry->isDir() && !$entry->isLink()) {
            @rmdir($entry->getPathname());
        } else {
            @unlink($entry->getPathname());
        }
    }
    @rmdir($realPath);
}

function poc6l_enrich_shadow(string $shadowRoot, string $moduleId, string $hostModuleId, string $failModuleId): void
{
    $prefix = str_replace('-', '_', $moduleId);
    $table = $prefix . '_records';
    $moduleDir = $shadowRoot . '/modules/' . $moduleId;
    $templateDir = $shadowRoot . '/templates/modules/' . $moduleId;
    if (!is_dir($moduleDir)) {
        throw new RuntimeException('Golden module scaffold missing: ' . $moduleDir);
    }

    $manifest = [
        'id' => $moduleId,
        'name' => 'Golden Cleanroom Lifecycle Module',
        'version' => '1.0.0',
        'description' => 'Shadow-only clean-room lifecycle proof module',
        'author' => 'Ikabud',
        'entry_module' => false,
        'owns_tables' => [$table],
        'reads_tables' => [],
        'migrations' => ['database/migrations/001_golden.sql'],
        'capabilities' => [
            'exposes' => [
                ['id' => 'golden_cap.ping@1', 'priority' => 50, 'modes' => ['first']],
                ['id' => 'entity.list.golden_entity@1', 'priority' => 50, 'modes' => ['first']],
                ['id' => 'entity.get.golden_entity@1', 'priority' => 50, 'modes' => ['first']],
            ],
            'depends' => [],
            'policy' => [
                'capabilities' => [
                    'golden_cap.ping@1' => ['allow_callers' => ['kernel', $moduleId]],
                ],
            ],
        ],
        'routes' => true,
        'events' => [['key' => 'golden.lifecycle.proved']],
        'nav' => [],
        'uninstall' => [
            'disable_safe' => true,
            'retain_data_by_default' => true,
            'supports_data_export' => false,
            'requires_confirmation_to_drop_data' => true,
        ],
    ];

    $helpers = <<<'PHP'
<?php

declare(strict_types=1);

function __PREFIX___capability_handlers(): array
{
    return [
        'golden_cap.ping@1' => '__PREFIX___cap_golden_cap_ping_1',
        'entity.list.golden_entity@1' => '__PREFIX___cap_entity_list_golden_entity_1',
        'entity.get.golden_entity@1' => '__PREFIX___cap_entity_get_golden_entity_1',
    ];
}

function __PREFIX___db(): \Ikabud\Kernel\Contracts\ModuleDB
{
    $ctx = module();
    if (!$ctx) {
        throw new RuntimeException('Module context unavailable');
    }
    return $ctx->db();
}

function __PREFIX___assert_tenant_and_role(string $requiredRole = 'admin'): array
{
    $ctx = capability_call_context() ?? [];
    $tenantId = function_exists('app') ? app()->tenant()->current() : null;
    $user = is_array($ctx['user'] ?? null) ? $ctx['user'] : null;
    $role = (string)($user['role'] ?? '');
    if (!is_int($tenantId) || $tenantId <= 0) {
        throw new DomainException('default_deny: tenant context required');
    }
    if ($role !== $requiredRole) {
        throw new DomainException('default_deny: role required');
    }
    return $ctx;
}

if (function_exists('app') && ($app = app()) !== null && method_exists($app, 'entityViews')) {
    $app->entityViews()->registerView('golden_entity', 'compact', [
        'fields' => ['id', 'title', 'status', 'db_name'],
        'actions' => ['view'],
        'limit' => 10,
        'empty_state' => 'No golden records.',
    ], '__MODULE_ID__');
}

function __PREFIX___cap_golden_cap_ping_1(mixed $payload, string $capabilityId = '', string $providerId = ''): array
{
    $ctx = __PREFIX___assert_tenant_and_role('admin');
    $payload = is_array($payload) ? $payload : [];
    $db = __PREFIX___db();
    $dbName = (string)($db->query('SELECT DATABASE()')->fetchColumn() ?: '');
    if (!empty($payload['emit'])) {
        $tenantId = (string)app()->tenant()->current();
        $pdo = app()->db();
        $pdo->beginTransaction();
        try {
            $rowId = app()->events()->fireDurable('golden.lifecycle.proved', [
                'module' => '__MODULE_ID__',
                'db_name' => $dbName,
                'spoof_payload' => [
                    'caller_module' => $payload['caller_module'] ?? null,
                    'caller_user' => $payload['caller_user'] ?? null,
                ],
            ], $pdo, [
                'tenant_id' => $tenantId,
                'source' => '__MODULE_ID__',
                'event_id' => (string)($payload['event_id'] ?? ''),
                'idempotency_key' => (string)($payload['idempotency_key'] ?? ''),
                'request_id' => (string)($ctx['request_id'] ?? ''),
                'actor_id' => isset($ctx['user']['id']) ? (string)$ctx['user']['id'] : null,
                'actor_role' => (string)($ctx['user']['role'] ?? ''),
            ]);
            $pdo->commit();
        } catch (Throwable $e) {
            if ($pdo->inTransaction()) {
                $pdo->rollBack();
            }
            throw $e;
        }
    } else {
        $rowId = null;
    }
    return [
        'ok' => true,
        'module' => '__MODULE_ID__',
        'db_name' => $dbName,
        'tenant_id' => app()->tenant()->current(),
        'caller' => [
            'module' => (string)($ctx['module'] ?? ''),
            'user' => is_array($ctx['user'] ?? null) ? $ctx['user'] : null,
            'request_id' => (string)($ctx['request_id'] ?? ''),
        ],
        'durable_row_id' => $rowId,
    ];
}

function __PREFIX___cap_entity_list_golden_entity_1(mixed $payload, string $capabilityId = '', string $providerId = ''): array
{
    __PREFIX___assert_tenant_and_role('admin');
    $rows = __PREFIX___db()->query('SELECT id, title, status, db_name FROM __TABLE__ ORDER BY id ASC')->fetchAll(PDO::FETCH_ASSOC) ?: [];
    return ['rows' => $rows, 'total' => count($rows)];
}

function __PREFIX___cap_entity_get_golden_entity_1(mixed $payload, string $capabilityId = '', string $providerId = ''): array
{
    __PREFIX___assert_tenant_and_role('admin');
    $payload = is_array($payload) ? $payload : [];
    $stmt = __PREFIX___db()->prepare('SELECT id, title, status, db_name FROM __TABLE__ WHERE id = ? LIMIT 1');
    $stmt->execute([(int)($payload['id'] ?? 0)]);
    return $stmt->fetch(PDO::FETCH_ASSOC) ?: [];
}

function __PREFIX___require_context_db_name(): string
{
    $ctx = module();
    if (!$ctx) {
        throw new RuntimeException('fail_closed: module context missing');
    }
    return (string)($ctx->db()->query('SELECT DATABASE()')->fetchColumn() ?: '');
}
PHP;
    $helpers = str_replace(['__PREFIX__', '__MODULE_ID__', '__TABLE__'], [$prefix, $moduleId, $table], $helpers);

    $migration = "CREATE TABLE IF NOT EXISTS `{$table}` (\n"
        . "  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,\n"
        . "  `title` VARCHAR(190) NOT NULL,\n"
        . "  `status` VARCHAR(32) NOT NULL DEFAULT 'active',\n"
        . "  `db_name` VARCHAR(190) NOT NULL,\n"
        . "  PRIMARY KEY (`id`)\n"
        . ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;\n"
        . "INSERT INTO `{$table}` (`title`, `status`, `db_name`) VALUES ('Golden Entity', 'active', DATABASE());\n";

    file_put_contents($moduleDir . '/module.json', json_encode($manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n");
    file_put_contents($moduleDir . '/helpers.php', $helpers);
    @mkdir($moduleDir . '/database/migrations', 0775, true);
    file_put_contents($moduleDir . '/database/migrations/001_golden.sql', $migration);
    if (!is_dir($templateDir . '/pages')) {
        @mkdir($templateDir . '/pages', 0775, true);
    }

    $hostDir = $shadowRoot . '/modules/' . $hostModuleId;
    @mkdir($hostDir, 0775, true);
    $hostManifest = [
        'id' => $hostModuleId,
        'name' => 'Golden Cleanroom Host Module',
        'version' => '1.0.0',
        'description' => 'Shadow-only coordinator host for the golden module',
        'author' => 'Ikabud',
        'entry_module' => true,
        'depends' => [$moduleId],
        'owns_tables' => [],
        'reads_tables' => [],
        'migrations' => [],
        'capabilities' => ['exposes' => [], 'depends' => []],
        'routes' => true,
        'events' => [],
        'nav' => [],
    ];
    file_put_contents($hostDir . '/module.json', json_encode($hostManifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n");
    file_put_contents($hostDir . '/helpers.php', "<?php\ndeclare(strict_types=1);\n");
    file_put_contents($hostDir . '/routes.php', "<?php\nreturn ['GET' => [], 'POST' => [], 'PUT' => [], 'PATCH' => [], 'DELETE' => []];\n");
    file_put_contents($hostDir . '/handlers.php', "<?php\ndeclare(strict_types=1);\n");

    $failPrefix = str_replace('-', '_', $failModuleId);
    $failTable = $failPrefix . '_records';
    $failDir = $shadowRoot . '/modules/' . $failModuleId;
    @mkdir($failDir . '/database/migrations', 0775, true);
    $failManifest = [
        'id' => $failModuleId,
        'name' => 'Golden Failed Install Fixture',
        'version' => '1.0.0',
        'description' => 'Shadow-only failed provision fixture',
        'author' => 'Ikabud',
        'entry_module' => true,
        'owns_tables' => [$failTable],
        'reads_tables' => [],
        'migrations' => ['database/migrations/001_fail.sql'],
        'capabilities' => ['exposes' => [], 'depends' => []],
        'routes' => true,
        'events' => [],
        'nav' => [],
    ];
    file_put_contents($failDir . '/module.json', json_encode($failManifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n");
    file_put_contents($failDir . '/helpers.php', "<?php\ndeclare(strict_types=1);\n");
    file_put_contents($failDir . '/routes.php', "<?php\nreturn ['GET' => [], 'POST' => [], 'PUT' => [], 'PATCH' => [], 'DELETE' => []];\n");
    file_put_contents($failDir . '/handlers.php', "<?php\ndeclare(strict_types=1);\n");
    file_put_contents($failDir . '/database/migrations/001_fail.sql', "THIS IS INVALID SQL;\n");

}

function poc6l_write_shadow_env(string $repoRoot, string $shadowRoot): void
{
    $lines = [];
    $sourceEnv = $repoRoot . '/.env';
    if (is_file($sourceEnv)) {
        $raw = (string)file_get_contents($sourceEnv);
        if ($raw !== '') {
            $lines[] = rtrim($raw, "\n");
        }
    } else {
        foreach (['DB_HOST', 'DB_PORT', 'DB_DATABASE', 'DB_USERNAME', 'DB_PASSWORD', 'DB_COLLATION', 'CONTROL_DB_ENC_KEY', 'APP_ENCRYPTION_KEY'] as $key) {
            $value = getenv($key);
            if ($value !== false) {
                $lines[] = $key . '=' . $value;
            }
        }
    }
    $lines[] = 'APP_MULTI_TENANT_ENABLED=1';
    $lines[] = 'APP_TENANT_STRATEGY=control_host';
    file_put_contents($shadowRoot . '/.env', implode("\n", array_filter($lines, static fn($v): bool => $v !== '')) . "\n");
}

function poc6l_inner_probe_source(): string
{
    return <<<'PHP'
<?php

declare(strict_types=1);

$_SERVER['HTTP_HOST'] = $_SERVER['HTTP_HOST'] ?? 'localhost';
$_SERVER['REQUEST_URI'] = $_SERVER['REQUEST_URI'] ?? '/';

use Ikabud\Kernel\Services\TenantProvisioner;

require __DIR__ . '/../bootstrap.php';
require_once __DIR__ . '/../src/helpers/module-manager.php';
require_once __DIR__ . '/../src/helpers/module-migrations.php';
require_once __DIR__ . '/../src/helpers/module-registry.php';
require_once __DIR__ . '/../src/helpers/durable-event-outbox.php';
require_once __DIR__ . '/../kernel/Services/TenantProvisioner.php';

$phase = $argv[1] ?? 'all';
$moduleId = $argv[2] ?? '';
$failModuleId = $argv[3] ?? '';
$hostModuleId = $argv[4] ?? '';
$statePath = $argv[5] ?? (__DIR__ . '/../storage/poc6-lifecycle-state.json');

function p6i_base_routes(): array { return ['GET' => [], 'POST' => [], 'PUT' => [], 'PATCH' => [], 'DELETE' => []]; }
function p6i_result(array $steps = [], array $state = [], bool $ok = true, array $extra = []): array { return $extra + ['ok' => $ok, 'steps' => $steps, 'state' => $state]; }
function p6i_add(array &$steps, string $name, bool $passed, array $evidence = []): void { $steps[] = ['name' => $name, 'passed' => $passed, 'evidence' => $evidence]; }
function p6i_db_conf(): array { return require __DIR__ . '/../config/database.php'; }
function p6i_root_pdo(): PDO {
    $db = p6i_db_conf();
    $dsn = 'mysql:host=' . ($db['host'] ?? '127.0.0.1') . ';port=' . ($db['port'] ?? '3306') . ';charset=' . ($db['charset'] ?? 'utf8mb4');
    return new PDO($dsn, (string)($db['username'] ?? ''), (string)($db['password'] ?? ''), [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
}
function p6i_safe_db(string $db): string { return preg_replace('/[^A-Za-z0-9_]/', '', $db) ?: $db; }
function p6i_create_db(PDO $root, string $db): void {
    $db = p6i_safe_db($db);
    $root->exec('DROP DATABASE IF EXISTS `' . $db . '`');
    $root->exec('CREATE DATABASE `' . $db . '` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');
}
function p6i_create_tenant(PDO $controlDb, string $tenantKey, string $entryModuleId, string $dbName): int {
    $db = p6i_db_conf();
    $stmt = $controlDb->prepare('INSERT INTO kernel_tenants (tenant_key, status, entry_module_id) VALUES (:k, :s, :e)');
    $stmt->execute([':k' => $tenantKey, ':s' => 'pending', ':e' => $entryModuleId]);
    $tenantId = (int)$controlDb->lastInsertId();
    $conn = $controlDb->prepare('INSERT INTO kernel_tenant_db_connections (tenant_id, db_driver, db_host, db_port, db_name, db_user, db_pass, db_charset, db_pass_ciphertext, db_pass_iv, db_pass_tag) VALUES (:tid, :drv, :host, :port, :name, :user, :pass, :charset, :cipher, :iv, :tag)');
    $conn->execute([
        ':tid' => $tenantId, ':drv' => 'mysql', ':host' => (string)($db['host'] ?? '127.0.0.1'), ':port' => (string)($db['port'] ?? '3306'),
        ':name' => $dbName, ':user' => (string)($db['username'] ?? ''), ':pass' => (string)($db['password'] ?? ''), ':charset' => (string)($db['charset'] ?? 'utf8mb4'),
        ':cipher' => '', ':iv' => '', ':tag' => '',
    ]);
    return $tenantId;
}
function p6i_drop_tenant(PDO $controlDb, PDO $root, ?int $tenantId, ?string $dbName): void {
    if (is_string($dbName) && $dbName !== '') {
        try { $root->exec('DROP DATABASE IF EXISTS `' . p6i_safe_db($dbName) . '`'); } catch (Throwable $e) {}
    }
    if ($tenantId) {
        try { $controlDb->prepare('DELETE FROM kernel_tenant_db_connections WHERE tenant_id = :tid')->execute([':tid' => $tenantId]); } catch (Throwable $e) {}
        try { $controlDb->prepare('DELETE FROM kernel_tenants WHERE id = :tid')->execute([':tid' => $tenantId]); } catch (Throwable $e) {}
    }
}
function p6i_state_read(string $path): array { return is_file($path) ? (json_decode((string)file_get_contents($path), true) ?: []) : []; }
function p6i_state_write(string $path, array $state): void { file_put_contents($path, json_encode($state, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n"); }
function p6i_table_exists(PDO $pdo, string $table): bool { try { return (bool)$pdo->query("SHOW TABLES LIKE '" . str_replace("'", "''", $table) . "'")->fetchColumn(); } catch (Throwable $e) { return false; } }
function p6i_status(PDO $controlDb, int $tenantId): string { $s = $controlDb->prepare('SELECT status FROM kernel_tenants WHERE id = :id LIMIT 1'); $s->execute([':id' => $tenantId]); return (string)($s->fetchColumn() ?: ''); }
function p6i_enabled(PDO $tenantDb, int $tenantId, string $moduleId): ?bool {
    try {
        $stmt = $tenantDb->prepare('SELECT setting_value FROM tenant_module_settings WHERE tenant_id = :tid AND module_id = :mid AND setting_key = :key LIMIT 1');
        $stmt->execute([':tid' => $tenantId, ':mid' => $moduleId, ':key' => '_module_enabled']);
        $raw = $stmt->fetchColumn();
        if ($raw === false) return null;
        $decoded = json_decode((string)$raw, true);
        return is_bool($decoded) ? $decoded : null;
    } catch (Throwable $e) { return null; }
}
function p6i_delete_path(string $path): void {
    if ($path === '') { return; }
    if (is_link($path) || is_file($path)) { @unlink($path); return; }
    if (!is_dir($path)) { return; }
    $it = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($path, FilesystemIterator::SKIP_DOTS), RecursiveIteratorIterator::CHILD_FIRST);
    foreach ($it as $entry) {
        if ($entry->isDir() && !$entry->isLink()) { @rmdir($entry->getPathname()); } else { @unlink($entry->getPathname()); }
    }
    @rmdir($path);
}
function p6i_fresh_load(int $tenantId, ?array $user = null): void {
    $_SERVER['HTTP_HOST'] = $_SERVER['HTTP_HOST'] ?? 'localhost';
    app()->tenant()->setTenantId($tenantId);
    app()->setUser($user ?? []);
    app()->entityViews()->reset();
    unset($GLOBALS['_kernel_discovered_modules']);
    loadModuleRoutes(p6i_base_routes());
}
function p6i_run_subprocess(array $args): array {
    $cmd = array_merge([PHP_BINARY, __FILE__], $args);
    $proc = proc_open($cmd, [0 => ['pipe', 'r'], 1 => ['pipe', 'w'], 2 => ['pipe', 'w']], $pipes, dirname(__DIR__));
    if (!is_resource($proc)) { throw new RuntimeException('subprocess start failed'); }
    fclose($pipes[0]);
    $stdout = stream_get_contents($pipes[1]);
    $stderr = stream_get_contents($pipes[2]);
    fclose($pipes[1]); fclose($pipes[2]);
    $code = proc_close($proc);
    $json = json_decode(trim((string)$stdout), true);
    if (!is_array($json)) { $json = ['ok' => false, 'steps' => [['name' => 'subprocess.' . ($args[0] ?? 'unknown'), 'passed' => false, 'evidence' => ['stdout' => $stdout, 'stderr' => $stderr, 'exit_code' => $code]]]]; }
    $json['_exit_code'] = $code; $json['_stdout'] = $stdout; $json['_stderr'] = $stderr;
    return $json;
}

try {
    if ($phase === 'init') {
        $steps = [];
        $controlDb = app()->controlDb();
        $root = p6i_root_pdo();
        $seed = substr(hash('sha256', $moduleId . '|' . $failModuleId . '|' . getmypid()), 0, 8);
        $goodDb = 'p6_life_' . $seed;
        $badDb = 'p6_fail_' . $seed;
        $goodKey = 'p6-life-' . $seed;
        $badKey = 'p6-fail-' . $seed;
        p6i_create_db($root, $goodDb);
        p6i_create_db($root, $badDb);
        $goodTenantId = p6i_create_tenant($controlDb, $goodKey, $hostModuleId !== '' ? $hostModuleId : $moduleId, $goodDb);
        $badTenantId = p6i_create_tenant($controlDb, $badKey, $failModuleId, $badDb);
        $provisioner = new TenantProvisioner($controlDb);
        $provision = $provisioner->provision($goodTenantId, ['skip_db_create' => true]);
        $tenantDb = app()->dbForTenant($goodTenantId);
        $goodStatus = p6i_status($controlDb, $goodTenantId);
        p6i_add($steps, 'shadow_disposable_tenant_provisioned_via_coordinator', !empty($provision['ok']) && $tenantDb instanceof PDO && $goodStatus === 'active', [
            'tenant_id' => $goodTenantId, 'tenant_key' => $goodKey, 'db_name' => $goodDb, 'status' => $goodStatus, 'provision' => $provision,
        ]);
        $state = [
            'good' => ['tenant_id' => $goodTenantId, 'tenant_key' => $goodKey, 'db_name' => $goodDb],
            'bad' => ['tenant_id' => $badTenantId, 'tenant_key' => $badKey, 'db_name' => $badDb],
            'module_id' => $moduleId, 'host_module_id' => $hostModuleId, 'fail_module_id' => $failModuleId,
        ];
        p6i_state_write($statePath, $state);
        echo json_encode(p6i_result($steps, $state, true), JSON_UNESCAPED_SLASHES) . "\n";
        exit(0);
    }

    if ($phase === 'cleanup') {
        $state = p6i_state_read($statePath);
        $controlDb = app()->controlDb();
        $root = p6i_root_pdo();
        p6i_drop_tenant($controlDb, $root, (int)($state['good']['tenant_id'] ?? 0), (string)($state['good']['db_name'] ?? ''));
        p6i_drop_tenant($controlDb, $root, (int)($state['bad']['tenant_id'] ?? 0), (string)($state['bad']['db_name'] ?? ''));
        @unlink($statePath);
        echo json_encode(['ok' => true, 'steps' => [['name' => 'cleanup_disposable_tenants', 'passed' => true, 'evidence' => $state]]], JSON_UNESCAPED_SLASHES) . "\n";
        exit(0);
    }

    if ($phase === 'runtime') {
        $state = p6i_state_read($statePath);
        $steps = [];
        $tenantId = (int)($state['good']['tenant_id'] ?? 0);
        $dbName = (string)($state['good']['db_name'] ?? '');
        $moduleId = (string)($state['module_id'] ?? $moduleId);
        $prefix = str_replace('-', '_', $moduleId);
        $table = $prefix . '_records';
        $admin = ['id' => 9001, 'role' => 'admin', 'source' => $moduleId];
        p6i_fresh_load($tenantId, $admin);
        $tenantDb = app()->db();
        $dbEvidence = moduleWithContext($moduleId, static function () use ($table): array {
            $db = module()->db();
            return [
                'db_name' => (string)($db->query('SELECT DATABASE()')->fetchColumn() ?: ''),
                'row_count' => (int)($db->query('SELECT COUNT(*) FROM `' . $table . '`')->fetchColumn() ?: 0),
            ];
        });
        p6i_add($steps, 'tenant_bound_db_access_and_owned_table', $dbEvidence['db_name'] === $dbName && $dbEvidence['row_count'] >= 1, $dbEvidence);

        $cap = app()->cap()->call('golden_cap.ping@1', ['caller_module' => 'payload-spoof', 'caller_user' => ['id' => 1, 'role' => 'spoof']], []);
        $capOk = is_array($cap) && !empty($cap['ok']) && ($cap['caller']['module'] ?? '') === 'kernel' && (($cap['caller']['user']['role'] ?? '') === 'admin');
        p6i_add($steps, 'authorized_capability_executes_and_payload_spoof_is_ignored', $capOk, ['result' => $cap]);

        $deniedRole = false;
        $deniedRoleEvidence = [];
        try {
            p6i_fresh_load($tenantId, ['id' => 9002, 'role' => 'viewer', 'source' => $moduleId]);
            $deniedRoleResult = app()->cap()->call('golden_cap.ping@1', [], []);
            $deniedRole = !is_array($deniedRoleResult) || empty($deniedRoleResult['ok']);
            $deniedRoleEvidence = ['result' => $deniedRoleResult];
        } catch (Throwable $e) {
            $deniedRole = str_contains($e->getMessage(), 'default_deny') || str_contains($e->getMessage(), 'Capability call failed');
            $deniedRoleEvidence = ['error' => $e->getMessage()];
        }
        p6i_add($steps, 'capability_default_deny_for_unknown_role', $deniedRole, $deniedRoleEvidence + ['tenant_id' => $tenantId]);

        $deniedMissingTenant = false;
        try { app()->tenant()->reset(); p6i_fresh_load($tenantId, ['id' => 9003, 'role' => 'admin', 'source' => $moduleId]); app()->tenant()->reset(); app()->cap()->call('golden_cap.ping@1', [], []); } catch (Throwable $e) { $deniedMissingTenant = str_contains($e->getMessage(), 'tenant context required') || str_contains($e->getMessage(), 'Capability call failed'); }
        p6i_add($steps, 'capability_rejects_missing_tenant_context', $deniedMissingTenant, []);

        p6i_fresh_load($tenantId, $admin);
        $view = app()->entityViews()->resolve('golden_entity', 'compact');
        $viewOk = is_array($view) && ($view['error'] ?? null) === null && !empty($view['rows'][0]['title']);
        p6i_add($steps, 'entity_view_renders_authorized_output', $viewOk, ['view' => $view]);

        $tenantDb->exec(durableEventOutboxDdl());
        $eventId = durableEventOutboxUuidV4();
        $idem = 'idem-' . substr(hash('sha256', $eventId), 0, 12);
        $tenantDb->beginTransaction();
        try {
            $rowId = app()->events()->fireDurable('golden.lifecycle.proved', ['module' => $moduleId], $tenantDb, [
                'tenant_id' => (string)$tenantId,
                'source' => $moduleId,
                'event_id' => $eventId,
                'idempotency_key' => $idem,
            ]);
            $tenantDb->commit();
        } catch (Throwable $e) {
            if ($tenantDb->inTransaction()) { $tenantDb->rollBack(); }
            throw $e;
        }
        $row = durableEventOutboxFind($tenantDb, (string)$tenantId, $eventId);
        $duplicateRejected = false;
        try {
            $tenantDb->beginTransaction();
            try {
                app()->events()->fireDurable('golden.lifecycle.proved', ['module' => $moduleId], $tenantDb, [
                    'tenant_id' => (string)$tenantId,
                    'source' => $moduleId,
                    'event_id' => $eventId,
                    'idempotency_key' => $idem,
                ]);
                $tenantDb->commit();
            } catch (Throwable $e) {
                if ($tenantDb->inTransaction()) { $tenantDb->rollBack(); }
                throw $e;
            }
        } catch (Throwable $e) { $duplicateRejected = true; }
        $countStmt = $tenantDb->prepare('SELECT COUNT(*) FROM kernel_durable_event_outbox WHERE tenant_id = :tid AND idempotency_key = :ikey');
        $countStmt->execute([':tid' => (string)$tenantId, ':ikey' => $idem]);
        $rowCount = (int)($countStmt->fetchColumn() ?: 0);
        p6i_add($steps, 'durable_event_written_once_to_tenant_outbox', is_int($rowId) && $rowId > 0 && is_array($row) && ($row['source'] ?? '') === $moduleId && $rowCount === 1 && $duplicateRejected, ['row' => $row, 'count' => $rowCount, 'row_id' => $rowId]);

        $controlRejected = false;
        try { moduleWithContext($moduleId, static function (): void { module()->db()->query('SELECT * FROM kernel_tenants LIMIT 1'); }); } catch (Throwable $e) { $controlRejected = true; }
        p6i_add($steps, 'forbidden_control_table_access_rejected', $controlRejected, []);

        $dbConf = p6i_db_conf();
        $baseReject = tenantRejectBaseDbConnection(['driver' => (string)($dbConf['driver'] ?? 'mysql'), 'host' => (string)($dbConf['host'] ?? '127.0.0.1'), 'port' => (string)($dbConf['port'] ?? '3306'), 'db_name' => (string)($dbConf['database'] ?? '')]);
        p6i_add($steps, 'forbidden_base_db_connection_rejected', empty($baseReject['ok']), $baseReject);

        $otherRejected = false;
        try { moduleWithContext($moduleId, static function (): void { module()->db()->query('SELECT * FROM cms_posts LIMIT 1'); }); } catch (Throwable $e) { $otherRejected = true; }
        p6i_add($steps, 'forbidden_other_module_table_access_rejected', $otherRejected, []);

        $contextRejected = false;
        try { $fn = str_replace('-', '_', $moduleId) . '_require_context_db_name'; $fn(); } catch (Throwable $e) { $contextRejected = str_contains($e->getMessage(), 'fail_closed'); }
        p6i_add($steps, 'forbidden_missing_module_context_rejected', $contextRejected, []);

        $spoofResult = app()->cap()->call('golden_cap.ping@1', ['caller_module' => 'spoofed', 'caller_user' => ['id' => 404, 'role' => 'spoof']], []);
        $spoofOk = is_array($spoofResult) && ($spoofResult['caller']['module'] ?? '') === 'kernel' && (($spoofResult['caller']['user']['id'] ?? 0) === 9001);
        p6i_add($steps, 'forbidden_caller_spoof_via_payload_rejected', $spoofOk, ['result' => $spoofResult]);

        echo json_encode(p6i_result($steps, $state, true), JSON_UNESCAPED_SLASHES) . "\n";
        exit(0);
    }

    if ($phase === 'disable') {
        $state = p6i_state_read($statePath); $steps = [];
        $tenantId = (int)($state['good']['tenant_id'] ?? 0); $moduleId = (string)($state['module_id'] ?? $moduleId);
        app()->tenant()->setTenantId($tenantId); disableModule($moduleId);
        unset($GLOBALS['_kernel_discovered_modules']);
        $tenantDb = app()->dbForTenant($tenantId);
        $enabled = $tenantDb instanceof PDO ? p6i_enabled($tenantDb, $tenantId, $moduleId) : null;
        p6i_fresh_load($tenantId, ['id' => 9004, 'role' => 'admin', 'source' => $moduleId]);
        $capUnavailable = false;
        try { app()->cap()->call('golden_cap.ping@1', [], []); } catch (Throwable $e) { $capUnavailable = true; }
        $contract = app()->entityViews()->viewContract('golden_entity', 'compact');
        $viewFallback = is_array($contract) && (($contract['fields'] ?? null) === '*');
        p6i_add($steps, 'disable_module_deactivates_capability_and_entity_view', $enabled === false && $capUnavailable && $viewFallback, ['enabled' => $enabled, 'contract' => $contract]);
        echo json_encode(p6i_result($steps, $state, true), JSON_UNESCAPED_SLASHES) . "\n"; exit(0);
    }

    if ($phase === 'enable') {
        $state = p6i_state_read($statePath); $steps = [];
        $tenantId = (int)($state['good']['tenant_id'] ?? 0); $moduleId = (string)($state['module_id'] ?? $moduleId);
        app()->tenant()->setTenantId($tenantId); enableModule($moduleId);
        unset($GLOBALS['_kernel_discovered_modules']);
        $tenantDb = app()->dbForTenant($tenantId);
        $enabled = $tenantDb instanceof PDO ? p6i_enabled($tenantDb, $tenantId, $moduleId) : null;
        p6i_fresh_load($tenantId, ['id' => 9005, 'role' => 'admin', 'source' => $moduleId]);
        $cap = app()->cap()->call('golden_cap.ping@1', [], []);
        $view = app()->entityViews()->resolve('golden_entity', 'compact');
        p6i_add($steps, 'enable_module_restores_capability_and_entity_view', $enabled === true && !empty($cap['ok']) && ($view['error'] ?? null) === null, ['enabled' => $enabled, 'cap' => $cap, 'view' => $view]);
        echo json_encode(p6i_result($steps, $state, true), JSON_UNESCAPED_SLASHES) . "\n"; exit(0);
    }

    if ($phase === 'lifecycle') {
        $state = p6i_state_read($statePath); $steps = [];
        $tenantId = (int)($state['good']['tenant_id'] ?? 0); $moduleId = (string)($state['module_id'] ?? $moduleId);
        $table = str_replace('-', '_', $moduleId) . '_records';
        app()->tenant()->setTenantId($tenantId);
        $zipPath = __DIR__ . '/../storage/' . $moduleId . '.zip';
        $pack = p6i_run_subprocess(['cli-pack', $moduleId, '__noop__', '__noop__', $zipPath]);
        $moduleDir = modulePathForId($moduleId) ?? (__DIR__ . '/../modules/' . $moduleId);
        $templateDir = __DIR__ . '/../templates/modules/' . $moduleId;
        p6i_delete_path($moduleDir);
        p6i_delete_path($templateDir);
        unset($GLOBALS['_kernel_discovered_modules']);
        $install = installModuleFromZip($zipPath);
        $tenantDb = app()->dbForTenant($tenantId);
        $installed = !empty($install['ok']) && is_dir($moduleDir);
        $retain = uninstallModule($moduleId, []);
        $retainTable = $tenantDb instanceof PDO ? p6i_table_exists($tenantDb, $table) : false;
        $retainLedger = $tenantDb instanceof PDO ? (int)($tenantDb->query("SELECT COUNT(*) FROM _migrations WHERE module = " . $tenantDb->quote($moduleId))->fetchColumn() ?: 0) : 0;
        p6i_add($steps, 'package_pack_install_uninstall_retain_data', $installed && !empty($retain['ok']) && $retainTable && $retainLedger > 0, ['install' => $install, 'retain' => $retain, 'table_exists' => $retainTable, 'ledger_rows' => $retainLedger]);
        $reinstall = installModuleFromZip($zipPath);
        $purge = uninstallModule($moduleId, ['purge' => true, 'confirm_purge' => true]);
        $purgeTable = $tenantDb instanceof PDO ? p6i_table_exists($tenantDb, $table) : true;
        $purgeLedger = $tenantDb instanceof PDO ? (int)($tenantDb->query("SELECT COUNT(*) FROM _migrations WHERE module = " . $tenantDb->quote($moduleId))->fetchColumn() ?: 0) : 1;
        p6i_add($steps, 'package_reinstall_uninstall_purge_data', !empty($reinstall['ok']) && !empty($purge['ok']) && !$purgeTable && $purgeLedger === 0, ['reinstall' => $reinstall, 'purge' => $purge, 'table_exists' => $purgeTable, 'ledger_rows' => $purgeLedger]);
        echo json_encode(p6i_result($steps, $state, true), JSON_UNESCAPED_SLASHES) . "\n"; exit(0);
    }

    if ($phase === 'cli-pack') {
        $zipPath = $argv[5] ?? '';
        $proc = proc_open([PHP_BINARY, __DIR__ . '/../ikabud', 'module:pack', $moduleId, $zipPath], [0 => ['pipe', 'r'], 1 => ['pipe', 'w'], 2 => ['pipe', 'w']], $pipes, dirname(__DIR__));
        if (!is_resource($proc)) { throw new RuntimeException('pack failed to start'); }
        fclose($pipes[0]); $stdout = stream_get_contents($pipes[1]); $stderr = stream_get_contents($pipes[2]); fclose($pipes[1]); fclose($pipes[2]); $code = proc_close($proc);
        echo json_encode(['ok' => $code === 0 && is_file($zipPath), 'stdout' => $stdout, 'stderr' => $stderr, 'zip' => $zipPath], JSON_UNESCAPED_SLASHES) . "\n"; exit($code === 0 ? 0 : 1);
    }

    if ($phase === 'failed') {
        $state = p6i_state_read($statePath); $steps = [];
        $controlDb = app()->controlDb();
        $badTenantId = (int)($state['bad']['tenant_id'] ?? 0); $failModuleId = (string)($state['fail_module_id'] ?? $failModuleId);
        $provisioner = new TenantProvisioner($controlDb);
        $provision = $provisioner->provision($badTenantId, ['skip_db_create' => true]);
        $status = p6i_status($controlDb, $badTenantId);
        $tenantDb = app()->dbForTenant($badTenantId);
        $enabled = $tenantDb instanceof PDO ? p6i_enabled($tenantDb, $badTenantId, $failModuleId) : null;
        $report = 'best-effort compensation only; non-atomic without disposable DB snapshot';
        p6i_add($steps, 'failed_install_restoration_reports_best_effort_non_atomic', empty($provision['ok']) && $status !== 'active' && $enabled !== true, ['status' => $status, 'module_enabled' => $enabled, 'provision' => $provision, 'restoration_report' => $report]);
        echo json_encode(p6i_result($steps, $state, true), JSON_UNESCAPED_SLASHES) . "\n"; exit(0);
    }

    if ($phase === 'all') {
        $aggregate = []; $state = [];
        $phases = ['init', 'runtime', 'disable', 'enable', 'lifecycle', 'failed'];
        try {
            foreach ($phases as $sub) {
                $result = p6i_run_subprocess([$sub, $moduleId, $failModuleId, $hostModuleId, $statePath]);
                $state = is_array($result['state'] ?? null) ? $result['state'] : $state;
                foreach ((array)($result['steps'] ?? []) as $step) { $aggregate[] = $step; }
                if (($result['_exit_code'] ?? 1) !== 0) {
                    echo json_encode(['ok' => false, 'steps' => $aggregate, 'state' => $state], JSON_UNESCAPED_SLASHES) . "\n";
                    exit(1);
                }
            }
        } finally {
            p6i_run_subprocess(['cleanup', $moduleId, $failModuleId, $hostModuleId, $statePath]);
        }
        echo json_encode(['ok' => true, 'steps' => $aggregate, 'state' => $state], JSON_UNESCAPED_SLASHES) . "\n";
        exit(0);
    }

    throw new RuntimeException('Unknown phase: ' . $phase);
} catch (Throwable $e) {
    echo json_encode(['ok' => false, 'steps' => [['name' => 'phase.' . $phase, 'passed' => false, 'evidence' => ['error' => $e->getMessage()]]]], JSON_UNESCAPED_SLASHES) . "\n";
    exit(1);
}
PHP;
}

function poc6l_main(): int
{
    $repoRoot = poc6_repo_root();
    $artifactDir = $repoRoot . '/storage/poc6';
    $statusDocPath = $repoRoot . '/docs/poc6-lifecycle-status.md';
    $allowedRepoWrites = [$artifactDir, dirname($statusDocPath)];
    $shadow = null;

    try {
        $shadow = poc6l_build_shadow();
        $moduleSeed = substr(hash('sha256', $shadow['head_sha'] . '|lifecycle'), 0, 8);
        $moduleId = 'golden-cleanroom-life-' . $moduleSeed;
        $failModuleId = 'golden-cleanroom-fail-' . $moduleSeed;
        $shadowRoot = $shadow['shadow_root'];

        $steps = [];
        $make = poc6_run([PHP_BINARY, 'ikabud', 'make:module', $moduleId], $shadowRoot);
        $steps[] = ['name' => 'shadow_make_module', 'passed' => $make['exit_code'] === 0, 'evidence' => ['output' => $make['output']]];
        if ($make['exit_code'] !== 0) {
            throw new RuntimeException('make:module failed: ' . $make['output']);
        }

        $guard = poc6_run([PHP_BINARY, 'scripts/guard-module-manifests.php', '--strict'], $shadowRoot);
        $steps[] = ['name' => 'shadow_guard_module_manifests_scaffold', 'passed' => $guard['exit_code'] === 0, 'evidence' => ['output' => $guard['output']]];
        if ($guard['exit_code'] !== 0) {
            throw new RuntimeException('guard-module-manifests failed: ' . $guard['output']);
        }

        $cert = poc6_run([PHP_BINARY, 'ikabud', 'module:certify', $moduleId], $shadowRoot);
        $steps[] = ['name' => 'shadow_module_certify_scaffold', 'passed' => $cert['exit_code'] === 0, 'evidence' => ['output' => $cert['output']]];
        if ($cert['exit_code'] !== 0) {
            throw new RuntimeException('module:certify failed: ' . $cert['output']);
        }

        $hostModuleId = 'golden-cleanroom-host-' . $moduleSeed;
        poc6l_enrich_shadow($shadowRoot, $moduleId, $hostModuleId, $failModuleId);
        poc6l_write_shadow_env($shadow['repo_root'], $shadowRoot);

        $guardEnriched = poc6_run([PHP_BINARY, 'scripts/guard-module-manifests.php', '--strict'], $shadowRoot);
        $steps[] = ['name' => 'shadow_guard_module_manifests_enriched', 'passed' => $guardEnriched['exit_code'] === 0, 'evidence' => ['output' => $guardEnriched['output']]];
        if ($guardEnriched['exit_code'] !== 0) {
            throw new RuntimeException('guard-module-manifests failed after enrichment: ' . $guardEnriched['output']);
        }

        $probePath = $shadowRoot . '/storage/poc6-lifecycle-inner.php';
        file_put_contents($probePath, poc6l_inner_probe_source());
        $probe = poc6_run([PHP_BINARY, $probePath, 'all', $moduleId, $failModuleId, $hostModuleId, $shadowRoot . '/storage/poc6-lifecycle-state.json'], $shadowRoot);
        $probeResult = json_decode(trim($probe['stdout']), true);
        if ($probe['exit_code'] !== 0 || !is_array($probeResult)) {
            throw new RuntimeException('inner lifecycle probe failed: ' . $probe['output']);
        }

        foreach ((array)($probeResult['steps'] ?? []) as $step) {
            $steps[] = [
                'name' => (string)($step['name'] ?? 'unnamed'),
                'passed' => !empty($step['passed']),
                'evidence' => $step['evidence'] ?? [],
            ];
        }

        $allPassed = true;
        foreach ($steps as $step) {
            if (empty($step['passed'])) {
                $allPassed = false;
                break;
            }
        }

        poc6_mkdir($artifactDir, $repoRoot, $allowedRepoWrites);
        $artifactPath = $artifactDir . '/proof-lifecycle-' . $shadow['short_head'] . '.json';
        $state = is_array($probeResult['state'] ?? null) ? $probeResult['state'] : [];
        $artifact = [
            'fingerprint' => [
                'head_sha' => $shadow['head_sha'],
                'dirty' => $shadow['dirty'],
                'captured_count' => count($shadow['captured_files']),
                'included' => $shadow['captured_files'],
                'modified_tracked_overlays' => $shadow['modified_tracked'],
                'captured_hashes' => $shadow['captured_hashes'],
            ],
            'module_id' => $moduleId,
            'disposable_tenant' => [
                'tenant_id' => $state['good']['tenant_id'] ?? null,
                'tenant_key' => $state['good']['tenant_key'] ?? null,
                'db_name' => $state['good']['db_name'] ?? null,
                'failed_tenant_id' => $state['bad']['tenant_id'] ?? null,
                'failed_tenant_key' => $state['bad']['tenant_key'] ?? null,
                'failed_db_name' => $state['bad']['db_name'] ?? null,
            ],
            'steps' => $steps,
            'artifact_path' => 'storage/poc6/' . basename($artifactPath),
            'verdict' => $allPassed ? 'PASS' : 'FAIL',
        ];

        poc6_write_file($artifactPath, json_encode($artifact, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n", $repoRoot, $allowedRepoWrites);
        poc6_write_file($statusDocPath, poc6l_render_status_doc($artifact), $repoRoot, $allowedRepoWrites);

        echo 'POC6 lifecycle proof: ' . $artifact['verdict'] . ' | module=' . $moduleId . ' | artifact=' . $artifact['artifact_path'] . PHP_EOL;
        foreach ($steps as $step) {
            echo '- ' . $step['name'] . ': ' . (!empty($step['passed']) ? 'PASS' : 'FAIL') . PHP_EOL;
        }

        return $allPassed ? 0 : 1;
    } catch (Throwable $e) {
        fwrite(STDERR, 'POC6 lifecycle proof: FAIL - ' . $e->getMessage() . PHP_EOL);
        return 1;
    } finally {
        if (is_array($shadow) && isset($shadow['temp_root'])) {
            poc6l_remove_tree((string)$shadow['temp_root']);
        }
    }
}

if (PHP_SAPI === 'cli' && realpath($_SERVER['SCRIPT_FILENAME'] ?? '') === __FILE__) {
    exit(poc6l_main());
}
