<?php

return [
    'GET' => [
        '/guidance/login' => 'guidance:pageGuidanceLogin',
        '/guidance/logout' => 'guidance:guidanceLogout',
        '/guidance/book' => 'guidance:pageGuidancePublicBooking',
        '/guidance/book/api/slots' => 'guidance:apiGuidanceBookingSlots',
        '/admin/guidance' => 'guidance:pageGuidanceDashboard',
        '/admin/guidance/pages/dashboard' => 'guidance:pageGuidanceDashboard',
        '/admin/guidance/pages/cases' => 'guidance:pageGuidanceCases',
        '/admin/guidance/pages/cases/new' => 'guidance:modalGuidanceCaseNew',
        '/admin/guidance/pages/cases/{id}' => 'guidance:pageGuidanceCaseView',
        '/admin/guidance/pages/appointments' => 'guidance:pageGuidanceAppointments',
        '/admin/guidance/pages/appointments/new' => 'guidance:modalGuidanceAppointmentNew',
        '/admin/guidance/pages/appointments/{id}' => 'guidance:modalGuidanceAppointmentDetail',
        '/admin/guidance/pages/appointments/{id}/edit' => 'guidance:modalGuidanceAppointmentEdit',
        '/admin/guidance/pages/reports' => 'guidance:pageGuidanceReports',
        '/admin/guidance/reports/cases/{id}/docx' => 'guidance:downloadGuidanceCaseSummaryDocx',
        '/admin/guidance/reports/appointments/docx' => 'guidance:downloadGuidanceAppointmentsDocx',
        '/admin/guidance/pages/trackers' => 'guidance:pageGuidanceTrackers',
        '/admin/guidance/pages/trackers/new' => 'guidance:modalGuidanceTrackerNew',
        '/admin/guidance/pages/trackers/{id}' => 'guidance:pageGuidanceTrackerView',
        '/admin/guidance/pages/trackers/{id}/edit' => 'guidance:modalGuidanceTrackerEdit',
        '/admin/guidance/pages/trackers/{id}/students/new' => 'guidance:modalGuidanceTrackerStudentNew',
        '/admin/guidance/pages/trackers/{id}/students/{studentId}' => 'guidance:modalGuidanceTrackerStudentView',
        '/admin/guidance/pages/trackers/{id}/items/new' => 'guidance:modalGuidanceTrackerItemNew',
        '/admin/guidance/pages/trackers/{id}/items/{itemId}/edit' => 'guidance:modalGuidanceTrackerItemEdit',
        '/admin/guidance/pages/users' => 'guidance:pageGuidanceUsers',
        '/admin/guidance/pages/colleges' => 'guidance:pageGuidanceColleges',
        '/admin/guidance/pages/settings' => 'guidance:pageGuidanceSettings',
        '/admin/guidance/pages/profile' => 'guidance:pageGuidanceProfile',

        '/admin/guidance/pages/users/new' => 'guidance:modalGuidanceUserNew',
        '/admin/guidance/pages/users/{id}/edit' => 'guidance:modalGuidanceUserEdit',
        '/admin/guidance/pages/colleges/new' => 'guidance:modalGuidanceCollegeNew',
        '/admin/guidance/pages/colleges/{id}/edit' => 'guidance:modalGuidanceCollegeEdit',
        '/admin/guidance/api/dashboard/stats' => 'guidance:apiGuidanceDashboardStats',
        '/admin/guidance/api/cases/recent' => 'guidance:apiGuidanceRecentCases',
        '/admin/guidance/api/cases' => 'guidance:apiGuidanceCases',
        '/admin/guidance/api/cases/options' => 'guidance:apiGuidanceCaseOptions',
        '/admin/guidance/api/appointments' => 'guidance:apiGuidanceAppointments',
        '/admin/guidance/api/appointments/pending' => 'guidance:apiGuidancePendingAppointments',
        '/admin/guidance/api/appointments/calendar' => 'guidance:apiGuidanceAppointmentsCalendar',

        '/admin/guidance/api/trackers' => 'guidance:apiGuidanceTrackers',
        '/admin/guidance/api/trackers/{id}/students' => 'guidance:apiGuidanceTrackerStudents',
        '/admin/guidance/api/trackers/{id}/items' => 'guidance:apiGuidanceTrackerItems',

        '/admin/guidance/api/users' => 'guidance:apiGuidanceUsers',
        '/admin/guidance/api/colleges' => 'guidance:apiGuidanceColleges',
        '/admin/guidance/api/settings' => 'guidance:apiGuidanceGetSettings',
    ],
    'POST' => [
        '/guidance/auth/login' => 'guidance:guidanceAuthLogin',
        '/guidance/book/api/booking' => 'guidance:apiGuidancePublicBooking',
        '/admin/guidance/api/profile' => 'guidance:apiGuidanceUpdateOwnProfile',
        '/admin/guidance/api/cases' => 'guidance:apiGuidanceCreateCase',
        '/admin/guidance/api/appointments/{id}/approve' => 'guidance:apiGuidanceApproveAppointment',
        '/admin/guidance/api/appointments/{id}/reject' => 'guidance:apiGuidanceRejectAppointment',
        '/admin/guidance/api/appointments/{id}/complete' => 'guidance:apiGuidanceCompleteAppointment',
        '/admin/guidance/api/appointments/{id}/no-show' => 'guidance:apiGuidanceNoShowAppointment',
        '/admin/guidance/api/appointments/{id}/cancel' => 'guidance:apiGuidanceCancelAppointment',

        '/admin/guidance/api/appointments' => 'guidance:apiGuidanceCreateAppointment',

        '/admin/guidance/api/trackers' => 'guidance:apiGuidanceCreateTracker',
        '/admin/guidance/api/trackers/{id}/students' => 'guidance:apiGuidanceCreateTrackerStudent',
        '/admin/guidance/api/trackers/{id}/items' => 'guidance:apiGuidanceCreateTrackerItem',
        '/admin/guidance/api/trackers/{id}/students/{studentId}/submissions' => 'guidance:apiGuidanceSaveTrackerStudentSubmissions',

        '/admin/guidance/api/users' => 'guidance:apiGuidanceCreateUser',
        '/admin/guidance/api/users/{id}/toggle-active' => 'guidance:apiGuidanceToggleUserActive',
        '/admin/guidance/api/users/{id}/colleges' => 'guidance:apiGuidanceSaveUserColleges',
    ],
    'PUT' => [
        '/admin/guidance/api/users/{id}' => 'guidance:apiGuidanceUpdateUser',
        '/admin/guidance/api/colleges/{id}' => 'guidance:apiGuidanceUpdateCollege',
        '/admin/guidance/api/settings' => 'guidance:apiGuidanceUpdateSettings',
        '/admin/guidance/api/appointments/{id}' => 'guidance:apiGuidanceUpdateAppointment',
        '/admin/guidance/api/trackers/{id}' => 'guidance:apiGuidanceUpdateTracker',
        '/admin/guidance/api/trackers/{id}/items/{itemId}' => 'guidance:apiGuidanceUpdateTrackerItem',
    ],
    'DELETE' => [
        '/admin/guidance/api/users/{id}' => 'guidance:apiGuidanceDeleteUser',
        '/admin/guidance/api/colleges/{id}' => 'guidance:apiGuidanceDeleteCollege',
        '/admin/guidance/api/trackers/{id}' => 'guidance:apiGuidanceDeleteTracker',
        '/admin/guidance/api/trackers/{id}/items/{itemId}' => 'guidance:apiGuidanceDeleteTrackerItem',
        '/admin/guidance/api/trackers/{id}/students/{studentId}' => 'guidance:apiGuidanceDeleteTrackerStudent',
    ],
];
