<?php

declare(strict_types=1);

return [
    'GET' => [
        '/harpp/login' => 'harpp:harppPageLogin',
        '/harpp/forgot-password' => 'harpp:harppPageForgotPassword',
        '/harpp/reset-password' => 'harpp:harppPageResetPassword',
        '/harpp' => 'harpp:harppPageMessenger',
        '/harpp/' => 'harpp:harppPageMessenger',
        '/harpp/decisions' => 'harpp:harppPageDecisions',
        '/harpp/decisions/{id}' => 'harpp:harppPageDecisionDetail',
        '/harpp/settings' => 'harpp:harppPageSettings',
        '/harpp/users' => 'harpp:harppPageUsers',
        '/harpp/notifications' => 'harpp:harppPageNotifications',
        '/harpp/sw.js' => 'harpp:harppServiceWorker',
        '/harpp/manifest.webmanifest' => 'harpp:harppManifest',
        '/harpp/icon.svg' => 'harpp:harppIcon',
        '/api/v1/harpp/auth/me' => 'harpp:harppAuthMe',
        '/api/v1/harpp/settings' => 'harpp:harppSettingsGet',
        '/api/v1/harpp/users' => 'harpp:harppUserList',
        '/api/v1/harpp/decisions' => 'harpp:harppDecisionList',
        '/api/v1/harpp/decisions/{id}' => 'harpp:harppDecisionGet',
        '/api/v1/harpp/conversations' => 'harpp:harppConversationList',
        '/api/v1/harpp/conversations/{id}/messages' => 'harpp:harppMessageList',
        '/api/v1/harpp/notifications' => 'harpp:harppNotificationList',
        '/api/v1/harpp/notifications/unread-count' => 'harpp:harppNotificationUnread',
        '/api/v1/harpp/push/vapid-public-key' => 'harpp:harppPushPublicKey',
        '/api/v1/harpp/adrs' => 'harpp:harppAdrList',
        '/api/v1/harpp/bridge/key' => 'harpp:harppBridgeKeyGet',
        '/api/v1/harpp/bridge/decisions' => 'harpp:harppBridgeDecisionList',
        '/api/v1/harpp/bridge/messages' => 'harpp:harppBridgeMessageList',
    ],
    'POST' => [
        '/api/v1/harpp/auth/login' => 'harpp:harppAuthLogin',
        '/api/v1/harpp/auth/refresh' => 'harpp:harppAuthRefresh',
        '/api/v1/harpp/auth/logout' => 'harpp:harppAuthLogout',
        '/api/v1/harpp/auth/forgot-password' => 'harpp:harppAuthForgotPassword',
        '/api/v1/harpp/auth/reset-password' => 'harpp:harppAuthResetPassword',
        '/api/v1/harpp/auth/register' => 'harpp:harppAuthInvite',
        '/api/v1/harpp/auth/invite' => 'harpp:harppAuthInvite',
        '/api/v1/harpp/auth/select-tenant' => 'harpp:harppAuthSelectTenant',
        '/api/v1/harpp/auth/profile' => 'harpp:harppAuthProfile',
        '/api/v1/harpp/settings' => 'harpp:harppSettingsSave',
        '/api/v1/harpp/users' => 'harpp:harppUserCreate',
        '/api/v1/harpp/decisions' => 'harpp:harppDecisionCreate',
        '/api/v1/harpp/decisions/{id}/transition' => 'harpp:harppDecisionTransition',
        '/api/v1/harpp/conversations' => 'harpp:harppConversationCreate',
        '/api/v1/harpp/conversations/{id}/messages' => 'harpp:harppMessageSend',
        '/api/v1/harpp/conversations/{id}/read' => 'harpp:harppMessageMarkRead',
        '/api/v1/harpp/conversations/{id}/close' => 'harpp:harppConversationClose',
        '/api/v1/harpp/conversations/{id}/archive' => 'harpp:harppConversationArchive',
        '/api/v1/harpp/notifications/{id}/read' => 'harpp:harppNotificationMarkRead',
        '/api/v1/harpp/push/subscribe' => 'harpp:harppPushSubscribe',
        '/api/v1/harpp/push/unsubscribe' => 'harpp:harppPushUnsubscribe',
        '/api/v1/harpp/adrs' => 'harpp:harppAdrRecord',
        '/api/v1/harpp/bridge/key' => 'harpp:harppBridgeKeyRotate',
        '/api/v1/harpp/bridge/key/generate' => 'harpp:harppBridgeKeyGenerate',
        '/api/v1/harpp/bridge/decisions' => 'harpp:harppBridgeDecisionCreate',
        '/api/v1/harpp/bridge/decisions/{id}/view' => 'harpp:harppBridgeDecisionView',
        '/api/v1/harpp/bridge/decisions/{id}/decide' => 'harpp:harppBridgeDecisionDecide',
        '/api/v1/harpp/bridge/decisions/{id}/acknowledge' => 'harpp:harppBridgeDecisionAcknowledge',
        '/api/v1/harpp/bridge/decisions/{id}/cancel' => 'harpp:harppBridgeDecisionCancel',
        '/api/v1/harpp/bridge/decisions/{id}/applied' => 'harpp:harppBridgeDecisionApplied',
        '/api/v1/harpp/bridge/messages' => 'harpp:harppBridgeMessageSend',
        '/api/v1/harpp/bridge/status' => 'harpp:harppBridgeStatus',
    ],
    'PUT' => [
        '/api/v1/harpp/users/{id}' => 'harpp:harppUserUpdate',
    ],
    'PATCH' => [
        '/api/v1/harpp/users/{id}' => 'harpp:harppUserUpdate',
    ],
    'DELETE' => [
        '/api/v1/harpp/users/{id}' => 'harpp:harppUserDelete',
    ],
];
