-- Migration 005: Salary computations
CREATE TABLE IF NOT EXISTS `salary_computations` (
    `computation_id`        INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `tenant_id`             VARCHAR(36) NOT NULL,
    `user_id`               INT UNSIGNED NOT NULL,
    `payroll_period_id`     INT UNSIGNED NOT NULL,
    `employee_profile_id`   INT UNSIGNED DEFAULT NULL,
    `basic_salary`          DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    -- Hours breakdown
    `regular_hours`         DECIMAL(8,2) DEFAULT 0.00,
    `overtime_hours`        DECIMAL(8,2) DEFAULT 0.00,
    `double_overtime_hours` DECIMAL(8,2) DEFAULT 0.00,
    `holiday_hours`         DECIMAL(8,2) DEFAULT 0.00,
    `night_shift_hours`     DECIMAL(8,2) DEFAULT 0.00,
    `rest_day_hours`        DECIMAL(8,2) DEFAULT 0.00,
    `unapproved_hours`      DECIMAL(8,2) DEFAULT 0.00,
    -- Pay components
    `regular_pay`           DECIMAL(12,2) DEFAULT 0.00,
    `overtime_pay`          DECIMAL(12,2) DEFAULT 0.00,
    `double_overtime_pay`   DECIMAL(12,2) DEFAULT 0.00,
    `holiday_pay`           DECIMAL(12,2) DEFAULT 0.00,
    `night_shift_pay`       DECIMAL(12,2) DEFAULT 0.00,
    `rest_day_pay`          DECIMAL(12,2) DEFAULT 0.00,
    `rest_day_premium`      DECIMAL(12,2) DEFAULT 0.00 COMMENT 'The 30% premium portion above regular rate',
    `gross_pay`             DECIMAL(12,2) DEFAULT 0.00,
    -- Government deductions
    `sss_employee`          DECIMAL(10,2) DEFAULT 0.00,
    `philhealth_employee`   DECIMAL(10,2) DEFAULT 0.00,
    `pagibig_employee`      DECIMAL(10,2) DEFAULT 0.00,
    `income_tax`            DECIMAL(10,2) DEFAULT 0.00,
    `sss_employer`          DECIMAL(10,2) DEFAULT 0.00,
    `philhealth_employer`   DECIMAL(10,2) DEFAULT 0.00,
    `pagibig_employer`      DECIMAL(10,2) DEFAULT 0.00,
    -- Other deductions
    `salary_deductions`     DECIMAL(10,2) DEFAULT 0.00,
    `cash_advance_deduction` DECIMAL(10,2) DEFAULT 0.00,
    `other_deductions`      DECIMAL(10,2) DEFAULT 0.00,
    `total_deductions`      DECIMAL(12,2) DEFAULT 0.00,
    `total_additions`       DECIMAL(12,2) DEFAULT 0.00 COMMENT 'Positive adjustments added to gross',
    `net_pay`               DECIMAL(12,2) DEFAULT 0.00,
    `total_employer_cost`   DECIMAL(12,2) DEFAULT 0.00,
    -- Workflow
    `status`                ENUM('draft','computed','approved','paid','cancelled') DEFAULT 'draft',
    `computed_by`           INT UNSIGNED DEFAULT NULL,
    `approved_by`           INT UNSIGNED DEFAULT NULL,
    `paid_by`               INT UNSIGNED DEFAULT NULL,
    `computation_date`      DATETIME DEFAULT NULL,
    `approval_date`         DATETIME DEFAULT NULL,
    `payment_date`          DATETIME DEFAULT NULL,
    `notes`                 TEXT DEFAULT NULL,
    `created_at`            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`computation_id`),
    UNIQUE INDEX `idx_tenant_user_period` (`tenant_id`, `user_id`, `payroll_period_id`),
    INDEX `idx_period` (`payroll_period_id`),
    INDEX `idx_status` (`tenant_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
