<?php
/**
 * Test Theme Theme Functions
 * 
 * DiSyL-powered WordPress theme
 * Generated by Ikabud Theme Builder
 * 
 * @package test-theme
 * @version 1.0.0
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

// Theme constants
define('TEST_THEME_VERSION', '1.0.0');
define('TEST_THEME_DIR', get_template_directory());
define('TEST_THEME_URI', get_template_directory_uri());

/**
 * Load theme includes
 */
require_once get_template_directory() . '/includes/class-theme-manifest.php';
require_once get_template_directory() . '/includes/class-theme-customizer.php';
require_once get_template_directory() . '/includes/template-functions.php';

/**
 * Theme Setup
 */
function test-theme_setup() {
    // Add theme support
    add_theme_support('title-tag');
    add_theme_support('post-thumbnails');
    add_theme_support('automatic-feed-links');
    add_theme_support('html5', array(
        'search-form',
        'comment-form',
        'comment-list',
        'gallery',
        'caption',
    ));
    add_theme_support('custom-logo', array(
        'height'      => 100,
        'width'       => 400,
        'flex-height' => true,
        'flex-width'  => true,
    ));
    add_theme_support('custom-background');
    add_theme_support('customize-selective-refresh-widgets');
    
    // Register navigation menus
    register_nav_menus(array(
        'primary' => __('Primary Menu', 'test-theme'),
        'footer' => __('Footer Menu', 'test-theme'),
    ));
    
    // Add image sizes
    add_image_size('test-theme-hero', 1920, 1080, true);
    add_image_size('test-theme-featured', 800, 600, true);
    add_image_size('test-theme-thumbnail', 400, 300, true);
}
add_action('after_setup_theme', 'test-theme_setup');

/**
 * Register Widget Areas
 */
function test-theme_widgets_init() {
    // Main Sidebar
    register_sidebar(array(
        'name'          => __('Main Sidebar', 'test-theme'),
        'id'            => 'sidebar-1',
        'description'   => __('Main sidebar widget area', 'test-theme'),
        'before_widget' => '<div id="%1$s" class="widget %2$s">',
        'after_widget'  => '</div>',
        'before_title'  => '<h3 class="widget-title">',
        'after_title'   => '</h3>',
    ));
    
    // Footer widgets
    for ($i = 1; $i <= 4; $i++) {
        register_sidebar(array(
            'name'          => sprintf(__('Footer Widget %d', 'test-theme'), $i),
            'id'            => 'footer-' . $i,
            'description'   => sprintf(__('Footer widget area %d', 'test-theme'), $i),
            'before_widget' => '<div id="%1$s" class="footer-widget %2$s">',
            'after_widget'  => '</div>',
            'before_title'  => '<h3 class="widget-title">',
            'after_title'   => '</h3>',
        ));
    }
}
add_action('widgets_init', 'test-theme_widgets_init');

/**
 * Enqueue Scripts and Styles
 */
function test-theme_scripts() {
    // DiSyL components stylesheet
    wp_enqueue_style('disyl-components', get_template_directory_uri() . '/assets/css/disyl-components.css', array(), TEST_THEME_VERSION);
    
    // Theme stylesheet
    wp_enqueue_style('test-theme-style', get_stylesheet_uri(), array('disyl-components'), TEST_THEME_VERSION);
    
    // Theme JavaScript
    wp_enqueue_script('test-theme-scripts', get_template_directory_uri() . '/assets/js/theme.js', array(), TEST_THEME_VERSION, true);
    
    // Localize script
    wp_localize_script('test-theme-scripts', 'testThemeData', array(
        'ajaxurl' => admin_url('admin-ajax.php'),
        'nonce'   => wp_create_nonce('test-theme-nonce'),
    ));
    
    // Comment reply script
    if (is_singular() && comments_open() && get_option('thread_comments')) {
        wp_enqueue_script('comment-reply');
    }
}
add_action('wp_enqueue_scripts', 'test-theme_scripts');

/**
 * Enable DiSyL support
 */
add_theme_support('ikabud-disyl');

/**
 * Extend DiSyL context with theme-specific data
 */
function test-theme_extend_disyl_context($context) {
    // Add menu data
    $context['menu'] = array(
        'primary' => test-theme_get_menu_items('primary'),
        'footer' => test-theme_get_menu_items('footer'),
    );
    
    // Add widget areas
    $context['widgets'] = array(
        'sidebar' => test-theme_get_widget_area('sidebar-1'),
        'footer_1' => test-theme_get_widget_area('footer-1'),
        'footer_2' => test-theme_get_widget_area('footer-2'),
        'footer_3' => test-theme_get_widget_area('footer-3'),
        'footer_4' => test-theme_get_widget_area('footer-4'),
    );
    
    return $context;
}
add_filter('ikabud_disyl_context', 'test-theme_extend_disyl_context');

/**
 * Get Menu Items for DiSyL Context
 */
function test-theme_get_menu_items($location) {
    $locations = get_nav_menu_locations();
    
    if (!isset($locations[$location])) {
        return array();
    }
    
    $menu = wp_get_nav_menu_object($locations[$location]);
    
    if (!$menu) {
        return array();
    }
    
    $menu_items = wp_get_nav_menu_items($menu->term_id);
    
    if (!$menu_items) {
        return array();
    }
    
    return test-theme_build_menu_tree($menu_items, 0);
}

/**
 * Build hierarchical menu tree
 */
function test-theme_build_menu_tree($menu_items, $parent_id = 0) {
    $branch = array();
    
    foreach ($menu_items as $item) {
        $item_parent = (int)$item->menu_item_parent;
        
        if ($item_parent == $parent_id) {
            $children = test-theme_build_menu_tree($menu_items, $item->ID);
            
            $classes = $item->classes;
            if (!empty($children)) {
                $classes[] = 'has-submenu';
            }
            
            $branch[] = array(
                'id' => $item->ID,
                'title' => $item->title,
                'url' => $item->url,
                'target' => $item->target,
                'classes' => implode(' ', $classes),
                'active' => ($item->url === home_url($_SERVER['REQUEST_URI'])),
                'children' => $children,
            );
        }
    }
    
    return $branch;
}

/**
 * Get widget area content
 */
function test-theme_get_widget_area($sidebar_id) {
    if (!is_active_sidebar($sidebar_id)) {
        return array(
            'active' => false,
            'content' => '',
        );
    }
    
    ob_start();
    dynamic_sidebar($sidebar_id);
    $content = ob_get_clean();
    
    return array(
        'active' => true,
        'content' => $content,
    );
}
