<?php
/**
 * Guidance Monitoring — State Machine Test
 *
 * Auto-generated by generate-module-test.php
 * Tests status transitions: array (
  0 => 'scheduled_date',
  1 => 'scheduled_time',
  2 => 'duration_minutes',
  3 => 'appointment_type',
  4 => 'appointment_type_id',
  5 => 'purpose',
  6 => 'location',
  7 => 'notes',
  8 => 'status',
)
 * Source: modules/guidance/handlers/25-appointments.php
 *
 * Pure logic — no bootstrap, no DB required.
 * Replicable pattern from PAL JobOrderWorkflow test.
 *
 * Usage: php tests/guidance/guidance_state_machine_test.php
 */

declare(strict_types=1);

require_once __DIR__ . '/../harness/TestHarness.php';

$h = new TestHarness('guidance-state-machine');

// Known allowed statuses (extracted from source)
$statuses = array (
  0 => 'scheduled_date',
  1 => 'scheduled_time',
  2 => 'duration_minutes',
  3 => 'appointment_type',
  4 => 'appointment_type_id',
  5 => 'purpose',
  6 => 'location',
  7 => 'notes',
  8 => 'status',
);

// Define allowed transitions based on source code analysis.
// KEY: from status → array of allowed target statuses.
// ALL other combinations in the N×N matrix must return false.
$allowed = [];
foreach ($statuses as $s) {
    $allowed[$s] = $statuses; // Placeholder — replace with actual transition rules
}
// Remove self-transitions
foreach ($allowed as $from => $tos) {
    $allowed[$from] = array_values(array_filter($tos, fn($t) => $t !== $from));
}

// Add forbidden transitions (extracted from source):
// $forbidden = ['closed' => ['open', 'in_progress', 'on_hold']];

$h->section('Exhaustive ' . count($statuses) . '×' . count($statuses) . ' transition matrix');

$asserted = 0;
foreach ($statuses as $from) {
    foreach ($statuses as $to) {
        // Replace this logic with actual isAllowed() call to the service
        $expected = in_array($to, $allowed[$from] ?? [], true);
        $label = "{$from} → {$to} = " . ($expected ? 'ALLOWED' : 'FORBIDDEN');
        $h->test($label, true); // Placeholder — replace with actual assertion
        $asserted++;
    }
}

$h->section('Label mapping');
foreach ($statuses as $s) {
    $label = ucfirst(str_replace('_', ' ', $s));
    $h->test("{$s} → '{$label}'", true); // Placeholder
}

$h->section('Gap analysis — integration tests needed');
$h->gap('DB: actual status transitions persist correctly');
$h->gap('DB: forbidden transitions throw/return error');
$h->gap('DB: version conflict detection');
$h->gap('DB: audit trail written on transition');
$h->gap('DB: status history recorded');

$h->done();