<?php
/**
 * Guidance Monitoring — Integration Test
 *
 * Auto-generated by generate-module-test.php
 * Tests DB-backed business logic.
 *
 * Prerequisites: tenant host 'guidance.test' must resolve
 * with a database containing guidance tables.
 *
 * Usage: php tests/guidance/guidance_integration_test.php
 */

declare(strict_types=1);

require_once __DIR__ . '/../harness/TestHarness.php';

$h = new TestHarness('guidance-integration', TestHarness::MODE_INTEGRATION, 'guidance.test');
$h->fingerprint('modules/guidance/module.json');
$h->fingerprint('modules/guidance/helpers.php');

// ── Load module ───────────────────────────────────────────────
$h->loadModule('modules/guidance/helpers.php');
$h->loadModule('modules/guidance/handlers.php');

$db = app()->db();
$testTenantId = (int)(app()->tenant()->current() ?? 999990);
$ownsTables = array (
  0 => 'gm_users',
  1 => 'gm_password_resets',
  2 => 'gm_otp_codes',
  3 => 'gm_rate_limits',
  4 => 'gm_colleges',
  5 => 'gm_counselor_assignments',
  6 => 'gm_cases',
  7 => 'gm_case_status_history',
  8 => 'gm_counselor_notes',
  9 => 'gm_attachments',
  10 => 'gm_appointment_types',
  11 => 'gm_appointments',
  12 => 'gm_blocked_dates',
  13 => 'gm_counselor_availability',
  14 => 'gm_notifications',
  15 => 'gm_notification_queue',
  16 => 'gm_settings',
  17 => 'gm_form_fields',
  18 => 'gm_audit_logs',
  19 => 'gm_sync_queue',
  20 => 'gm_trackers',
  21 => 'gm_tracker_items',
  22 => 'gm_tracker_students',
  23 => 'gm_tracker_submissions',
  24 => 'gm_tracker_custom_fields',
  25 => 'gm_migrations',
);
$moduleDb = new \Ikabud\Kernel\Contracts\ModuleDB($db, 'guidance', $ownsTables, []);

// ── Cleanup ───────────────────────────────────────────────────
foreach ($ownsTables as $t) {
    try { $db->exec("DELETE FROM {$t} WHERE tenant_id = {$testTenantId}"); } catch (\Throwable $e) {}
}

$h->section('Database connection');
try {
    $dbName = $db->query('SELECT DATABASE()')->fetchColumn();
    $h->test('connected to database', $dbName !== false && $dbName !== '');
} catch (\Exception $e) {
    $h->test('database connection', false, $e->getMessage());
}

$h->section('Core tables exist');
$coreTables = array_slice($ownsTables, 0, 5);
foreach ($coreTables as $t) {
    try {
        $db->query("SELECT COUNT(*) FROM {$t} LIMIT 1");
        $h->test("table {$t} accessible", true);
    } catch (\Exception $e) {
        $h->test("table {$t} accessible", false, $e->getMessage());
    }
}

$h->section('Gap analysis');
$h->gap('CRUD operations on core entities');
$h->gap('Business logic validation (unique constraints, required fields)');
$h->gap('Event emission on create/update/delete');
$h->gap('Audit trail on mutations');

$h->done();