<?php
/**
 * Guidance Monitoring — Manifest Contract Test
 *
 * Auto-generated by generate-module-test.php
 * Validates module.json structure and file existence.
 *
 * Usage: php tests/guidance/manifest_test.php
 */

declare(strict_types=1);

require_once __DIR__ . '/../harness/TestHarness.php';

$h = new TestHarness('guidance-manifest');
$h->fingerprint('modules/guidance/module.json');

$manifestPath = $h->basePath() . '/modules/guidance/module.json';
$manifest = json_decode((string) file_get_contents($manifestPath), true);

$h->section('Module identity');
$h->test('module id is guidance', ($manifest['id'] ?? '') === 'guidance');
$h->test('module.json is valid JSON', is_array($manifest));

$h->section('Owned tables');
$h->test('owns_tables declared', is_array($manifest['owns_tables'] ?? null));
$h->test(count($ownsTables) . ' owned tables', count($manifest['owns_tables'] ?? []) >= 1);

$h->section('Capabilities');
$h->test('depends on kernel.auth.user@1', in_array('kernel.auth.user@1', $manifest['capabilities']['depends'] ?? [], true));

$h->section('File existence');
$h->test('routes.php exists', is_file($h->basePath() . '/modules/guidance/routes.php'));
$h->test('handlers.php exists', is_file($h->basePath() . '/modules/guidance/handlers.php'));
$h->test('helpers.php exists', is_file($h->basePath() . '/modules/guidance/helpers.php'));

$h->section('PHP syntax');
$allPhp = array_merge(
    glob($h->basePath() . '/modules/guidance/*.php'),
    glob($h->basePath() . '/modules/guidance/handlers/*.php'),
);
$syntaxOk = true;
foreach ($allPhp as $f) {
    $output = shell_exec('php -l ' . escapeshellarg($f) . ' 2>/dev/null');
    if ($output === null || !str_contains($output, 'No syntax errors')) {
        $h->test('Syntax: ' . basename($f), false, $output ?? 'exec failed');
        $syntaxOk = false;
    }
}
if ($syntaxOk) $h->test('All PHP files pass syntax check', true);

$h->section('Gap analysis');
$h->gap('Auth-owned user table CRUD operations');
$h->gap('Settings read/write through manifest contract');
$h->gap('Navigation items resolve to valid handlers');
$h->gap('Entity view contracts in helpers/views/');

$h->done();