/**
 * Browser tests for Guidance Monitoring Dashboard
 *
 * Auto-generated by generate-module-test.php
 *
 * Run: npx playwright test tests/browser/modules/guidance/
 *
 * @see modules/guidance
 */

// @ts-check
const { test, expect } = require('../WorkbenchFixture');

test.describe('guidance:dashboard', () => {

    test.beforeEach(async ({ page }) => {
        await page.goto(`/guidance/login`);
        await page.fill('input[name="username"]', 'admin');
        await page.fill('input[name="password"]', 'password');
        await page.click('button[type="submit"]');
        await page.waitForURL('**/admin/guidance');
        await page.waitForSelector('[data-wb-component="app-shell"]', { timeout: 10000 });
    });

    test('renders with app shell', async ({ page, shell }) => {
        await shell.expectVisible();
        await shell.expectAppName();
    });

    test('dashboard page title is visible', async ({ page }) => {
        await expect(page.locator('h1')).toBeVisible();
    });

    // ── Gaps ──
    test('known coverage gaps', async ({ integrity }) => {
        integrity.gap('Sidebar navigation items reflect guidance routes');
        integrity.gap('Summary cards display correct counts');
        integrity.gap('Quick-action buttons navigate to create pages');
        integrity.gap('Mobile responsive layout at 375px');
        integrity.gap('Page title matches nav item label');
    });
});